tmp_dir = "bin/air"

[build]
cmd = "make -C .. buildbackend BACKEND_BINARY=backend/bin/air/crypto-scanner"
entrypoint = ["./bin/air/crypto-scanner"]
send_interrupt = true
kill_delay = "15s"

[misc]
clean_on_exit = true
