// Code generated by go run ./gen; DO NOT EDIT.

package talib

import (
	"crypto-scanner/internal/indicator"

	ta "github.com/TA-Lib/ta-lib-cgo"
)

var functions = []spec{
	{
		name:          "ACCBANDS",
		indicatorType: "accbands",
		title:         "Acceleration Bands",
		group:         "Overlap Studies",
		overlap:       true,
		inputs:        []string{"high", "low", "close"},
		params: []param{
			{key: "period", title: "Time Period", description: "Number of period", kind: paramInteger, minimum: 2, maximum: 100000, defaultValue: 20},
		},
		outputs: []output{
			{name: "upperband", style: indicator.OutputUpperLimit},
			{name: "middleband", style: indicator.OutputLine},
			{name: "lowerband", style: indicator.OutputLowerLimit},
		},
		lookback: func(p []float64) int { return ta.AccbandsLookback(int(p[0])) },
		call: func(in [][]float64, p []float64) [][]float64 {
			o0, o1, o2 := ta.Accbands(in[0], in[1], in[2], int(p[0]), nil, nil, nil)
			return [][]float64{o0, o1, o2}
		},
	},
	{
		name:          "AD",
		indicatorType: "ad",
		title:         "Chaikin A/D Line",
		group:         "Volume Indicators",
		inputs:        []string{"high", "low", "close", "volume"},
		outputs: []output{
			{name: "ad", style: indicator.OutputLine},
		},
		lookback: func(p []float64) int { return ta.AdLookback() },
		call: func(in [][]float64, p []float64) [][]float64 {
			o0 := ta.Ad(in[0], in[1], in[2], in[3], nil)
			return [][]float64{o0}
		},
	},
	{
		name:          "ADOSC",
		indicatorType: "adosc",
		title:         "Chaikin A/D Oscillator",
		group:         "Volume Indicators",
		inputs:        []string{"high", "low", "close", "volume"},
		params: []param{
			{key: "fast_period", title: "Fast Period", description: "Number of period for the fast MA", kind: paramInteger, minimum: 2, maximum: 100000, defaultValue: 3},
			{key: "slow_period", title: "Slow Period", description: "Number of period for the slow MA", kind: paramInteger, minimum: 2, maximum: 100000, defaultValue: 10},
		},
		outputs: []output{
			{name: "adosc", style: indicator.OutputLine},
		},
		lookback: func(p []float64) int { return ta.AdoscLookback(int(p[0]), int(p[1])) },
		call: func(in [][]float64, p []float64) [][]float64 {
			o0 := ta.Adosc(in[0], in[1], in[2], in[3], int(p[0]), int(p[1]), nil)
			return [][]float64{o0}
		},
	},
	{
		name:          "ADX",
		indicatorType: "adx",
		title:         "Average Directional Movement Index",
		group:         "Momentum Indicators",
		unstable:      true,
		inputs:        []string{"high", "low", "close"},
		params: []param{
			{key: "period", title: "Time Period", description: "Number of period", kind: paramInteger, minimum: 2, maximum: 100000, defaultValue: 14},
		},
		outputs: []output{
			{name: "adx", style: indicator.OutputLine},
		},
		lookback: func(p []float64) int { return ta.AdxLookback(int(p[0])) },
		call: func(in [][]float64, p []float64) [][]float64 {
			o0 := ta.Adx(in[0], in[1], in[2], int(p[0]), nil)
			return [][]float64{o0}
		},
	},
	{
		name:          "ADXR",
		indicatorType: "adxr",
		title:         "Average Directional Movement Index Rating",
		group:         "Momentum Indicators",
		unstable:      true,
		inputs:        []string{"high", "low", "close"},
		params: []param{
			{key: "period", title: "Time Period", description: "Number of period", kind: paramInteger, minimum: 2, maximum: 100000, defaultValue: 14},
		},
		outputs: []output{
			{name: "adxr", style: indicator.OutputLine},
		},
		lookback: func(p []float64) int { return ta.AdxrLookback(int(p[0])) },
		call: func(in [][]float64, p []float64) [][]float64 {
			o0 := ta.Adxr(in[0], in[1], in[2], int(p[0]), nil)
			return [][]float64{o0}
		},
	},
	{
		name:          "APO",
		indicatorType: "apo",
		title:         "Absolute Price Oscillator",
		group:         "Momentum Indicators",
		inputs:        []string{"close"},
		params: []param{
			{key: "fast_period", title: "Fast Period", description: "Number of period for the fast MA", kind: paramInteger, minimum: 2, maximum: 100000, defaultValue: 12},
			{key: "slow_period", title: "Slow Period", description: "Number of period for the slow MA", kind: paramInteger, minimum: 2, maximum: 100000, defaultValue: 26},
			{key: "ma_type", title: "MA Type", description: "Type of Moving Average", kind: paramMAType, defaultValue: 0},
		},
		outputs: []output{
			{name: "apo", style: indicator.OutputLine},
		},
		lookback: func(p []float64) int { return ta.ApoLookback(int(p[0]), int(p[1]), int(p[2])) },
		call: func(in [][]float64, p []float64) [][]float64 {
			o0 := ta.Apo(in[0], int(p[0]), int(p[1]), int(p[2]), nil)
			return [][]float64{o0}
		},
	},
	{
		name:          "AROON",
		indicatorType: "aroon",
		title:         "Aroon",
		group:         "Momentum Indicators",
		inputs:        []string{"high", "low"},
		params: []param{
			{key: "period", title: "Time Period", description: "Number of period", kind: paramInteger, minimum: 2, maximum: 100000, defaultValue: 14},
		},
		outputs: []output{
			{name: "aroondown", style: indicator.OutputDashedLine},
			{name: "aroonup", style: indicator.OutputLine},
		},
		lookback: func(p []float64) int { return ta.AroonLookback(int(p[0])) },
		call: func(in [][]float64, p []float64) [][]float64 {
			o0, o1 := ta.Aroon(in[0], in[1], int(p[0]), nil, nil)
			return [][]float64{o0, o1}
		},
	},
	{
		name:          "AROONOSC",
		indicatorType: "aroonosc",
		title:         "Aroon Oscillator",
		group:         "Momentum Indicators",
		inputs:        []string{"high", "low"},
		params: []param{
			{key: "period", title: "Time Period", description: "Number of period", kind: paramInteger, minimum: 2, maximum: 100000, defaultValue: 14},
		},
		outputs: []output{
			{name: "aroonosc", style: indicator.OutputLine},
		},
		lookback: func(p []float64) int { return ta.AroonoscLookback(int(p[0])) },
		call: func(in [][]float64, p []float64) [][]float64 {
			o0 := ta.Aroonosc(in[0], in[1], int(p[0]), nil)
			return [][]float64{o0}
		},
	},
	{
		name:          "ATR",
		indicatorType: "atr",
		title:         "Average True Range",
		group:         "Volatility Indicators",
		unstable:      true,
		inputs:        []string{"high", "low", "close"},
		params: []param{
			{key: "period", title: "Time Period", description: "Number of period", kind: paramInteger, minimum: 1, maximum: 100000, defaultValue: 14},
		},
		outputs: []output{
			{name: "atr", style: indicator.OutputLine},
		},
		lookback: func(p []float64) int { return ta.AtrLookback(int(p[0])) },
		call: func(in [][]float64, p []float64) [][]float64 {
			o0 := ta.Atr(in[0], in[1], in[2], int(p[0]), nil)
			return [][]float64{o0}
		},
	},
	{
		name:          "AVGPRICE",
		indicatorType: "avgprice",
		title:         "Average Price",
		group:         "Price Transform",
		overlap:       true,
		inputs:        []string{"open", "high", "low", "close"},
		outputs: []output{
			{name: "avgprice", style: indicator.OutputLine},
		},
		lookback: func(p []float64) int { return ta.AvgpriceLookback() },
		call: func(in [][]float64, p []float64) [][]float64 {
			o0 := ta.Avgprice(in[0], in[1], in[2], in[3], nil)
			return [][]float64{o0}
		},
	},
	{
		name:          "AVGDEV",
		indicatorType: "avgdev",
		title:         "Average Deviation",
		group:         "Price Transform",
		overlap:       true,
		inputs:        []string{"close"},
		params: []param{
			{key: "period", title: "Time Period", description: "Number of period", kind: paramInteger, minimum: 2, maximum: 100000, defaultValue: 14},
		},
		outputs: []output{
			{name: "avgdev", style: indicator.OutputLine},
		},
		lookback: func(p []float64) int { return ta.AvgdevLookback(int(p[0])) },
		call: func(in [][]float64, p []float64) [][]float64 {
			o0 := ta.Avgdev(in[0], int(p[0]), nil)
			return [][]float64{o0}
		},
	},
	{
		name:          "BBANDS",
		indicatorType: "bbands",
		title:         "Bollinger Bands",
		group:         "Overlap Studies",
		overlap:       true,
		inputs:        []string{"close"},
		params: []param{
			{key: "period", title: "Time Period", description: "Number of period", kind: paramInteger, minimum: 2, maximum: 100000, defaultValue: 5},
			{key: "deviations_up", title: "Deviations up", description: "Deviation multiplier for upper band", kind: paramReal, minimum: -3e+37, maximum: 3e+37, defaultValue: 2},
			{key: "deviations_down", title: "Deviations down", description: "Deviation multiplier for lower band", kind: paramReal, minimum: -3e+37, maximum: 3e+37, defaultValue: 2},
			{key: "ma_type", title: "MA Type", description: "Type of Moving Average", kind: paramMAType, defaultValue: 0},
		},
		outputs: []output{
			{name: "upperband", style: indicator.OutputUpperLimit},
			{name: "middleband", style: indicator.OutputLine},
			{name: "lowerband", style: indicator.OutputLowerLimit},
		},
		lookback: func(p []float64) int { return ta.BbandsLookback(int(p[0]), p[1], p[2], int(p[3])) },
		call: func(in [][]float64, p []float64) [][]float64 {
			o0, o1, o2 := ta.Bbands(in[0], int(p[0]), p[1], p[2], int(p[3]), nil, nil, nil)
			return [][]float64{o0, o1, o2}
		},
	},
	{
		name:          "BOP",
		indicatorType: "bop",
		title:         "Balance Of Power",
		group:         "Momentum Indicators",
		inputs:        []string{"open", "high", "low", "close"},
		outputs: []output{
			{name: "bop", style: indicator.OutputLine},
		},
		lookback: func(p []float64) int { return ta.BopLookback() },
		call: func(in [][]float64, p []float64) [][]float64 {
			o0 := ta.Bop(in[0], in[1], in[2], in[3], nil)
			return [][]float64{o0}
		},
	},
	{
		name:          "CCI",
		indicatorType: "cci",
		title:         "Commodity Channel Index",
		group:         "Momentum Indicators",
		inputs:        []string{"high", "low", "close"},
		params: []param{
			{key: "period", title: "Time Period", description: "Number of period", kind: paramInteger, minimum: 2, maximum: 100000, defaultValue: 14},
		},
		outputs: []output{
			{name: "cci", style: indicator.OutputLine},
		},
		lookback: func(p []float64) int { return ta.CciLookback(int(p[0])) },
		call: func(in [][]float64, p []float64) [][]float64 {
			o0 := ta.Cci(in[0], in[1], in[2], int(p[0]), nil)
			return [][]float64{o0}
		},
	},
	{
		name:          "CDL2CROWS",
		indicatorType: "cdl2crows",
		title:         "Two Crows",
		group:         "Pattern Recognition",
		candlestick:   true,
		inputs:        []string{"open", "high", "low", "close"},
		outputs: []output{
			{name: "cdl2crows", style: indicator.OutputLine},
		},
		lookback: func(p []float64) int { return ta.Cdl2crowsLookback() },
		call: func(in [][]float64, p []float64) [][]float64 {
			o0 := ta.Cdl2crows(in[0], in[1], in[2], in[3], nil)
			return [][]float64{integers(o0)}
		},
	},
	{
		name:          "CDL3BLACKCROWS",
		indicatorType: "cdl3blackcrows",
		title:         "Three Black Crows",
		group:         "Pattern Recognition",
		candlestick:   true,
		inputs:        []string{"open", "high", "low", "close"},
		outputs: []output{
			{name: "cdl3blackcrows", style: indicator.OutputLine},
		},
		lookback: func(p []float64) int { return ta.Cdl3blackcrowsLookback() },
		call: func(in [][]float64, p []float64) [][]float64 {
			o0 := ta.Cdl3blackcrows(in[0], in[1], in[2], in[3], nil)
			return [][]float64{integers(o0)}
		},
	},
	{
		name:          "CDL3INSIDE",
		indicatorType: "cdl3inside",
		title:         "Three Inside Up/Down",
		group:         "Pattern Recognition",
		candlestick:   true,
		inputs:        []string{"open", "high", "low", "close"},
		outputs: []output{
			{name: "cdl3inside", style: indicator.OutputLine},
		},
		lookback: func(p []float64) int { return ta.Cdl3insideLookback() },
		call: func(in [][]float64, p []float64) [][]float64 {
			o0 := ta.Cdl3inside(in[0], in[1], in[2], in[3], nil)
			return [][]float64{integers(o0)}
		},
	},
	{
		name:          "CDL3LINESTRIKE",
		indicatorType: "cdl3linestrike",
		title:         "Three-Line Strike ",
		group:         "Pattern Recognition",
		candlestick:   true,
		inputs:        []string{"open", "high", "low", "close"},
		outputs: []output{
			{name: "cdl3linestrike", style: indicator.OutputLine},
		},
		lookback: func(p []float64) int { return ta.Cdl3linestrikeLookback() },
		call: func(in [][]float64, p []float64) [][]float64 {
			o0 := ta.Cdl3linestrike(in[0], in[1], in[2], in[3], nil)
			return [][]float64{integers(o0)}
		},
	},
	{
		name:          "CDL3OUTSIDE",
		indicatorType: "cdl3outside",
		title:         "Three Outside Up/Down",
		group:         "Pattern Recognition",
		candlestick:   true,
		inputs:        []string{"open", "high", "low", "close"},
		outputs: []output{
			{name: "cdl3outside", style: indicator.OutputLine},
		},
		lookback: func(p []float64) int { return ta.Cdl3outsideLookback() },
		call: func(in [][]float64, p []float64) [][]float64 {
			o0 := ta.Cdl3outside(in[0], in[1], in[2], in[3], nil)
			return [][]float64{integers(o0)}
		},
	},
	{
		name:          "CDL3STARSINSOUTH",
		indicatorType: "cdl3starsinsouth",
		title:         "Three Stars In The South",
		group:         "Pattern Recognition",
		candlestick:   true,
		inputs:        []string{"open", "high", "low", "close"},
		outputs: []output{
			{name: "cdl3starsinsouth", style: indicator.OutputLine},
		},
		lookback: func(p []float64) int { return ta.Cdl3starsinsouthLookback() },
		call: func(in [][]float64, p []float64) [][]float64 {
			o0 := ta.Cdl3starsinsouth(in[0], in[1], in[2], in[3], nil)
			return [][]float64{integers(o0)}
		},
	},
	{
		name:          "CDL3WHITESOLDIERS",
		indicatorType: "cdl3whitesoldiers",
		title:         "Three Advancing White Soldiers",
		group:         "Pattern Recognition",
		candlestick:   true,
		inputs:        []string{"open", "high", "low", "close"},
		outputs: []output{
			{name: "cdl3whitesoldiers", style: indicator.OutputLine},
		},
		lookback: func(p []float64) int { return ta.Cdl3whitesoldiersLookback() },
		call: func(in [][]float64, p []float64) [][]float64 {
			o0 := ta.Cdl3whitesoldiers(in[0], in[1], in[2], in[3], nil)
			return [][]float64{integers(o0)}
		},
	},
	{
		name:          "CDLABANDONEDBABY",
		indicatorType: "cdlabandonedbaby",
		title:         "Abandoned Baby",
		group:         "Pattern Recognition",
		candlestick:   true,
		inputs:        []string{"open", "high", "low", "close"},
		params: []param{
			{key: "penetration", title: "Penetration", description: "Percentage of penetration of a candle within another candle", kind: paramReal, minimum: 0, maximum: 3e+37, defaultValue: 0.3},
		},
		outputs: []output{
			{name: "cdlabandonedbaby", style: indicator.OutputLine},
		},
		lookback: func(p []float64) int { return ta.CdlabandonedbabyLookback(p[0]) },
		call: func(in [][]float64, p []float64) [][]float64 {
			o0 := ta.Cdlabandonedbaby(in[0], in[1], in[2], in[3], p[0], nil)
			return [][]float64{integers(o0)}
		},
	},
	{
		name:          "CDLADVANCEBLOCK",
		indicatorType: "cdladvanceblock",
		title:         "Advance Block",
		group:         "Pattern Recognition",
		candlestick:   true,
		inputs:        []string{"open", "high", "low", "close"},
		outputs: []output{
			{name: "cdladvanceblock", style: indicator.OutputLine},
		},
		lookback: func(p []float64) int { return ta.CdladvanceblockLookback() },
		call: func(in [][]float64, p []float64) [][]float64 {
			o0 := ta.Cdladvanceblock(in[0], in[1], in[2], in[3], nil)
			return [][]float64{integers(o0)}
		},
	},
	{
		name:          "CDLBELTHOLD",
		indicatorType: "cdlbelthold",
		title:         "Belt-hold",
		group:         "Pattern Recognition",
		candlestick:   true,
		inputs:        []string{"open", "high", "low", "close"},
		outputs: []output{
			{name: "cdlbelthold", style: indicator.OutputLine},
		},
		lookback: func(p []float64) int { return ta.CdlbeltholdLookback() },
		call: func(in [][]float64, p []float64) [][]float64 {
			o0 := ta.Cdlbelthold(in[0], in[1], in[2], in[3], nil)
			return [][]float64{integers(o0)}
		},
	},
	{
		name:          "CDLBREAKAWAY",
		indicatorType: "cdlbreakaway",
		title:         "Breakaway",
		group:         "Pattern Recognition",
		candlestick:   true,
		inputs:        []string{"open", "high", "low", "close"},
		outputs: []output{
			{name: "cdlbreakaway", style: indicator.OutputLine},
		},
		lookback: func(p []float64) int { return ta.CdlbreakawayLookback() },
		call: func(in [][]float64, p []float64) [][]float64 {
			o0 := ta.Cdlbreakaway(in[0], in[1], in[2], in[3], nil)
			return [][]float64{integers(o0)}
		},
	},
	{
		name:          "CDLCLOSINGMARUBOZU",
		indicatorType: "cdlclosingmarubozu",
		title:         "Closing Marubozu",
		group:         "Pattern Recognition",
		candlestick:   true,
		inputs:        []string{"open", "high", "low", "close"},
		outputs: []output{
			{name: "cdlclosingmarubozu", style: indicator.OutputLine},
		},
		lookback: func(p []float64) int { return ta.CdlclosingmarubozuLookback() },
		call: func(in [][]float64, p []float64) [][]float64 {
			o0 := ta.Cdlclosingmarubozu(in[0], in[1], in[2], in[3], nil)
			return [][]float64{integers(o0)}
		},
	},
	{
		name:          "CDLCONCEALBABYSWALL",
		indicatorType: "cdlconcealbabyswall",
		title:         "Concealing Baby Swallow",
		group:         "Pattern Recognition",
		candlestick:   true,
		inputs:        []string{"open", "high", "low", "close"},
		outputs: []output{
			{name: "cdlconcealbabyswall", style: indicator.OutputLine},
		},
		lookback: func(p []float64) int { return ta.CdlconcealbabyswallLookback() },
		call: func(in [][]float64, p []float64) [][]float64 {
			o0 := ta.Cdlconcealbabyswall(in[0], in[1], in[2], in[3], nil)
			return [][]float64{integers(o0)}
		},
	},
	{
		name:          "CDLCOUNTERATTACK",
		indicatorType: "cdlcounterattack",
		title:         "Counterattack",
		group:         "Pattern Recognition",
		candlestick:   true,
		inputs:        []string{"open", "high", "low", "close"},
		outputs: []output{
			{name: "cdlcounterattack", style: indicator.OutputLine},
		},
		lookback: func(p []float64) int { return ta.CdlcounterattackLookback() },
		call: func(in [][]float64, p []float64) [][]float64 {
			o0 := ta.Cdlcounterattack(in[0], in[1], in[2], in[3], nil)
			return [][]float64{integers(o0)}
		},
	},
	{
		name:          "CDLDARKCLOUDCOVER",
		indicatorType: "cdldarkcloudcover",
		title:         "Dark Cloud Cover",
		group:         "Pattern Recognition",
		candlestick:   true,
		inputs:        []string{"open", "high", "low", "close"},
		params: []param{
			{key: "penetration", title: "Penetration", description: "Percentage of penetration of a candle within another candle", kind: paramReal, minimum: 0, maximum: 3e+37, defaultValue: 0.5},
		},
		outputs: []output{
			{name: "cdldarkcloudcover", style: indicator.OutputLine},
		},
		lookback: func(p []float64) int { return ta.CdldarkcloudcoverLookback(p[0]) },
		call: func(in [][]float64, p []float64) [][]float64 {
			o0 := ta.Cdldarkcloudcover(in[0], in[1], in[2], in[3], p[0], nil)
			return [][]float64{integers(o0)}
		},
	},
	{
		name:          "CDLDOJI",
		indicatorType: "cdldoji",
		title:         "Doji",
		group:         "Pattern Recognition",
		candlestick:   true,
		inputs:        []string{"open", "high", "low", "close"},
		outputs: []output{
			{name: "cdldoji", style: indicator.OutputLine},
		},
		lookback: func(p []float64) int { return ta.CdldojiLookback() },
		call: func(in [][]float64, p []float64) [][]float64 {
			o0 := ta.Cdldoji(in[0], in[1], in[2], in[3], nil)
			return [][]float64{integers(o0)}
		},
	},
	{
		name:          "CDLDOJISTAR",
		indicatorType: "cdldojistar",
		title:         "Doji Star",
		group:         "Pattern Recognition",
		candlestick:   true,
		inputs:        []string{"open", "high", "low", "close"},
		outputs: []output{
			{name: "cdldojistar", style: indicator.OutputLine},
		},
		lookback: func(p []float64) int { return ta.CdldojistarLookback() },
		call: func(in [][]float64, p []float64) [][]float64 {
			o0 := ta.Cdldojistar(in[0], in[1], in[2], in[3], nil)
			return [][]float64{integers(o0)}
		},
	},
	{
		name:          "CDLDRAGONFLYDOJI",
		indicatorType: "cdldragonflydoji",
		title:         "Dragonfly Doji",
		group:         "Pattern Recognition",
		candlestick:   true,
		inputs:        []string{"open", "high", "low", "close"},
		outputs: []output{
			{name: "cdldragonflydoji", style: indicator.OutputLine},
		},
		lookback: func(p []float64) int { return ta.CdldragonflydojiLookback() },
		call: func(in [][]float64, p []float64) [][]float64 {
			o0 := ta.Cdldragonflydoji(in[0], in[1], in[2], in[3], nil)
			return [][]float64{integers(o0)}
		},
	},
	{
		name:          "CDLENGULFING",
		indicatorType: "cdlengulfing",
		title:         "Engulfing Pattern",
		group:         "Pattern Recognition",
		candlestick:   true,
		inputs:        []string{"open", "high", "low", "close"},
		outputs: []output{
			{name: "cdlengulfing", style: indicator.OutputLine},
		},
		lookback: func(p []float64) int { return ta.CdlengulfingLookback() },
		call: func(in [][]float64, p []float64) [][]float64 {
			o0 := ta.Cdlengulfing(in[0], in[1], in[2], in[3], nil)
			return [][]float64{integers(o0)}
		},
	},
	{
		name:          "CDLEVENINGDOJISTAR",
		indicatorType: "cdleveningdojistar",
		title:         "Evening Doji Star",
		group:         "Pattern Recognition",
		candlestick:   true,
		inputs:        []string{"open", "high", "low", "close"},
		params: []param{
			{key: "penetration", title: "Penetration", description: "Percentage of penetration of a candle within another candle", kind: paramReal, minimum: 0, maximum: 3e+37, defaultValue: 0.3},
		},
		outputs: []output{
			{name: "cdleveningdojistar", style: indicator.OutputLine},
		},
		lookback: func(p []float64) int { return ta.CdleveningdojistarLookback(p[0]) },
		call: func(in [][]float64, p []float64) [][]float64 {
			o0 := ta.Cdleveningdojistar(in[0], in[1], in[2], in[3], p[0], nil)
			return [][]float64{integers(o0)}
		},
	},
	{
		name:          "CDLEVENINGSTAR",
		indicatorType: "cdleveningstar",
		title:         "Evening Star",
		group:         "Pattern Recognition",
		candlestick:   true,
		inputs:        []string{"open", "high", "low", "close"},
		params: []param{
			{key: "penetration", title: "Penetration", description: "Percentage of penetration of a candle within another candle", kind: paramReal, minimum: 0, maximum: 3e+37, defaultValue: 0.3},
		},
		outputs: []output{
			{name: "cdleveningstar", style: indicator.OutputLine},
		},
		lookback: func(p []float64) int { return ta.CdleveningstarLookback(p[0]) },
		call: func(in [][]float64, p []float64) [][]float64 {
			o0 := ta.Cdleveningstar(in[0], in[1], in[2], in[3], p[0], nil)
			return [][]float64{integers(o0)}
		},
	},
	{
		name:          "CDLGAPSIDESIDEWHITE",
		indicatorType: "cdlgapsidesidewhite",
		title:         "Up/Down-gap side-by-side white lines",
		group:         "Pattern Recognition",
		candlestick:   true,
		inputs:        []string{"open", "high", "low", "close"},
		outputs: []output{
			{name: "cdlgapsidesidewhite", style: indicator.OutputLine},
		},
		lookback: func(p []float64) int { return ta.CdlgapsidesidewhiteLookback() },
		call: func(in [][]float64, p []float64) [][]float64 {
			o0 := ta.Cdlgapsidesidewhite(in[0], in[1], in[2], in[3], nil)
			return [][]float64{integers(o0)}
		},
	},
	{
		name:          "CDLGRAVESTONEDOJI",
		indicatorType: "cdlgravestonedoji",
		title:         "Gravestone Doji",
		group:         "Pattern Recognition",
		candlestick:   true,
		inputs:        []string{"open", "high", "low", "close"},
		outputs: []output{
			{name: "cdlgravestonedoji", style: indicator.OutputLine},
		},
		lookback: func(p []float64) int { return ta.CdlgravestonedojiLookback() },
		call: func(in [][]float64, p []float64) [][]float64 {
			o0 := ta.Cdlgravestonedoji(in[0], in[1], in[2], in[3], nil)
			return [][]float64{integers(o0)}
		},
	},
	{
		name:          "CDLHAMMER",
		indicatorType: "cdlhammer",
		title:         "Hammer",
		group:         "Pattern Recognition",
		candlestick:   true,
		inputs:        []string{"open", "high", "low", "close"},
		outputs: []output{
			{name: "cdlhammer", style: indicator.OutputLine},
		},
		lookback: func(p []float64) int { return ta.CdlhammerLookback() },
		call: func(in [][]float64, p []float64) [][]float64 {
			o0 := ta.Cdlhammer(in[0], in[1], in[2], in[3], nil)
			return [][]float64{integers(o0)}
		},
	},
	{
		name:          "CDLHANGINGMAN",
		indicatorType: "cdlhangingman",
		title:         "Hanging Man",
		group:         "Pattern Recognition",
		candlestick:   true,
		inputs:        []string{"open", "high", "low", "close"},
		outputs: []output{
			{name: "cdlhangingman", style: indicator.OutputLine},
		},
		lookback: func(p []float64) int { return ta.CdlhangingmanLookback() },
		call: func(in [][]float64, p []float64) [][]float64 {
			o0 := ta.Cdlhangingman(in[0], in[1], in[2], in[3], nil)
			return [][]float64{integers(o0)}
		},
	},
	{
		name:          "CDLHARAMI",
		indicatorType: "cdlharami",
		title:         "Harami Pattern",
		group:         "Pattern Recognition",
		candlestick:   true,
		inputs:        []string{"open", "high", "low", "close"},
		outputs: []output{
			{name: "cdlharami", style: indicator.OutputLine},
		},
		lookback: func(p []float64) int { return ta.CdlharamiLookback() },
		call: func(in [][]float64, p []float64) [][]float64 {
			o0 := ta.Cdlharami(in[0], in[1], in[2], in[3], nil)
			return [][]float64{integers(o0)}
		},
	},
	{
		name:          "CDLHARAMICROSS",
		indicatorType: "cdlharamicross",
		title:         "Harami Cross Pattern",
		group:         "Pattern Recognition",
		candlestick:   true,
		inputs:        []string{"open", "high", "low", "close"},
		outputs: []output{
			{name: "cdlharamicross", style: indicator.OutputLine},
		},
		lookback: func(p []float64) int { return ta.CdlharamicrossLookback() },
		call: func(in [][]float64, p []float64) [][]float64 {
			o0 := ta.Cdlharamicross(in[0], in[1], in[2], in[3], nil)
			return [][]float64{integers(o0)}
		},
	},
	{
		name:          "CDLHIGHWAVE",
		indicatorType: "cdlhighwave",
		title:         "High-Wave Candle",
		group:         "Pattern Recognition",
		candlestick:   true,
		inputs:        []string{"open", "high", "low", "close"},
		outputs: []output{
			{name: "cdlhighwave", style: indicator.OutputLine},
		},
		lookback: func(p []float64) int { return ta.CdlhighwaveLookback() },
		call: func(in [][]float64, p []float64) [][]float64 {
			o0 := ta.Cdlhighwave(in[0], in[1], in[2], in[3], nil)
			return [][]float64{integers(o0)}
		},
	},
	{
		name:          "CDLHIKKAKE",
		indicatorType: "cdlhikkake",
		title:         "Hikkake Pattern",
		group:         "Pattern Recognition",
		candlestick:   true,
		inputs:        []string{"open", "high", "low", "close"},
		outputs: []output{
			{name: "cdlhikkake", style: indicator.OutputLine},
		},
		lookback: func(p []float64) int { return ta.CdlhikkakeLookback() },
		call: func(in [][]float64, p []float64) [][]float64 {
			o0 := ta.Cdlhikkake(in[0], in[1], in[2], in[3], nil)
			return [][]float64{integers(o0)}
		},
	},
	{
		name:          "CDLHIKKAKEMOD",
		indicatorType: "cdlhikkakemod",
		title:         "Modified Hikkake Pattern",
		group:         "Pattern Recognition",
		candlestick:   true,
		inputs:        []string{"open", "high", "low", "close"},
		outputs: []output{
			{name: "cdlhikkakemod", style: indicator.OutputLine},
		},
		lookback: func(p []float64) int { return ta.CdlhikkakemodLookback() },
		call: func(in [][]float64, p []float64) [][]float64 {
			o0 := ta.Cdlhikkakemod(in[0], in[1], in[2], in[3], nil)
			return [][]float64{integers(o0)}
		},
	},
	{
		name:          "CDLHOMINGPIGEON",
		indicatorType: "cdlhomingpigeon",
		title:         "Homing Pigeon",
		group:         "Pattern Recognition",
		candlestick:   true,
		inputs:        []string{"open", "high", "low", "close"},
		outputs: []output{
			{name: "cdlhomingpigeon", style: indicator.OutputLine},
		},
		lookback: func(p []float64) int { return ta.CdlhomingpigeonLookback() },
		call: func(in [][]float64, p []float64) [][]float64 {
			o0 := ta.Cdlhomingpigeon(in[0], in[1], in[2], in[3], nil)
			return [][]float64{integers(o0)}
		},
	},
	{
		name:          "CDLIDENTICAL3CROWS",
		indicatorType: "cdlidentical3crows",
		title:         "Identical Three Crows",
		group:         "Pattern Recognition",
		candlestick:   true,
		inputs:        []string{"open", "high", "low", "close"},
		outputs: []output{
			{name: "cdlidentical3crows", style: indicator.OutputLine},
		},
		lookback: func(p []float64) int { return ta.Cdlidentical3crowsLookback() },
		call: func(in [][]float64, p []float64) [][]float64 {
			o0 := ta.Cdlidentical3crows(in[0], in[1], in[2], in[3], nil)
			return [][]float64{integers(o0)}
		},
	},
	{
		name:          "CDLINNECK",
		indicatorType: "cdlinneck",
		title:         "In-Neck Pattern",
		group:         "Pattern Recognition",
		candlestick:   true,
		inputs:        []string{"open", "high", "low", "close"},
		outputs: []output{
			{name: "cdlinneck", style: indicator.OutputLine},
		},
		lookback: func(p []float64) int { return ta.CdlinneckLookback() },
		call: func(in [][]float64, p []float64) [][]float64 {
			o0 := ta.Cdlinneck(in[0], in[1], in[2], in[3], nil)
			return [][]float64{integers(o0)}
		},
	},
	{
		name:          "CDLINVERTEDHAMMER",
		indicatorType: "cdlinvertedhammer",
		title:         "Inverted Hammer",
		group:         "Pattern Recognition",
		candlestick:   true,
		inputs:        []string{"open", "high", "low", "close"},
		outputs: []output{
			{name: "cdlinvertedhammer", style: indicator.OutputLine},
		},
		lookback: func(p []float64) int { return ta.CdlinvertedhammerLookback() },
		call: func(in [][]float64, p []float64) [][]float64 {
			o0 := ta.Cdlinvertedhammer(in[0], in[1], in[2], in[3], nil)
			return [][]float64{integers(o0)}
		},
	},
	{
		name:          "CDLKICKING",
		indicatorType: "cdlkicking",
		title:         "Kicking",
		group:         "Pattern Recognition",
		candlestick:   true,
		inputs:        []string{"open", "high", "low", "close"},
		outputs: []output{
			{name: "cdlkicking", style: indicator.OutputLine},
		},
		lookback: func(p []float64) int { return ta.CdlkickingLookback() },
		call: func(in [][]float64, p []float64) [][]float64 {
			o0 := ta.Cdlkicking(in[0], in[1], in[2], in[3], nil)
			return [][]float64{integers(o0)}
		},
	},
	{
		name:          "CDLKICKINGBYLENGTH",
		indicatorType: "cdlkickingbylength",
		title:         "Kicking - bull/bear determined by the longer marubozu",
		group:         "Pattern Recognition",
		candlestick:   true,
		inputs:        []string{"open", "high", "low", "close"},
		outputs: []output{
			{name: "cdlkickingbylength", style: indicator.OutputLine},
		},
		lookback: func(p []float64) int { return ta.CdlkickingbylengthLookback() },
		call: func(in [][]float64, p []float64) [][]float64 {
			o0 := ta.Cdlkickingbylength(in[0], in[1], in[2], in[3], nil)
			return [][]float64{integers(o0)}
		},
	},
	{
		name:          "CDLLADDERBOTTOM",
		indicatorType: "cdlladderbottom",
		title:         "Ladder Bottom",
		group:         "Pattern Recognition",
		candlestick:   true,
		inputs:        []string{"open", "high", "low", "close"},
		outputs: []output{
			{name: "cdlladderbottom", style: indicator.OutputLine},
		},
		lookback: func(p []float64) int { return ta.CdlladderbottomLookback() },
		call: func(in [][]float64, p []float64) [][]float64 {
			o0 := ta.Cdlladderbottom(in[0], in[1], in[2], in[3], nil)
			return [][]float64{integers(o0)}
		},
	},
	{
		name:          "CDLLONGLEGGEDDOJI",
		indicatorType: "cdllongleggeddoji",
		title:         "Long Legged Doji",
		group:         "Pattern Recognition",
		candlestick:   true,
		inputs:        []string{"open", "high", "low", "close"},
		outputs: []output{
			{name: "cdllongleggeddoji", style: indicator.OutputLine},
		},
		lookback: func(p []float64) int { return ta.CdllongleggeddojiLookback() },
		call: func(in [][]float64, p []float64) [][]float64 {
			o0 := ta.Cdllongleggeddoji(in[0], in[1], in[2], in[3], nil)
			return [][]float64{integers(o0)}
		},
	},
	{
		name:          "CDLLONGLINE",
		indicatorType: "cdllongline",
		title:         "Long Line Candle",
		group:         "Pattern Recognition",
		candlestick:   true,
		inputs:        []string{"open", "high", "low", "close"},
		outputs: []output{
			{name: "cdllongline", style: indicator.OutputLine},
		},
		lookback: func(p []float64) int { return ta.CdllonglineLookback() },
		call: func(in [][]float64, p []float64) [][]float64 {
			o0 := ta.Cdllongline(in[0], in[1], in[2], in[3], nil)
			return [][]float64{integers(o0)}
		},
	},
	{
		name:          "CDLMARUBOZU",
		indicatorType: "cdlmarubozu",
		title:         "Marubozu",
		group:         "Pattern Recognition",
		candlestick:   true,
		inputs:        []string{"open", "high", "low", "close"},
		outputs: []output{
			{name: "cdlmarubozu", style: indicator.OutputLine},
		},
		lookback: func(p []float64) int { return ta.CdlmarubozuLookback() },
		call: func(in [][]float64, p []float64) [][]float64 {
			o0 := ta.Cdlmarubozu(in[0], in[1], in[2], in[3], nil)
			return [][]float64{integers(o0)}
		},
	},
	{
		name:          "CDLMATCHINGLOW",
		indicatorType: "cdlmatchinglow",
		title:         "Matching Low",
		group:         "Pattern Recognition",
		candlestick:   true,
		inputs:        []string{"open", "high", "low", "close"},
		outputs: []output{
			{name: "cdlmatchinglow", style: indicator.OutputLine},
		},
		lookback: func(p []float64) int { return ta.CdlmatchinglowLookback() },
		call: func(in [][]float64, p []float64) [][]float64 {
			o0 := ta.Cdlmatchinglow(in[0], in[1], in[2], in[3], nil)
			return [][]float64{integers(o0)}
		},
	},
	{
		name:          "CDLMATHOLD",
		indicatorType: "cdlmathold",
		title:         "Mat Hold",
		group:         "Pattern Recognition",
		candlestick:   true,
		inputs:        []string{"open", "high", "low", "close"},
		params: []param{
			{key: "penetration", title: "Penetration", description: "Percentage of penetration of a candle within another candle", kind: paramReal, minimum: 0, maximum: 3e+37, defaultValue: 0.5},
		},
		outputs: []output{
			{name: "cdlmathold", style: indicator.OutputLine},
		},
		lookback: func(p []float64) int { return ta.CdlmatholdLookback(p[0]) },
		call: func(in [][]float64, p []float64) [][]float64 {
			o0 := ta.Cdlmathold(in[0], in[1], in[2], in[3], p[0], nil)
			return [][]float64{integers(o0)}
		},
	},
	{
		name:          "CDLMORNINGDOJISTAR",
		indicatorType: "cdlmorningdojistar",
		title:         "Morning Doji Star",
		group:         "Pattern Recognition",
		candlestick:   true,
		inputs:        []string{"open", "high", "low", "close"},
		params: []param{
			{key: "penetration", title: "Penetration", description: "Percentage of penetration of a candle within another candle", kind: paramReal, minimum: 0, maximum: 3e+37, defaultValue: 0.3},
		},
		outputs: []output{
			{name: "cdlmorningdojistar", style: indicator.OutputLine},
		},
		lookback: func(p []float64) int { return ta.CdlmorningdojistarLookback(p[0]) },
		call: func(in [][]float64, p []float64) [][]float64 {
			o0 := ta.Cdlmorningdojistar(in[0], in[1], in[2], in[3], p[0], nil)
			return [][]float64{integers(o0)}
		},
	},
	{
		name:          "CDLMORNINGSTAR",
		indicatorType: "cdlmorningstar",
		title:         "Morning Star",
		group:         "Pattern Recognition",
		candlestick:   true,
		inputs:        []string{"open", "high", "low", "close"},
		params: []param{
			{key: "penetration", title: "Penetration", description: "Percentage of penetration of a candle within another candle", kind: paramReal, minimum: 0, maximum: 3e+37, defaultValue: 0.3},
		},
		outputs: []output{
			{name: "cdlmorningstar", style: indicator.OutputLine},
		},
		lookback: func(p []float64) int { return ta.CdlmorningstarLookback(p[0]) },
		call: func(in [][]float64, p []float64) [][]float64 {
			o0 := ta.Cdlmorningstar(in[0], in[1], in[2], in[3], p[0], nil)
			return [][]float64{integers(o0)}
		},
	},
	{
		name:          "CDLONNECK",
		indicatorType: "cdlonneck",
		title:         "On-Neck Pattern",
		group:         "Pattern Recognition",
		candlestick:   true,
		inputs:        []string{"open", "high", "low", "close"},
		outputs: []output{
			{name: "cdlonneck", style: indicator.OutputLine},
		},
		lookback: func(p []float64) int { return ta.CdlonneckLookback() },
		call: func(in [][]float64, p []float64) [][]float64 {
			o0 := ta.Cdlonneck(in[0], in[1], in[2], in[3], nil)
			return [][]float64{integers(o0)}
		},
	},
	{
		name:          "CDLPIERCING",
		indicatorType: "cdlpiercing",
		title:         "Piercing Pattern",
		group:         "Pattern Recognition",
		candlestick:   true,
		inputs:        []string{"open", "high", "low", "close"},
		outputs: []output{
			{name: "cdlpiercing", style: indicator.OutputLine},
		},
		lookback: func(p []float64) int { return ta.CdlpiercingLookback() },
		call: func(in [][]float64, p []float64) [][]float64 {
			o0 := ta.Cdlpiercing(in[0], in[1], in[2], in[3], nil)
			return [][]float64{integers(o0)}
		},
	},
	{
		name:          "CDLRICKSHAWMAN",
		indicatorType: "cdlrickshawman",
		title:         "Rickshaw Man",
		group:         "Pattern Recognition",
		candlestick:   true,
		inputs:        []string{"open", "high", "low", "close"},
		outputs: []output{
			{name: "cdlrickshawman", style: indicator.OutputLine},
		},
		lookback: func(p []float64) int { return ta.CdlrickshawmanLookback() },
		call: func(in [][]float64, p []float64) [][]float64 {
			o0 := ta.Cdlrickshawman(in[0], in[1], in[2], in[3], nil)
			return [][]float64{integers(o0)}
		},
	},
	{
		name:          "CDLRISEFALL3METHODS",
		indicatorType: "cdlrisefall3methods",
		title:         "Rising/Falling Three Methods",
		group:         "Pattern Recognition",
		candlestick:   true,
		inputs:        []string{"open", "high", "low", "close"},
		outputs: []output{
			{name: "cdlrisefall3methods", style: indicator.OutputLine},
		},
		lookback: func(p []float64) int { return ta.Cdlrisefall3methodsLookback() },
		call: func(in [][]float64, p []float64) [][]float64 {
			o0 := ta.Cdlrisefall3methods(in[0], in[1], in[2], in[3], nil)
			return [][]float64{integers(o0)}
		},
	},
	{
		name:          "CDLSEPARATINGLINES",
		indicatorType: "cdlseparatinglines",
		title:         "Separating Lines",
		group:         "Pattern Recognition",
		candlestick:   true,
		inputs:        []string{"open", "high", "low", "close"},
		outputs: []output{
			{name: "cdlseparatinglines", style: indicator.OutputLine},
		},
		lookback: func(p []float64) int { return ta.CdlseparatinglinesLookback() },
		call: func(in [][]float64, p []float64) [][]float64 {
			o0 := ta.Cdlseparatinglines(in[0], in[1], in[2], in[3], nil)
			return [][]float64{integers(o0)}
		},
	},
	{
		name:          "CDLSHOOTINGSTAR",
		indicatorType: "cdlshootingstar",
		title:         "Shooting Star",
		group:         "Pattern Recognition",
		candlestick:   true,
		inputs:        []string{"open", "high", "low", "close"},
		outputs: []output{
			{name: "cdlshootingstar", style: indicator.OutputLine},
		},
		lookback: func(p []float64) int { return ta.CdlshootingstarLookback() },
		call: func(in [][]float64, p []float64) [][]float64 {
			o0 := ta.Cdlshootingstar(in[0], in[1], in[2], in[3], nil)
			return [][]float64{integers(o0)}
		},
	},
	{
		name:          "CDLSHORTLINE",
		indicatorType: "cdlshortline",
		title:         "Short Line Candle",
		group:         "Pattern Recognition",
		candlestick:   true,
		inputs:        []string{"open", "high", "low", "close"},
		outputs: []output{
			{name: "cdlshortline", style: indicator.OutputLine},
		},
		lookback: func(p []float64) int { return ta.CdlshortlineLookback() },
		call: func(in [][]float64, p []float64) [][]float64 {
			o0 := ta.Cdlshortline(in[0], in[1], in[2], in[3], nil)
			return [][]float64{integers(o0)}
		},
	},
	{
		name:          "CDLSPINNINGTOP",
		indicatorType: "cdlspinningtop",
		title:         "Spinning Top",
		group:         "Pattern Recognition",
		candlestick:   true,
		inputs:        []string{"open", "high", "low", "close"},
		outputs: []output{
			{name: "cdlspinningtop", style: indicator.OutputLine},
		},
		lookback: func(p []float64) int { return ta.CdlspinningtopLookback() },
		call: func(in [][]float64, p []float64) [][]float64 {
			o0 := ta.Cdlspinningtop(in[0], in[1], in[2], in[3], nil)
			return [][]float64{integers(o0)}
		},
	},
	{
		name:          "CDLSTALLEDPATTERN",
		indicatorType: "cdlstalledpattern",
		title:         "Stalled Pattern",
		group:         "Pattern Recognition",
		candlestick:   true,
		inputs:        []string{"open", "high", "low", "close"},
		outputs: []output{
			{name: "cdlstalledpattern", style: indicator.OutputLine},
		},
		lookback: func(p []float64) int { return ta.CdlstalledpatternLookback() },
		call: func(in [][]float64, p []float64) [][]float64 {
			o0 := ta.Cdlstalledpattern(in[0], in[1], in[2], in[3], nil)
			return [][]float64{integers(o0)}
		},
	},
	{
		name:          "CDLSTICKSANDWICH",
		indicatorType: "cdlsticksandwich",
		title:         "Stick Sandwich",
		group:         "Pattern Recognition",
		candlestick:   true,
		inputs:        []string{"open", "high", "low", "close"},
		outputs: []output{
			{name: "cdlsticksandwich", style: indicator.OutputLine},
		},
		lookback: func(p []float64) int { return ta.CdlsticksandwichLookback() },
		call: func(in [][]float64, p []float64) [][]float64 {
			o0 := ta.Cdlsticksandwich(in[0], in[1], in[2], in[3], nil)
			return [][]float64{integers(o0)}
		},
	},
	{
		name:          "CDLTAKURI",
		indicatorType: "cdltakuri",
		title:         "Takuri (Dragonfly Doji with very long lower shadow)",
		group:         "Pattern Recognition",
		candlestick:   true,
		inputs:        []string{"open", "high", "low", "close"},
		outputs: []output{
			{name: "cdltakuri", style: indicator.OutputLine},
		},
		lookback: func(p []float64) int { return ta.CdltakuriLookback() },
		call: func(in [][]float64, p []float64) [][]float64 {
			o0 := ta.Cdltakuri(in[0], in[1], in[2], in[3], nil)
			return [][]float64{integers(o0)}
		},
	},
	{
		name:          "CDLTASUKIGAP",
		indicatorType: "cdltasukigap",
		title:         "Tasuki Gap",
		group:         "Pattern Recognition",
		candlestick:   true,
		inputs:        []string{"open", "high", "low", "close"},
		outputs: []output{
			{name: "cdltasukigap", style: indicator.OutputLine},
		},
		lookback: func(p []float64) int { return ta.CdltasukigapLookback() },
		call: func(in [][]float64, p []float64) [][]float64 {
			o0 := ta.Cdltasukigap(in[0], in[1], in[2], in[3], nil)
			return [][]float64{integers(o0)}
		},
	},
	{
		name:          "CDLTHRUSTING",
		indicatorType: "cdlthrusting",
		title:         "Thrusting Pattern",
		group:         "Pattern Recognition",
		candlestick:   true,
		inputs:        []string{"open", "high", "low", "close"},
		outputs: []output{
			{name: "cdlthrusting", style: indicator.OutputLine},
		},
		lookback: func(p []float64) int { return ta.CdlthrustingLookback() },
		call: func(in [][]float64, p []float64) [][]float64 {
			o0 := ta.Cdlthrusting(in[0], in[1], in[2], in[3], nil)
			return [][]float64{integers(o0)}
		},
	},
	{
		name:          "CDLTRISTAR",
		indicatorType: "cdltristar",
		title:         "Tristar Pattern",
		group:         "Pattern Recognition",
		candlestick:   true,
		inputs:        []string{"open", "high", "low", "close"},
		outputs: []output{
			{name: "cdltristar", style: indicator.OutputLine},
		},
		lookback: func(p []float64) int { return ta.CdltristarLookback() },
		call: func(in [][]float64, p []float64) [][]float64 {
			o0 := ta.Cdltristar(in[0], in[1], in[2], in[3], nil)
			return [][]float64{integers(o0)}
		},
	},
	{
		name:          "CDLUNIQUE3RIVER",
		indicatorType: "cdlunique3river",
		title:         "Unique 3 River",
		group:         "Pattern Recognition",
		candlestick:   true,
		inputs:        []string{"open", "high", "low", "close"},
		outputs: []output{
			{name: "cdlunique3river", style: indicator.OutputLine},
		},
		lookback: func(p []float64) int { return ta.Cdlunique3riverLookback() },
		call: func(in [][]float64, p []float64) [][]float64 {
			o0 := ta.Cdlunique3river(in[0], in[1], in[2], in[3], nil)
			return [][]float64{integers(o0)}
		},
	},
	{
		name:          "CDLUPSIDEGAP2CROWS",
		indicatorType: "cdlupsidegap2crows",
		title:         "Upside Gap Two Crows",
		group:         "Pattern Recognition",
		candlestick:   true,
		inputs:        []string{"open", "high", "low", "close"},
		outputs: []output{
			{name: "cdlupsidegap2crows", style: indicator.OutputLine},
		},
		lookback: func(p []float64) int { return ta.Cdlupsidegap2crowsLookback() },
		call: func(in [][]float64, p []float64) [][]float64 {
			o0 := ta.Cdlupsidegap2crows(in[0], in[1], in[2], in[3], nil)
			return [][]float64{integers(o0)}
		},
	},
	{
		name:          "CDLXSIDEGAP3METHODS",
		indicatorType: "cdlxsidegap3methods",
		title:         "Upside/Downside Gap Three Methods",
		group:         "Pattern Recognition",
		candlestick:   true,
		inputs:        []string{"open", "high", "low", "close"},
		outputs: []output{
			{name: "cdlxsidegap3methods", style: indicator.OutputLine},
		},
		lookback: func(p []float64) int { return ta.Cdlxsidegap3methodsLookback() },
		call: func(in [][]float64, p []float64) [][]float64 {
			o0 := ta.Cdlxsidegap3methods(in[0], in[1], in[2], in[3], nil)
			return [][]float64{integers(o0)}
		},
	},
	{
		name:          "CMO",
		indicatorType: "cmo",
		title:         "Chande Momentum Oscillator",
		group:         "Momentum Indicators",
		unstable:      true,
		inputs:        []string{"close"},
		params: []param{
			{key: "period", title: "Time Period", description: "Number of period", kind: paramInteger, minimum: 2, maximum: 100000, defaultValue: 14},
		},
		outputs: []output{
			{name: "cmo", style: indicator.OutputLine},
		},
		lookback: func(p []float64) int { return ta.CmoLookback(int(p[0])) },
		call: func(in [][]float64, p []float64) [][]float64 {
			o0 := ta.Cmo(in[0], int(p[0]), nil)
			return [][]float64{o0}
		},
	},
	{
		name:          "DEMA",
		indicatorType: "dema",
		title:         "Double Exponential Moving Average",
		group:         "Overlap Studies",
		overlap:       true,
		inputs:        []string{"close"},
		params: []param{
			{key: "period", title: "Time Period", description: "Number of period", kind: paramInteger, minimum: 2, maximum: 100000, defaultValue: 30},
		},
		outputs: []output{
			{name: "dema", style: indicator.OutputLine},
		},
		lookback: func(p []float64) int { return ta.DemaLookback(int(p[0])) },
		call: func(in [][]float64, p []float64) [][]float64 {
			o0 := ta.Dema(in[0], int(p[0]), nil)
			return [][]float64{o0}
		},
	},
	{
		name:          "DX",
		indicatorType: "dx",
		title:         "Directional Movement Index",
		group:         "Momentum Indicators",
		unstable:      true,
		inputs:        []string{"high", "low", "close"},
		params: []param{
			{key: "period", title: "Time Period", description: "Number of period", kind: paramInteger, minimum: 2, maximum: 100000, defaultValue: 14},
		},
		outputs: []output{
			{name: "dx", style: indicator.OutputLine},
		},
		lookback: func(p []float64) int { return ta.DxLookback(int(p[0])) },
		call: func(in [][]float64, p []float64) [][]float64 {
			o0 := ta.Dx(in[0], in[1], in[2], int(p[0]), nil)
			return [][]float64{o0}
		},
	},
	{
		name:          "EMA",
		indicatorType: "ema",
		title:         "Exponential Moving Average",
		group:         "Overlap Studies",
		overlap:       true,
		unstable:      true,
		inputs:        []string{"close"},
		params: []param{
			{key: "period", title: "Time Period", description: "Number of period", kind: paramInteger, minimum: 2, maximum: 100000, defaultValue: 30},
		},
		outputs: []output{
			{name: "ema", style: indicator.OutputLine},
		},
		lookback: func(p []float64) int { return ta.EmaLookback(int(p[0])) },
		call: func(in [][]float64, p []float64) [][]float64 {
			o0 := ta.Ema(in[0], int(p[0]), nil)
			return [][]float64{o0}
		},
	},
	{
		name:          "HT_DCPERIOD",
		indicatorType: "ht_dcperiod",
		title:         "Hilbert Transform - Dominant Cycle Period",
		group:         "Cycle Indicators",
		unstable:      true,
		inputs:        []string{"close"},
		outputs: []output{
			{name: "ht_dcperiod", style: indicator.OutputLine},
		},
		lookback: func(p []float64) int { return ta.HtDcperiodLookback() },
		call: func(in [][]float64, p []float64) [][]float64 {
			o0 := ta.HtDcperiod(in[0], nil)
			return [][]float64{o0}
		},
	},
	{
		name:          "HT_DCPHASE",
		indicatorType: "ht_dcphase",
		title:         "Hilbert Transform - Dominant Cycle Phase",
		group:         "Cycle Indicators",
		unstable:      true,
		inputs:        []string{"close"},
		outputs: []output{
			{name: "ht_dcphase", style: indicator.OutputLine},
		},
		lookback: func(p []float64) int { return ta.HtDcphaseLookback() },
		call: func(in [][]float64, p []float64) [][]float64 {
			o0 := ta.HtDcphase(in[0], nil)
			return [][]float64{o0}
		},
	},
	{
		name:          "HT_PHASOR",
		indicatorType: "ht_phasor",
		title:         "Hilbert Transform - Phasor Components",
		group:         "Cycle Indicators",
		unstable:      true,
		inputs:        []string{"close"},
		outputs: []output{
			{name: "inphase", style: indicator.OutputLine},
			{name: "quadrature", style: indicator.OutputDashedLine},
		},
		lookback: func(p []float64) int { return ta.HtPhasorLookback() },
		call: func(in [][]float64, p []float64) [][]float64 {
			o0, o1 := ta.HtPhasor(in[0], nil, nil)
			return [][]float64{o0, o1}
		},
	},
	{
		name:          "HT_SINE",
		indicatorType: "ht_sine",
		title:         "Hilbert Transform - SineWave",
		group:         "Cycle Indicators",
		unstable:      true,
		inputs:        []string{"close"},
		outputs: []output{
			{name: "sine", style: indicator.OutputLine},
			{name: "leadsine", style: indicator.OutputDashedLine},
		},
		lookback: func(p []float64) int { return ta.HtSineLookback() },
		call: func(in [][]float64, p []float64) [][]float64 {
			o0, o1 := ta.HtSine(in[0], nil, nil)
			return [][]float64{o0, o1}
		},
	},
	{
		name:          "HT_TRENDLINE",
		indicatorType: "ht_trendline",
		title:         "Hilbert Transform - Instantaneous Trendline",
		group:         "Overlap Studies",
		overlap:       true,
		unstable:      true,
		inputs:        []string{"close"},
		outputs: []output{
			{name: "ht_trendline", style: indicator.OutputLine},
		},
		lookback: func(p []float64) int { return ta.HtTrendlineLookback() },
		call: func(in [][]float64, p []float64) [][]float64 {
			o0 := ta.HtTrendline(in[0], nil)
			return [][]float64{o0}
		},
	},
	{
		name:          "HT_TRENDMODE",
		indicatorType: "ht_trendmode",
		title:         "Hilbert Transform - Trend vs Cycle Mode",
		group:         "Cycle Indicators",
		unstable:      true,
		inputs:        []string{"close"},
		outputs: []output{
			{name: "ht_trendmode", style: indicator.OutputLine},
		},
		lookback: func(p []float64) int { return ta.HtTrendmodeLookback() },
		call: func(in [][]float64, p []float64) [][]float64 {
			o0 := ta.HtTrendmode(in[0], nil)
			return [][]float64{integers(o0)}
		},
	},
	{
		name:          "KAMA",
		indicatorType: "kama",
		title:         "Kaufman Adaptive Moving Average",
		group:         "Overlap Studies",
		overlap:       true,
		unstable:      true,
		inputs:        []string{"close"},
		params: []param{
			{key: "period", title: "Time Period", description: "Number of period", kind: paramInteger, minimum: 2, maximum: 100000, defaultValue: 30},
		},
		outputs: []output{
			{name: "kama", style: indicator.OutputLine},
		},
		lookback: func(p []float64) int { return ta.KamaLookback(int(p[0])) },
		call: func(in [][]float64, p []float64) [][]float64 {
			o0 := ta.Kama(in[0], int(p[0]), nil)
			return [][]float64{o0}
		},
	},
	{
		name:          "LINEARREG",
		indicatorType: "linearreg",
		title:         "Linear Regression",
		group:         "Statistic Functions",
		overlap:       true,
		inputs:        []string{"close"},
		params: []param{
			{key: "period", title: "Time Period", description: "Number of period", kind: paramInteger, minimum: 2, maximum: 100000, defaultValue: 14},
		},
		outputs: []output{
			{name: "linearreg", style: indicator.OutputLine},
		},
		lookback: func(p []float64) int { return ta.LinearregLookback(int(p[0])) },
		call: func(in [][]float64, p []float64) [][]float64 {
			o0 := ta.Linearreg(in[0], int(p[0]), nil)
			return [][]float64{o0}
		},
	},
	{
		name:          "LINEARREG_ANGLE",
		indicatorType: "linearreg_angle",
		title:         "Linear Regression Angle",
		group:         "Statistic Functions",
		inputs:        []string{"close"},
		params: []param{
			{key: "period", title: "Time Period", description: "Number of period", kind: paramInteger, minimum: 2, maximum: 100000, defaultValue: 14},
		},
		outputs: []output{
			{name: "linearreg_angle", style: indicator.OutputLine},
		},
		lookback: func(p []float64) int { return ta.LinearregAngleLookback(int(p[0])) },
		call: func(in [][]float64, p []float64) [][]float64 {
			o0 := ta.LinearregAngle(in[0], int(p[0]), nil)
			return [][]float64{o0}
		},
	},
	{
		name:          "LINEARREG_INTERCEPT",
		indicatorType: "linearreg_intercept",
		title:         "Linear Regression Intercept",
		group:         "Statistic Functions",
		overlap:       true,
		inputs:        []string{"close"},
		params: []param{
			{key: "period", title: "Time Period", description: "Number of period", kind: paramInteger, minimum: 2, maximum: 100000, defaultValue: 14},
		},
		outputs: []output{
			{name: "linearreg_intercept", style: indicator.OutputLine},
		},
		lookback: func(p []float64) int { return ta.LinearregInterceptLookback(int(p[0])) },
		call: func(in [][]float64, p []float64) [][]float64 {
			o0 := ta.LinearregIntercept(in[0], int(p[0]), nil)
			return [][]float64{o0}
		},
	},
	{
		name:          "LINEARREG_SLOPE",
		indicatorType: "linearreg_slope",
		title:         "Linear Regression Slope",
		group:         "Statistic Functions",
		inputs:        []string{"close"},
		params: []param{
			{key: "period", title: "Time Period", description: "Number of period", kind: paramInteger, minimum: 2, maximum: 100000, defaultValue: 14},
		},
		outputs: []output{
			{name: "linearreg_slope", style: indicator.OutputLine},
		},
		lookback: func(p []float64) int { return ta.LinearregSlopeLookback(int(p[0])) },
		call: func(in [][]float64, p []float64) [][]float64 {
			o0 := ta.LinearregSlope(in[0], int(p[0]), nil)
			return [][]float64{o0}
		},
	},
	{
		name:          "MA",
		indicatorType: "ma",
		title:         "Moving average",
		group:         "Overlap Studies",
		overlap:       true,
		inputs:        []string{"close"},
		params: []param{
			{key: "period", title: "Time Period", description: "Number of period", kind: paramInteger, minimum: 1, maximum: 100000, defaultValue: 30},
			{key: "ma_type", title: "MA Type", description: "Type of Moving Average", kind: paramMAType, defaultValue: 0},
		},
		outputs: []output{
			{name: "ma", style: indicator.OutputLine},
		},
		lookback: func(p []float64) int { return ta.MaLookback(int(p[0]), int(p[1])) },
		call: func(in [][]float64, p []float64) [][]float64 {
			o0 := ta.Ma(in[0], int(p[0]), int(p[1]), nil)
			return [][]float64{o0}
		},
	},
	{
		name:          "MACD",
		indicatorType: "macd",
		title:         "Moving Average Convergence/Divergence",
		group:         "Momentum Indicators",
		inputs:        []string{"close"},
		params: []param{
			{key: "fast_period", title: "Fast Period", description: "Number of period for the fast MA", kind: paramInteger, minimum: 2, maximum: 100000, defaultValue: 12},
			{key: "slow_period", title: "Slow Period", description: "Number of period for the slow MA", kind: paramInteger, minimum: 2, maximum: 100000, defaultValue: 26},
			{key: "signal_period", title: "Signal Period", description: "Smoothing for the signal line (nb of period)", kind: paramInteger, minimum: 1, maximum: 100000, defaultValue: 9},
		},
		outputs: []output{
			{name: "macd", style: indicator.OutputLine},
			{name: "macdsignal", style: indicator.OutputDashedLine},
			{name: "macdhist", style: indicator.OutputHistogram},
		},
		lookback: func(p []float64) int { return ta.MacdLookback(int(p[0]), int(p[1]), int(p[2])) },
		call: func(in [][]float64, p []float64) [][]float64 {
			o0, o1, o2 := ta.Macd(in[0], int(p[0]), int(p[1]), int(p[2]), nil, nil, nil)
			return [][]float64{o0, o1, o2}
		},
	},
	{
		name:          "MACDEXT",
		indicatorType: "macdext",
		title:         "MACD with controllable MA type",
		group:         "Momentum Indicators",
		inputs:        []string{"close"},
		params: []param{
			{key: "fast_period", title: "Fast Period", description: "Number of period for the fast MA", kind: paramInteger, minimum: 2, maximum: 100000, defaultValue: 12},
			{key: "fast_ma", title: "Fast MA", description: "Type of Moving Average for fast MA", kind: paramMAType, defaultValue: 0},
			{key: "slow_period", title: "Slow Period", description: "Number of period for the slow MA", kind: paramInteger, minimum: 2, maximum: 100000, defaultValue: 26},
			{key: "slow_ma", title: "Slow MA", description: "Type of Moving Average for slow MA", kind: paramMAType, defaultValue: 0},
			{key: "signal_period", title: "Signal Period", description: "Smoothing for the signal line (nb of period)", kind: paramInteger, minimum: 1, maximum: 100000, defaultValue: 9},
			{key: "signal_ma", title: "Signal MA", description: "Type of Moving Average for signal line", kind: paramMAType, defaultValue: 0},
		},
		outputs: []output{
			{name: "macd", style: indicator.OutputLine},
			{name: "macdsignal", style: indicator.OutputDashedLine},
			{name: "macdhist", style: indicator.OutputHistogram},
		},
		lookback: func(p []float64) int {
			return ta.MacdextLookback(int(p[0]), int(p[1]), int(p[2]), int(p[3]), int(p[4]), int(p[5]))
		},
		call: func(in [][]float64, p []float64) [][]float64 {
			o0, o1, o2 := ta.Macdext(in[0], int(p[0]), int(p[1]), int(p[2]), int(p[3]), int(p[4]), int(p[5]), nil, nil, nil)
			return [][]float64{o0, o1, o2}
		},
	},
	{
		name:          "MACDFIX",
		indicatorType: "macdfix",
		title:         "Moving Average Convergence/Divergence Fix 12/26",
		group:         "Momentum Indicators",
		inputs:        []string{"close"},
		params: []param{
			{key: "signal_period", title: "Signal Period", description: "Smoothing for the signal line (nb of period)", kind: paramInteger, minimum: 1, maximum: 100000, defaultValue: 9},
		},
		outputs: []output{
			{name: "macd", style: indicator.OutputLine},
			{name: "macdsignal", style: indicator.OutputDashedLine},
			{name: "macdhist", style: indicator.OutputHistogram},
		},
		lookback: func(p []float64) int { return ta.MacdfixLookback(int(p[0])) },
		call: func(in [][]float64, p []float64) [][]float64 {
			o0, o1, o2 := ta.Macdfix(in[0], int(p[0]), nil, nil, nil)
			return [][]float64{o0, o1, o2}
		},
	},
	{
		name:          "MAMA",
		indicatorType: "mama",
		title:         "MESA Adaptive Moving Average",
		group:         "Overlap Studies",
		overlap:       true,
		unstable:      true,
		inputs:        []string{"close"},
		params: []param{
			{key: "fast_limit", title: "Fast Limit", description: "Upper limit use in the adaptive algorithm", kind: paramReal, minimum: 0.01, maximum: 0.99, defaultValue: 0.5},
			{key: "slow_limit", title: "Slow Limit", description: "Lower limit use in the adaptive algorithm", kind: paramReal, minimum: 0.01, maximum: 0.99, defaultValue: 0.05},
		},
		outputs: []output{
			{name: "mama", style: indicator.OutputLine},
			{name: "fama", style: indicator.OutputDashedLine},
		},
		lookback: func(p []float64) int { return ta.MamaLookback(p[0], p[1]) },
		call: func(in [][]float64, p []float64) [][]float64 {
			o0, o1 := ta.Mama(in[0], p[0], p[1], nil, nil)
			return [][]float64{o0, o1}
		},
	},
	{
		name:          "MAX",
		indicatorType: "max",
		title:         "Highest value over a specified period",
		group:         "Math Operators",
		overlap:       true,
		inputs:        []string{"close"},
		params: []param{
			{key: "period", title: "Time Period", description: "Number of period", kind: paramInteger, minimum: 2, maximum: 100000, defaultValue: 30},
		},
		outputs: []output{
			{name: "max", style: indicator.OutputLine},
		},
		lookback: func(p []float64) int { return ta.MaxLookback(int(p[0])) },
		call: func(in [][]float64, p []float64) [][]float64 {
			o0 := ta.Max(in[0], int(p[0]), nil)
			return [][]float64{o0}
		},
	},
	{
		name:          "MEDPRICE",
		indicatorType: "medprice",
		title:         "Median Price",
		group:         "Price Transform",
		overlap:       true,
		inputs:        []string{"high", "low"},
		outputs: []output{
			{name: "medprice", style: indicator.OutputLine},
		},
		lookback: func(p []float64) int { return ta.MedpriceLookback() },
		call: func(in [][]float64, p []float64) [][]float64 {
			o0 := ta.Medprice(in[0], in[1], nil)
			return [][]float64{o0}
		},
	},
	{
		name:          "MFI",
		indicatorType: "mfi",
		title:         "Money Flow Index",
		group:         "Momentum Indicators",
		unstable:      true,
		inputs:        []string{"high", "low", "close", "volume"},
		params: []param{
			{key: "period", title: "Time Period", description: "Number of period", kind: paramInteger, minimum: 2, maximum: 100000, defaultValue: 14},
		},
		outputs: []output{
			{name: "mfi", style: indicator.OutputLine},
		},
		lookback: func(p []float64) int { return ta.MfiLookback(int(p[0])) },
		call: func(in [][]float64, p []float64) [][]float64 {
			o0 := ta.Mfi(in[0], in[1], in[2], in[3], int(p[0]), nil)
			return [][]float64{o0}
		},
	},
	{
		name:          "MIDPOINT",
		indicatorType: "midpoint",
		title:         "MidPoint over period",
		group:         "Overlap Studies",
		overlap:       true,
		inputs:        []string{"close"},
		params: []param{
			{key: "period", title: "Time Period", description: "Number of period", kind: paramInteger, minimum: 2, maximum: 100000, defaultValue: 14},
		},
		outputs: []output{
			{name: "midpoint", style: indicator.OutputLine},
		},
		lookback: func(p []float64) int { return ta.MidpointLookback(int(p[0])) },
		call: func(in [][]float64, p []float64) [][]float64 {
			o0 := ta.Midpoint(in[0], int(p[0]), nil)
			return [][]float64{o0}
		},
	},
	{
		name:          "MIDPRICE",
		indicatorType: "midprice",
		title:         "Midpoint Price over period",
		group:         "Overlap Studies",
		overlap:       true,
		inputs:        []string{"high", "low"},
		params: []param{
			{key: "period", title: "Time Period", description: "Number of period", kind: paramInteger, minimum: 2, maximum: 100000, defaultValue: 14},
		},
		outputs: []output{
			{name: "midprice", style: indicator.OutputLine},
		},
		lookback: func(p []float64) int { return ta.MidpriceLookback(int(p[0])) },
		call: func(in [][]float64, p []float64) [][]float64 {
			o0 := ta.Midprice(in[0], in[1], int(p[0]), nil)
			return [][]float64{o0}
		},
	},
	{
		name:          "MIN",
		indicatorType: "min",
		title:         "Lowest value over a specified period",
		group:         "Math Operators",
		overlap:       true,
		inputs:        []string{"close"},
		params: []param{
			{key: "period", title: "Time Period", description: "Number of period", kind: paramInteger, minimum: 2, maximum: 100000, defaultValue: 30},
		},
		outputs: []output{
			{name: "min", style: indicator.OutputLine},
		},
		lookback: func(p []float64) int { return ta.MinLookback(int(p[0])) },
		call: func(in [][]float64, p []float64) [][]float64 {
			o0 := ta.Min(in[0], int(p[0]), nil)
			return [][]float64{o0}
		},
	},
	{
		name:          "MINMAX",
		indicatorType: "minmax",
		title:         "Lowest and highest values over a specified period",
		group:         "Math Operators",
		overlap:       true,
		inputs:        []string{"close"},
		params: []param{
			{key: "period", title: "Time Period", description: "Number of period", kind: paramInteger, minimum: 2, maximum: 100000, defaultValue: 30},
		},
		outputs: []output{
			{name: "min", style: indicator.OutputLine},
			{name: "max", style: indicator.OutputLine},
		},
		lookback: func(p []float64) int { return ta.MinmaxLookback(int(p[0])) },
		call: func(in [][]float64, p []float64) [][]float64 {
			o0, o1 := ta.Minmax(in[0], int(p[0]), nil, nil)
			return [][]float64{o0, o1}
		},
	},
	{
		name:          "MINUS_DI",
		indicatorType: "minus_di",
		title:         "Minus Directional Indicator",
		group:         "Momentum Indicators",
		unstable:      true,
		inputs:        []string{"high", "low", "close"},
		params: []param{
			{key: "period", title: "Time Period", description: "Number of period", kind: paramInteger, minimum: 1, maximum: 100000, defaultValue: 14},
		},
		outputs: []output{
			{name: "minus_di", style: indicator.OutputLine},
		},
		lookback: func(p []float64) int { return ta.MinusDiLookback(int(p[0])) },
		call: func(in [][]float64, p []float64) [][]float64 {
			o0 := ta.MinusDi(in[0], in[1], in[2], int(p[0]), nil)
			return [][]float64{o0}
		},
	},
	{
		name:          "MINUS_DM",
		indicatorType: "minus_dm",
		title:         "Minus Directional Movement",
		group:         "Momentum Indicators",
		unstable:      true,
		inputs:        []string{"high", "low"},
		params: []param{
			{key: "period", title: "Time Period", description: "Number of period", kind: paramInteger, minimum: 1, maximum: 100000, defaultValue: 14},
		},
		outputs: []output{
			{name: "minus_dm", style: indicator.OutputLine},
		},
		lookback: func(p []float64) int { return ta.MinusDmLookback(int(p[0])) },
		call: func(in [][]float64, p []float64) [][]float64 {
			o0 := ta.MinusDm(in[0], in[1], int(p[0]), nil)
			return [][]float64{o0}
		},
	},
	{
		name:          "MOM",
		indicatorType: "mom",
		title:         "Momentum",
		group:         "Momentum Indicators",
		inputs:        []string{"close"},
		params: []param{
			{key: "period", title: "Time Period", description: "Number of period", kind: paramInteger, minimum: 1, maximum: 100000, defaultValue: 10},
		},
		outputs: []output{
			{name: "mom", style: indicator.OutputLine},
		},
		lookback: func(p []float64) int { return ta.MomLookback(int(p[0])) },
		call: func(in [][]float64, p []float64) [][]float64 {
			o0 := ta.Mom(in[0], int(p[0]), nil)
			return [][]float64{o0}
		},
	},
	{
		name:          "NATR",
		indicatorType: "natr",
		title:         "Normalized Average True Range",
		group:         "Volatility Indicators",
		unstable:      true,
		inputs:        []string{"high", "low", "close"},
		params: []param{
			{key: "period", title: "Time Period", description: "Number of period", kind: paramInteger, minimum: 1, maximum: 100000, defaultValue: 14},
		},
		outputs: []output{
			{name: "natr", style: indicator.OutputLine},
		},
		lookback: func(p []float64) int { return ta.NatrLookback(int(p[0])) },
		call: func(in [][]float64, p []float64) [][]float64 {
			o0 := ta.Natr(in[0], in[1], in[2], int(p[0]), nil)
			return [][]float64{o0}
		},
	},
	{
		name:          "OBV",
		indicatorType: "obv",
		title:         "On Balance Volume",
		group:         "Volume Indicators",
		inputs:        []string{"close", "volume"},
		outputs: []output{
			{name: "obv", style: indicator.OutputLine},
		},
		lookback: func(p []float64) int { return ta.ObvLookback() },
		call: func(in [][]float64, p []float64) [][]float64 {
			o0 := ta.Obv(in[0], in[1], nil)
			return [][]float64{o0}
		},
	},
	{
		name:          "PLUS_DI",
		indicatorType: "plus_di",
		title:         "Plus Directional Indicator",
		group:         "Momentum Indicators",
		unstable:      true,
		inputs:        []string{"high", "low", "close"},
		params: []param{
			{key: "period", title: "Time Period", description: "Number of period", kind: paramInteger, minimum: 1, maximum: 100000, defaultValue: 14},
		},
		outputs: []output{
			{name: "plus_di", style: indicator.OutputLine},
		},
		lookback: func(p []float64) int { return ta.PlusDiLookback(int(p[0])) },
		call: func(in [][]float64, p []float64) [][]float64 {
			o0 := ta.PlusDi(in[0], in[1], in[2], int(p[0]), nil)
			return [][]float64{o0}
		},
	},
	{
		name:          "PLUS_DM",
		indicatorType: "plus_dm",
		title:         "Plus Directional Movement",
		group:         "Momentum Indicators",
		unstable:      true,
		inputs:        []string{"high", "low"},
		params: []param{
			{key: "period", title: "Time Period", description: "Number of period", kind: paramInteger, minimum: 1, maximum: 100000, defaultValue: 14},
		},
		outputs: []output{
			{name: "plus_dm", style: indicator.OutputLine},
		},
		lookback: func(p []float64) int { return ta.PlusDmLookback(int(p[0])) },
		call: func(in [][]float64, p []float64) [][]float64 {
			o0 := ta.PlusDm(in[0], in[1], int(p[0]), nil)
			return [][]float64{o0}
		},
	},
	{
		name:          "PPO",
		indicatorType: "ppo",
		title:         "Percentage Price Oscillator",
		group:         "Momentum Indicators",
		inputs:        []string{"close"},
		params: []param{
			{key: "fast_period", title: "Fast Period", description: "Number of period for the fast MA", kind: paramInteger, minimum: 2, maximum: 100000, defaultValue: 12},
			{key: "slow_period", title: "Slow Period", description: "Number of period for the slow MA", kind: paramInteger, minimum: 2, maximum: 100000, defaultValue: 26},
			{key: "ma_type", title: "MA Type", description: "Type of Moving Average", kind: paramMAType, defaultValue: 0},
		},
		outputs: []output{
			{name: "ppo", style: indicator.OutputLine},
		},
		lookback: func(p []float64) int { return ta.PpoLookback(int(p[0]), int(p[1]), int(p[2])) },
		call: func(in [][]float64, p []float64) [][]float64 {
			o0 := ta.Ppo(in[0], int(p[0]), int(p[1]), int(p[2]), nil)
			return [][]float64{o0}
		},
	},
	{
		name:          "ROC",
		indicatorType: "roc",
		title:         "Rate of change : ((price/prevPrice)-1)*100",
		group:         "Momentum Indicators",
		inputs:        []string{"close"},
		params: []param{
			{key: "period", title: "Time Period", description: "Number of period", kind: paramInteger, minimum: 1, maximum: 100000, defaultValue: 10},
		},
		outputs: []output{
			{name: "roc", style: indicator.OutputLine},
		},
		lookback: func(p []float64) int { return ta.RocLookback(int(p[0])) },
		call: func(in [][]float64, p []float64) [][]float64 {
			o0 := ta.Roc(in[0], int(p[0]), nil)
			return [][]float64{o0}
		},
	},
	{
		name:          "ROCP",
		indicatorType: "rocp",
		title:         "Rate of change Percentage: (price-prevPrice)/prevPrice",
		group:         "Momentum Indicators",
		inputs:        []string{"close"},
		params: []param{
			{key: "period", title: "Time Period", description: "Number of period", kind: paramInteger, minimum: 1, maximum: 100000, defaultValue: 10},
		},
		outputs: []output{
			{name: "rocp", style: indicator.OutputLine},
		},
		lookback: func(p []float64) int { return ta.RocpLookback(int(p[0])) },
		call: func(in [][]float64, p []float64) [][]float64 {
			o0 := ta.Rocp(in[0], int(p[0]), nil)
			return [][]float64{o0}
		},
	},
	{
		name:          "ROCR",
		indicatorType: "rocr",
		title:         "Rate of change ratio: (price/prevPrice)",
		group:         "Momentum Indicators",
		inputs:        []string{"close"},
		params: []param{
			{key: "period", title: "Time Period", description: "Number of period", kind: paramInteger, minimum: 1, maximum: 100000, defaultValue: 10},
		},
		outputs: []output{
			{name: "rocr", style: indicator.OutputLine},
		},
		lookback: func(p []float64) int { return ta.RocrLookback(int(p[0])) },
		call: func(in [][]float64, p []float64) [][]float64 {
			o0 := ta.Rocr(in[0], int(p[0]), nil)
			return [][]float64{o0}
		},
	},
	{
		name:          "ROCR100",
		indicatorType: "rocr100",
		title:         "Rate of change ratio 100 scale: (price/prevPrice)*100",
		group:         "Momentum Indicators",
		inputs:        []string{"close"},
		params: []param{
			{key: "period", title: "Time Period", description: "Number of period", kind: paramInteger, minimum: 1, maximum: 100000, defaultValue: 10},
		},
		outputs: []output{
			{name: "rocr100", style: indicator.OutputLine},
		},
		lookback: func(p []float64) int { return ta.Rocr100Lookback(int(p[0])) },
		call: func(in [][]float64, p []float64) [][]float64 {
			o0 := ta.Rocr100(in[0], int(p[0]), nil)
			return [][]float64{o0}
		},
	},
	{
		name:          "RSI",
		indicatorType: "rsi",
		title:         "Relative Strength Index",
		group:         "Momentum Indicators",
		unstable:      true,
		inputs:        []string{"close"},
		params: []param{
			{key: "period", title: "Time Period", description: "Number of period", kind: paramInteger, minimum: 2, maximum: 100000, defaultValue: 14},
		},
		outputs: []output{
			{name: "rsi", style: indicator.OutputLine},
		},
		lookback: func(p []float64) int { return ta.RsiLookback(int(p[0])) },
		call: func(in [][]float64, p []float64) [][]float64 {
			o0 := ta.Rsi(in[0], int(p[0]), nil)
			return [][]float64{o0}
		},
	},
	{
		name:          "SAR",
		indicatorType: "sar",
		title:         "Parabolic SAR",
		group:         "Overlap Studies",
		overlap:       true,
		inputs:        []string{"high", "low"},
		params: []param{
			{key: "acceleration_factor", title: "Acceleration Factor", description: "Acceleration Factor used up to the Maximum value", kind: paramReal, minimum: 0, maximum: 3e+37, defaultValue: 0.02},
			{key: "af_maximum", title: "AF Maximum", description: "Acceleration Factor Maximum value", kind: paramReal, minimum: 0, maximum: 3e+37, defaultValue: 0.2},
		},
		outputs: []output{
			{name: "sar", style: indicator.OutputLine},
		},
		lookback: func(p []float64) int { return ta.SarLookback(p[0], p[1]) },
		call: func(in [][]float64, p []float64) [][]float64 {
			o0 := ta.Sar(in[0], in[1], p[0], p[1], nil)
			return [][]float64{o0}
		},
	},
	{
		name:          "SAREXT",
		indicatorType: "sarext",
		title:         "Parabolic SAR - Extended",
		group:         "Overlap Studies",
		overlap:       true,
		inputs:        []string{"high", "low"},
		params: []param{
			{key: "start_value", title: "Start Value", description: "Start value and direction. 0 for Auto, >0 for Long, <0 for Short", kind: paramReal, minimum: -3e+37, maximum: 3e+37, defaultValue: 0},
			{key: "offset_on_reverse", title: "Offset on Reverse", description: "Percent offset added/removed to initial stop on short/long reversal", kind: paramReal, minimum: 0, maximum: 3e+37, defaultValue: 0},
			{key: "af_init_long", title: "AF Init Long", description: "Acceleration Factor initial value for the Long direction", kind: paramReal, minimum: 0, maximum: 3e+37, defaultValue: 0.02},
			{key: "af_long", title: "AF Long", description: "Acceleration Factor for the Long direction", kind: paramReal, minimum: 0, maximum: 3e+37, defaultValue: 0.02},
			{key: "af_max_long", title: "AF Max Long", description: "Acceleration Factor maximum value for the Long direction", kind: paramReal, minimum: 0, maximum: 3e+37, defaultValue: 0.2},
			{key: "af_init_short", title: "AF Init Short", description: "Acceleration Factor initial value for the Short direction", kind: paramReal, minimum: 0, maximum: 3e+37, defaultValue: 0.02},
			{key: "af_short", title: "AF Short", description: "Acceleration Factor for the Short direction", kind: paramReal, minimum: 0, maximum: 3e+37, defaultValue: 0.02},
			{key: "af_max_short", title: "AF Max Short", description: "Acceleration Factor maximum value for the Short direction", kind: paramReal, minimum: 0, maximum: 3e+37, defaultValue: 0.2},
		},
		outputs: []output{
			{name: "sarext", style: indicator.OutputLine},
		},
		lookback: func(p []float64) int { return ta.SarextLookback(p[0], p[1], p[2], p[3], p[4], p[5], p[6], p[7]) },
		call: func(in [][]float64, p []float64) [][]float64 {
			o0 := ta.Sarext(in[0], in[1], p[0], p[1], p[2], p[3], p[4], p[5], p[6], p[7], nil)
			return [][]float64{o0}
		},
	},
	{
		name:          "SMA",
		indicatorType: "sma",
		title:         "Simple Moving Average",
		group:         "Overlap Studies",
		overlap:       true,
		inputs:        []string{"close"},
		params: []param{
			{key: "period", title: "Time Period", description: "Number of period", kind: paramInteger, minimum: 2, maximum: 100000, defaultValue: 30},
		},
		outputs: []output{
			{name: "sma", style: indicator.OutputLine},
		},
		lookback: func(p []float64) int { return ta.SmaLookback(int(p[0])) },
		call: func(in [][]float64, p []float64) [][]float64 {
			o0 := ta.Sma(in[0], int(p[0]), nil)
			return [][]float64{o0}
		},
	},
	{
		name:          "STDDEV",
		indicatorType: "stddev",
		title:         "Standard Deviation",
		group:         "Statistic Functions",
		inputs:        []string{"close"},
		params: []param{
			{key: "period", title: "Time Period", description: "Number of period", kind: paramInteger, minimum: 2, maximum: 100000, defaultValue: 5},
			{key: "deviations", title: "Deviations", description: "Nb of deviations", kind: paramReal, minimum: -3e+37, maximum: 3e+37, defaultValue: 1},
		},
		outputs: []output{
			{name: "stddev", style: indicator.OutputLine},
		},
		lookback: func(p []float64) int { return ta.StddevLookback(int(p[0]), p[1]) },
		call: func(in [][]float64, p []float64) [][]float64 {
			o0 := ta.Stddev(in[0], int(p[0]), p[1], nil)
			return [][]float64{o0}
		},
	},
	{
		name:          "STOCH",
		indicatorType: "stoch",
		title:         "Stochastic",
		group:         "Momentum Indicators",
		inputs:        []string{"high", "low", "close"},
		params: []param{
			{key: "fast_k_period", title: "Fast-K Period", description: "Time period for building the Fast-K line", kind: paramInteger, minimum: 1, maximum: 100000, defaultValue: 5},
			{key: "slow_k_period", title: "Slow-K Period", description: "Smoothing for making the Slow-K line. Usually set to 3", kind: paramInteger, minimum: 1, maximum: 100000, defaultValue: 3},
			{key: "slow_k_ma", title: "Slow-K MA", description: "Type of Moving Average for Slow-K", kind: paramMAType, defaultValue: 0},
			{key: "slow_d_period", title: "Slow-D Period", description: "Smoothing for making the Slow-D line", kind: paramInteger, minimum: 1, maximum: 100000, defaultValue: 3},
			{key: "slow_d_ma", title: "Slow-D MA", description: "Type of Moving Average for Slow-D", kind: paramMAType, defaultValue: 0},
		},
		outputs: []output{
			{name: "slowk", style: indicator.OutputDashedLine},
			{name: "slowd", style: indicator.OutputDashedLine},
		},
		lookback: func(p []float64) int { return ta.StochLookback(int(p[0]), int(p[1]), int(p[2]), int(p[3]), int(p[4])) },
		call: func(in [][]float64, p []float64) [][]float64 {
			o0, o1 := ta.Stoch(in[0], in[1], in[2], int(p[0]), int(p[1]), int(p[2]), int(p[3]), int(p[4]), nil, nil)
			return [][]float64{o0, o1}
		},
	},
	{
		name:          "STOCHF",
		indicatorType: "stochf",
		title:         "Stochastic Fast",
		group:         "Momentum Indicators",
		inputs:        []string{"high", "low", "close"},
		params: []param{
			{key: "fast_k_period", title: "Fast-K Period", description: "Time period for building the Fast-K line", kind: paramInteger, minimum: 1, maximum: 100000, defaultValue: 5},
			{key: "fast_d_period", title: "Fast-D Period", description: "Smoothing for making the Fast-D line. Usually set to 3", kind: paramInteger, minimum: 1, maximum: 100000, defaultValue: 3},
			{key: "fast_d_ma", title: "Fast-D MA", description: "Type of Moving Average for Fast-D", kind: paramMAType, defaultValue: 0},
		},
		outputs: []output{
			{name: "fastk", style: indicator.OutputLine},
			{name: "fastd", style: indicator.OutputLine},
		},
		lookback: func(p []float64) int { return ta.StochfLookback(int(p[0]), int(p[1]), int(p[2])) },
		call: func(in [][]float64, p []float64) [][]float64 {
			o0, o1 := ta.Stochf(in[0], in[1], in[2], int(p[0]), int(p[1]), int(p[2]), nil, nil)
			return [][]float64{o0, o1}
		},
	},
	{
		name:          "STOCHRSI",
		indicatorType: "stochrsi",
		title:         "Stochastic Relative Strength Index",
		group:         "Momentum Indicators",
		unstable:      true,
		inputs:        []string{"close"},
		params: []param{
			{key: "period", title: "Time Period", description: "Number of period", kind: paramInteger, minimum: 2, maximum: 100000, defaultValue: 14},
			{key: "fast_k_period", title: "Fast-K Period", description: "Time period for building the Fast-K line", kind: paramInteger, minimum: 1, maximum: 100000, defaultValue: 5},
			{key: "fast_d_period", title: "Fast-D Period", description: "Smoothing for making the Fast-D line. Usually set to 3", kind: paramInteger, minimum: 1, maximum: 100000, defaultValue: 3},
			{key: "fast_d_ma", title: "Fast-D MA", description: "Type of Moving Average for Fast-D", kind: paramMAType, defaultValue: 0},
		},
		outputs: []output{
			{name: "fastk", style: indicator.OutputLine},
			{name: "fastd", style: indicator.OutputLine},
		},
		lookback: func(p []float64) int { return ta.StochrsiLookback(int(p[0]), int(p[1]), int(p[2]), int(p[3])) },
		call: func(in [][]float64, p []float64) [][]float64 {
			o0, o1 := ta.Stochrsi(in[0], int(p[0]), int(p[1]), int(p[2]), int(p[3]), nil, nil)
			return [][]float64{o0, o1}
		},
	},
	{
		name:          "SUM",
		indicatorType: "sum",
		title:         "Summation",
		group:         "Math Operators",
		inputs:        []string{"close"},
		params: []param{
			{key: "period", title: "Time Period", description: "Number of period", kind: paramInteger, minimum: 2, maximum: 100000, defaultValue: 30},
		},
		outputs: []output{
			{name: "sum", style: indicator.OutputLine},
		},
		lookback: func(p []float64) int { return ta.SumLookback(int(p[0])) },
		call: func(in [][]float64, p []float64) [][]float64 {
			o0 := ta.Sum(in[0], int(p[0]), nil)
			return [][]float64{o0}
		},
	},
	{
		name:          "T3",
		indicatorType: "t3",
		title:         "Triple Exponential Moving Average (T3)",
		group:         "Overlap Studies",
		overlap:       true,
		unstable:      true,
		inputs:        []string{"close"},
		params: []param{
			{key: "period", title: "Time Period", description: "Number of period", kind: paramInteger, minimum: 2, maximum: 100000, defaultValue: 5},
			{key: "volume_factor", title: "Volume Factor", description: "Volume Factor", kind: paramReal, minimum: 0, maximum: 1, defaultValue: 0.7},
		},
		outputs: []output{
			{name: "t3", style: indicator.OutputLine},
		},
		lookback: func(p []float64) int { return ta.T3Lookback(int(p[0]), p[1]) },
		call: func(in [][]float64, p []float64) [][]float64 {
			o0 := ta.T3(in[0], int(p[0]), p[1], nil)
			return [][]float64{o0}
		},
	},
	{
		name:          "TEMA",
		indicatorType: "tema",
		title:         "Triple Exponential Moving Average",
		group:         "Overlap Studies",
		overlap:       true,
		inputs:        []string{"close"},
		params: []param{
			{key: "period", title: "Time Period", description: "Number of period", kind: paramInteger, minimum: 2, maximum: 100000, defaultValue: 30},
		},
		outputs: []output{
			{name: "tema", style: indicator.OutputLine},
		},
		lookback: func(p []float64) int { return ta.TemaLookback(int(p[0])) },
		call: func(in [][]float64, p []float64) [][]float64 {
			o0 := ta.Tema(in[0], int(p[0]), nil)
			return [][]float64{o0}
		},
	},
	{
		name:          "TRANGE",
		indicatorType: "trange",
		title:         "True Range",
		group:         "Volatility Indicators",
		inputs:        []string{"high", "low", "close"},
		outputs: []output{
			{name: "trange", style: indicator.OutputLine},
		},
		lookback: func(p []float64) int { return ta.TrangeLookback() },
		call: func(in [][]float64, p []float64) [][]float64 {
			o0 := ta.Trange(in[0], in[1], in[2], nil)
			return [][]float64{o0}
		},
	},
	{
		name:          "TRIMA",
		indicatorType: "trima",
		title:         "Triangular Moving Average",
		group:         "Overlap Studies",
		overlap:       true,
		inputs:        []string{"close"},
		params: []param{
			{key: "period", title: "Time Period", description: "Number of period", kind: paramInteger, minimum: 2, maximum: 100000, defaultValue: 30},
		},
		outputs: []output{
			{name: "trima", style: indicator.OutputLine},
		},
		lookback: func(p []float64) int { return ta.TrimaLookback(int(p[0])) },
		call: func(in [][]float64, p []float64) [][]float64 {
			o0 := ta.Trima(in[0], int(p[0]), nil)
			return [][]float64{o0}
		},
	},
	{
		name:          "TRIX",
		indicatorType: "trix",
		title:         "1-day Rate-Of-Change (ROC) of a Triple Smooth EMA",
		group:         "Momentum Indicators",
		inputs:        []string{"close"},
		params: []param{
			{key: "period", title: "Time Period", description: "Number of period", kind: paramInteger, minimum: 1, maximum: 100000, defaultValue: 30},
		},
		outputs: []output{
			{name: "trix", style: indicator.OutputLine},
		},
		lookback: func(p []float64) int { return ta.TrixLookback(int(p[0])) },
		call: func(in [][]float64, p []float64) [][]float64 {
			o0 := ta.Trix(in[0], int(p[0]), nil)
			return [][]float64{o0}
		},
	},
	{
		name:          "TSF",
		indicatorType: "tsf",
		title:         "Time Series Forecast",
		group:         "Statistic Functions",
		overlap:       true,
		inputs:        []string{"close"},
		params: []param{
			{key: "period", title: "Time Period", description: "Number of period", kind: paramInteger, minimum: 2, maximum: 100000, defaultValue: 14},
		},
		outputs: []output{
			{name: "tsf", style: indicator.OutputLine},
		},
		lookback: func(p []float64) int { return ta.TsfLookback(int(p[0])) },
		call: func(in [][]float64, p []float64) [][]float64 {
			o0 := ta.Tsf(in[0], int(p[0]), nil)
			return [][]float64{o0}
		},
	},
	{
		name:          "TYPPRICE",
		indicatorType: "typprice",
		title:         "Typical Price",
		group:         "Price Transform",
		overlap:       true,
		inputs:        []string{"high", "low", "close"},
		outputs: []output{
			{name: "typprice", style: indicator.OutputLine},
		},
		lookback: func(p []float64) int { return ta.TyppriceLookback() },
		call: func(in [][]float64, p []float64) [][]float64 {
			o0 := ta.Typprice(in[0], in[1], in[2], nil)
			return [][]float64{o0}
		},
	},
	{
		name:          "ULTOSC",
		indicatorType: "ultosc",
		title:         "Ultimate Oscillator",
		group:         "Momentum Indicators",
		inputs:        []string{"high", "low", "close"},
		params: []param{
			{key: "first_period", title: "First Period", description: "Number of bars for 1st period.", kind: paramInteger, minimum: 1, maximum: 100000, defaultValue: 7},
			{key: "second_period", title: "Second Period", description: "Number of bars fro 2nd period", kind: paramInteger, minimum: 1, maximum: 100000, defaultValue: 14},
			{key: "third_period", title: "Third Period", description: "Number of bars for 3rd period", kind: paramInteger, minimum: 1, maximum: 100000, defaultValue: 28},
		},
		outputs: []output{
			{name: "ultosc", style: indicator.OutputLine},
		},
		lookback: func(p []float64) int { return ta.UltoscLookback(int(p[0]), int(p[1]), int(p[2])) },
		call: func(in [][]float64, p []float64) [][]float64 {
			o0 := ta.Ultosc(in[0], in[1], in[2], int(p[0]), int(p[1]), int(p[2]), nil)
			return [][]float64{o0}
		},
	},
	{
		name:          "VAR",
		indicatorType: "var",
		title:         "Variance",
		group:         "Statistic Functions",
		inputs:        []string{"close"},
		params: []param{
			{key: "period", title: "Time Period", description: "Number of period", kind: paramInteger, minimum: 1, maximum: 100000, defaultValue: 5},
			{key: "deviations", title: "Deviations", description: "Nb of deviations", kind: paramReal, minimum: -3e+37, maximum: 3e+37, defaultValue: 1},
		},
		outputs: []output{
			{name: "var", style: indicator.OutputLine},
		},
		lookback: func(p []float64) int { return ta.VarLookback(int(p[0]), p[1]) },
		call: func(in [][]float64, p []float64) [][]float64 {
			o0 := ta.Var(in[0], int(p[0]), p[1], nil)
			return [][]float64{o0}
		},
	},
	{
		name:          "WCLPRICE",
		indicatorType: "wclprice",
		title:         "Weighted Close Price",
		group:         "Price Transform",
		overlap:       true,
		inputs:        []string{"high", "low", "close"},
		outputs: []output{
			{name: "wclprice", style: indicator.OutputLine},
		},
		lookback: func(p []float64) int { return ta.WclpriceLookback() },
		call: func(in [][]float64, p []float64) [][]float64 {
			o0 := ta.Wclprice(in[0], in[1], in[2], nil)
			return [][]float64{o0}
		},
	},
	{
		name:          "WILLR",
		indicatorType: "willr",
		title:         "Williams' %R",
		group:         "Momentum Indicators",
		inputs:        []string{"high", "low", "close"},
		params: []param{
			{key: "period", title: "Time Period", description: "Number of period", kind: paramInteger, minimum: 2, maximum: 100000, defaultValue: 14},
		},
		outputs: []output{
			{name: "willr", style: indicator.OutputLine},
		},
		lookback: func(p []float64) int { return ta.WillrLookback(int(p[0])) },
		call: func(in [][]float64, p []float64) [][]float64 {
			o0 := ta.Willr(in[0], in[1], in[2], int(p[0]), nil)
			return [][]float64{o0}
		},
	},
	{
		name:          "WMA",
		indicatorType: "wma",
		title:         "Weighted Moving Average",
		group:         "Overlap Studies",
		overlap:       true,
		inputs:        []string{"close"},
		params: []param{
			{key: "period", title: "Time Period", description: "Number of period", kind: paramInteger, minimum: 2, maximum: 100000, defaultValue: 30},
		},
		outputs: []output{
			{name: "wma", style: indicator.OutputLine},
		},
		lookback: func(p []float64) int { return ta.WmaLookback(int(p[0])) },
		call: func(in [][]float64, p []float64) [][]float64 {
			o0 := ta.Wma(in[0], int(p[0]), nil)
			return [][]float64{o0}
		},
	},
}
