//go:build go1.22

// Package httpapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package httpapi

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
)

// Defines values for APIErrorCode.
const (
	APIErrorCodeAccessDenied               APIErrorCode = "access_denied"
	APIErrorCodeInsufficientData           APIErrorCode = "insufficient_data"
	APIErrorCodeInternalError              APIErrorCode = "internal_error"
	APIErrorCodeInvalidArgument            APIErrorCode = "invalid_argument"
	APIErrorCodeMappingConflict            APIErrorCode = "mapping_conflict"
	APIErrorCodeMappingNotFound            APIErrorCode = "mapping_not_found"
	APIErrorCodeMappingProviderUnavailable APIErrorCode = "mapping_provider_unavailable"
	APIErrorCodeMarketCapMissing           APIErrorCode = "market_cap_missing"
	APIErrorCodeMarketCapUnavailable       APIErrorCode = "market_cap_unavailable"
	APIErrorCodeMarketDataUnavailable      APIErrorCode = "market_data_unavailable"
	APIErrorCodeSymbolNotFound             APIErrorCode = "symbol_not_found"
	APIErrorCodeUnauthenticated            APIErrorCode = "unauthenticated"
)

// Valid indicates whether the value is a known member of the APIErrorCode enum.
func (e APIErrorCode) Valid() bool {
	switch e {
	case APIErrorCodeAccessDenied:
		return true
	case APIErrorCodeInsufficientData:
		return true
	case APIErrorCodeInternalError:
		return true
	case APIErrorCodeInvalidArgument:
		return true
	case APIErrorCodeMappingConflict:
		return true
	case APIErrorCodeMappingNotFound:
		return true
	case APIErrorCodeMappingProviderUnavailable:
		return true
	case APIErrorCodeMarketCapMissing:
		return true
	case APIErrorCodeMarketCapUnavailable:
		return true
	case APIErrorCodeMarketDataUnavailable:
		return true
	case APIErrorCodeSymbolNotFound:
		return true
	case APIErrorCodeUnauthenticated:
		return true
	default:
		return false
	}
}

// Defines values for CandleInterval.
const (
	N1M CandleInterval = "1M"
	N1d CandleInterval = "1d"
	N1h CandleInterval = "1h"
	N1w CandleInterval = "1w"
)

// Valid indicates whether the value is a known member of the CandleInterval enum.
func (e CandleInterval) Valid() bool {
	switch e {
	case N1M:
		return true
	case N1d:
		return true
	case N1h:
		return true
	case N1w:
		return true
	default:
		return false
	}
}

// Defines values for LivenessResponseStatus.
const (
	LivenessResponseStatusOk LivenessResponseStatus = "ok"
)

// Valid indicates whether the value is a known member of the LivenessResponseStatus enum.
func (e LivenessResponseStatus) Valid() bool {
	switch e {
	case LivenessResponseStatusOk:
		return true
	default:
		return false
	}
}

// Defines values for MarketSortDirection.
const (
	Asc  MarketSortDirection = "asc"
	Desc MarketSortDirection = "desc"
)

// Valid indicates whether the value is a known member of the MarketSortDirection enum.
func (e MarketSortDirection) Valid() bool {
	switch e {
	case Asc:
		return true
	case Desc:
		return true
	default:
		return false
	}
}

// Defines values for MarketSortField.
const (
	MarketCapUsd MarketSortField = "market_cap_usd"
)

// Valid indicates whether the value is a known member of the MarketSortField enum.
func (e MarketSortField) Valid() bool {
	switch e {
	case MarketCapUsd:
		return true
	default:
		return false
	}
}

// Defines values for ReadinessCheck.
const (
	ReadinessCheckMissing     ReadinessCheck = "missing"
	ReadinessCheckOk          ReadinessCheck = "ok"
	ReadinessCheckUnavailable ReadinessCheck = "unavailable"
)

// Valid indicates whether the value is a known member of the ReadinessCheck enum.
func (e ReadinessCheck) Valid() bool {
	switch e {
	case ReadinessCheckMissing:
		return true
	case ReadinessCheckOk:
		return true
	case ReadinessCheckUnavailable:
		return true
	default:
		return false
	}
}

// Defines values for ReadinessResponseStatus.
const (
	NotReady ReadinessResponseStatus = "not_ready"
	Ready    ReadinessResponseStatus = "ready"
)

// Valid indicates whether the value is a known member of the ReadinessResponseStatus enum.
func (e ReadinessResponseStatus) Valid() bool {
	switch e {
	case NotReady:
		return true
	case Ready:
		return true
	default:
		return false
	}
}

// Defines values for UnresolvedInstrumentCode.
const (
	UnresolvedInstrumentCodeMappingConflict            UnresolvedInstrumentCode = "mapping_conflict"
	UnresolvedInstrumentCodeMappingNotFound            UnresolvedInstrumentCode = "mapping_not_found"
	UnresolvedInstrumentCodeMappingProviderUnavailable UnresolvedInstrumentCode = "mapping_provider_unavailable"
	UnresolvedInstrumentCodeMarketCapMissing           UnresolvedInstrumentCode = "market_cap_missing"
)

// Valid indicates whether the value is a known member of the UnresolvedInstrumentCode enum.
func (e UnresolvedInstrumentCode) Valid() bool {
	switch e {
	case UnresolvedInstrumentCodeMappingConflict:
		return true
	case UnresolvedInstrumentCodeMappingNotFound:
		return true
	case UnresolvedInstrumentCodeMappingProviderUnavailable:
		return true
	case UnresolvedInstrumentCodeMarketCapMissing:
		return true
	default:
		return false
	}
}

// APIError defines model for APIError.
type APIError struct {
	Code    APIErrorCode `json:"code"`
	Details interface{}  `json:"details,omitempty"`
	Message string       `json:"message"`
}

// APIErrorCode defines model for APIError.Code.
type APIErrorCode string

// Candle defines model for Candle.
type Candle struct {
	Close            float64   `json:"close"`
	CloseTime        time.Time `json:"close_time"`
	High             float64   `json:"high"`
	Low              float64   `json:"low"`
	Open             float64   `json:"open"`
	OpenTime         time.Time `json:"open_time"`
	QuoteAssetVolume float64   `json:"quote_asset_volume"`
	TradeCount       int64     `json:"trade_count"`
	Volume           float64   `json:"volume"`
}

// CandleInterval defines model for CandleInterval.
type CandleInterval string

// CandlePageResponse defines model for CandlePageResponse.
type CandlePageResponse struct {
	Candles    []Candle       `json:"candles"`
	HasMore    bool           `json:"has_more"`
	Interval   CandleInterval `json:"interval"`
	NextBefore *time.Time     `json:"next_before,omitempty"`
	Symbol     string         `json:"symbol"`
}

// ChartIndicatorResult defines model for ChartIndicatorResult.
type ChartIndicatorResult struct {
	Parameters map[string]interface{} `json:"parameters"`
	Series     []IndicatorSeries      `json:"series"`
	Type       string                 `json:"type"`
}

// ChartPageResponse defines model for ChartPageResponse.
type ChartPageResponse struct {
	Candles    []Candle               `json:"candles"`
	HasMore    bool                   `json:"has_more"`
	Indicators []ChartIndicatorResult `json:"indicators"`
	Interval   CandleInterval         `json:"interval"`
	NextBefore *time.Time             `json:"next_before,omitempty"`
	Symbol     string                 `json:"symbol"`
}

// ChartRequest defines model for ChartRequest.
type ChartRequest struct {
	Indicators []IndicatorConfig `json:"indicators"`
}

// CriterionRequest defines model for CriterionRequest.
type CriterionRequest struct {
	Key        string                 `json:"key"`
	Label      string                 `json:"label"`
	Name       string                 `json:"name"`
	Parameters map[string]interface{} `json:"parameters"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error     APIError `json:"error"`
	RequestId string   `json:"request_id"`
}

// Evaluation defines model for Evaluation.
type Evaluation struct {
	CandleCount int                `json:"candle_count"`
	From        time.Time          `json:"from"`
	Key         string             `json:"key"`
	Label       string             `json:"label"`
	Matched     bool               `json:"matched"`
	Metrics     map[string]float64 `json:"metrics"`
	Name        string             `json:"name"`
	To          time.Time          `json:"to"`
}

// IndicatorConfig defines model for IndicatorConfig.
type IndicatorConfig struct {
	Parameters map[string]interface{} `json:"parameters"`
	Type       string                 `json:"type"`
}

// IndicatorPoint defines model for IndicatorPoint.
type IndicatorPoint struct {
	Time  time.Time `json:"time"`
	Value float64   `json:"value"`
}

// IndicatorSeries defines model for IndicatorSeries.
type IndicatorSeries struct {
	Name   string           `json:"name"`
	Points []IndicatorPoint `json:"points"`
}

// InstrumentAnalysisRequest defines model for InstrumentAnalysisRequest.
type InstrumentAnalysisRequest struct {
	Criteria []CriterionRequest `json:"criteria"`
}

// InstrumentAnalysisResponse defines model for InstrumentAnalysisResponse.
type InstrumentAnalysisResponse struct {
	Evaluations []Evaluation `json:"evaluations"`
	Matched     bool         `json:"matched"`
	Symbol      string       `json:"symbol"`
	Warnings    []Warning    `json:"warnings"`
}

// LivenessResponse defines model for LivenessResponse.
type LivenessResponse struct {
	Status LivenessResponseStatus `json:"status"`
}

// LivenessResponseStatus defines model for LivenessResponse.Status.
type LivenessResponseStatus string

// MarketAnalysisItem defines model for MarketAnalysisItem.
type MarketAnalysisItem struct {
	Evaluations  []Evaluation `json:"evaluations"`
	Matched      bool         `json:"matched"`
	PriceHistory []*float64   `json:"price_history"`
	Symbol       string       `json:"symbol"`
}

// MarketAnalysisRequest defines model for MarketAnalysisRequest.
type MarketAnalysisRequest struct {
	Criteria []CriterionRequest `json:"criteria"`

	// Limit Maximum instruments to select. Zero or omission means no limit.
	Limit *int        `json:"limit,omitempty"`
	Sort  *MarketSort `json:"sort,omitempty"`
}

// MarketAnalysisResponse defines model for MarketAnalysisResponse.
type MarketAnalysisResponse struct {
	AnalyzedCount         int                    `json:"analyzed_count"`
	InsufficientDataCount int                    `json:"insufficient_data_count"`
	Items                 []MarketAnalysisItem   `json:"items"`
	MatchedCount          int                    `json:"matched_count"`
	PriceHistoryWindow    PriceHistoryWindow     `json:"price_history_window"`
	Unresolved            []UnresolvedInstrument `json:"unresolved"`
	Warnings              []Warning              `json:"warnings"`
}

// MarketSort defines model for MarketSort.
type MarketSort struct {
	Direction MarketSortDirection `json:"direction"`
	Field     MarketSortField     `json:"field"`
}

// MarketSortDirection defines model for MarketSort.Direction.
type MarketSortDirection string

// MarketSortField defines model for MarketSort.Field.
type MarketSortField string

// PriceHistoryWindow defines model for PriceHistoryWindow.
type PriceHistoryWindow struct {
	From time.Time `json:"from"`
	To   time.Time `json:"to"`
}

// ReadinessCheck defines model for ReadinessCheck.
type ReadinessCheck string

// ReadinessResponse defines model for ReadinessResponse.
type ReadinessResponse struct {
	Checks struct {
		Database   ReadinessCheck `json:"database"`
		MarketSync ReadinessCheck `json:"market_sync"`
		Migrations ReadinessCheck `json:"migrations"`
	} `json:"checks"`
	Status ReadinessResponseStatus `json:"status"`
}

// ReadinessResponseStatus defines model for ReadinessResponse.Status.
type ReadinessResponseStatus string

// UnresolvedInstrument defines model for UnresolvedInstrument.
type UnresolvedInstrument struct {
	Code    UnresolvedInstrumentCode `json:"code"`
	Message string                   `json:"message"`
	Symbol  string                   `json:"symbol"`
}

// UnresolvedInstrumentCode defines model for UnresolvedInstrument.Code.
type UnresolvedInstrumentCode string

// Warning defines model for Warning.
type Warning struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// RequestID defines model for RequestID.
type RequestID = string

// Symbol defines model for Symbol.
type Symbol = string

// AccessDenied defines model for AccessDenied.
type AccessDenied = ErrorResponse

// AnalysisUnavailable defines model for AnalysisUnavailable.
type AnalysisUnavailable = ErrorResponse

// BadRequest defines model for BadRequest.
type BadRequest = ErrorResponse

// InsufficientData defines model for InsufficientData.
type InsufficientData = ErrorResponse

// InternalError defines model for InternalError.
type InternalError = ErrorResponse

// SymbolNotFound defines model for SymbolNotFound.
type SymbolNotFound = ErrorResponse

// Unauthenticated defines model for Unauthenticated.
type Unauthenticated = ErrorResponse

// UnprocessableAnalysis defines model for UnprocessableAnalysis.
type UnprocessableAnalysis = ErrorResponse

// AnalyzeInstrumentParams defines parameters for AnalyzeInstrument.
type AnalyzeInstrumentParams struct {
	// XRequestID Optional caller-provided correlation ID. Unsafe values are replaced.
	XRequestID *RequestID `json:"X-Request-ID,omitempty"`
}

// AnalyzeMarketParams defines parameters for AnalyzeMarket.
type AnalyzeMarketParams struct {
	// XRequestID Optional caller-provided correlation ID. Unsafe values are replaced.
	XRequestID *RequestID `json:"X-Request-ID,omitempty"`
}

// ListInstrumentCandlesParams defines parameters for ListInstrumentCandles.
type ListInstrumentCandlesParams struct {
	// Interval Supported Binance Spot candle interval.
	Interval CandleInterval `form:"interval" json:"interval"`

	// Before Return candles whose open time is before this cursor.
	Before *time.Time `form:"before,omitempty" json:"before,omitempty"`

	// Limit Maximum number of candles to return.
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// XRequestID Optional caller-provided correlation ID. Unsafe values are replaced.
	XRequestID *RequestID `json:"X-Request-ID,omitempty"`
}

// GetInstrumentChartParams defines parameters for GetInstrumentChart.
type GetInstrumentChartParams struct {
	Interval CandleInterval `form:"interval" json:"interval"`

	// Before Return visible candles whose open time is before this cursor.
	Before *time.Time `form:"before,omitempty" json:"before,omitempty"`
	Limit  *int       `form:"limit,omitempty" json:"limit,omitempty"`

	// XRequestID Optional caller-provided correlation ID. Unsafe values are replaced.
	XRequestID *RequestID `json:"X-Request-ID,omitempty"`
}

// GetLivenessParams defines parameters for GetLiveness.
type GetLivenessParams struct {
	// XRequestID Optional caller-provided correlation ID. Unsafe values are replaced.
	XRequestID *RequestID `json:"X-Request-ID,omitempty"`
}

// GetReadinessParams defines parameters for GetReadiness.
type GetReadinessParams struct {
	// XRequestID Optional caller-provided correlation ID. Unsafe values are replaced.
	XRequestID *RequestID `json:"X-Request-ID,omitempty"`
}

// AnalyzeInstrumentJSONRequestBody defines body for AnalyzeInstrument for application/json ContentType.
type AnalyzeInstrumentJSONRequestBody = InstrumentAnalysisRequest

// AnalyzeMarketJSONRequestBody defines body for AnalyzeMarket for application/json ContentType.
type AnalyzeMarketJSONRequestBody = MarketAnalysisRequest

// GetInstrumentChartJSONRequestBody defines body for GetInstrumentChart for application/json ContentType.
type GetInstrumentChartJSONRequestBody = ChartRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// AnalyzeInstrument Analyze one active instrument
	// (POST /api/v1/analysis/instruments/{symbol})
	AnalyzeInstrument(w http.ResponseWriter, r *http.Request, symbol Symbol, params AnalyzeInstrumentParams)
	// AnalyzeMarket Analyze active instruments in the market
	// (POST /api/v1/analysis/market)
	AnalyzeMarket(w http.ResponseWriter, r *http.Request, params AnalyzeMarketParams)
	// ListInstrumentCandles List a chronological page of closed candles
	// (GET /api/v1/instruments/{symbol}/candles)
	ListInstrumentCandles(w http.ResponseWriter, r *http.Request, symbol Symbol, params ListInstrumentCandlesParams)
	// GetInstrumentChart Get a chronological candle page with aligned technical indicators
	// (POST /api/v1/instruments/{symbol}/chart)
	GetInstrumentChart(w http.ResponseWriter, r *http.Request, symbol Symbol, params GetInstrumentChartParams)
	// GetLiveness Check whether the process is alive
	// (GET /health/live)
	GetLiveness(w http.ResponseWriter, r *http.Request, params GetLivenessParams)
	// GetReadiness Check whether required service dependencies are ready
	// (GET /health/ready)
	GetReadiness(w http.ResponseWriter, r *http.Request, params GetReadinessParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// AnalyzeInstrument operation middleware
func (siw *ServerInterfaceWrapper) AnalyzeInstrument(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "symbol" -------------
	var symbol Symbol

	err = runtime.BindStyledParameterWithOptions("simple", "symbol", r.PathValue("symbol"), &symbol, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "symbol", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params AnalyzeInstrumentParams

	headers := r.Header

	// ------------- Optional header parameter "X-Request-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Request-ID")]; found {
		var XRequestID RequestID
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Request-ID", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Request-ID", valueList[0], &XRequestID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Request-ID", Err: err})
			return
		}

		params.XRequestID = &XRequestID

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AnalyzeInstrument(w, r, symbol, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AnalyzeMarket operation middleware
func (siw *ServerInterfaceWrapper) AnalyzeMarket(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params AnalyzeMarketParams

	headers := r.Header

	// ------------- Optional header parameter "X-Request-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Request-ID")]; found {
		var XRequestID RequestID
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Request-ID", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Request-ID", valueList[0], &XRequestID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Request-ID", Err: err})
			return
		}

		params.XRequestID = &XRequestID

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AnalyzeMarket(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListInstrumentCandles operation middleware
func (siw *ServerInterfaceWrapper) ListInstrumentCandles(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "symbol" -------------
	var symbol Symbol

	err = runtime.BindStyledParameterWithOptions("simple", "symbol", r.PathValue("symbol"), &symbol, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "symbol", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ListInstrumentCandlesParams

	// ------------- Required query parameter "interval" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "interval", r.URL.Query(), &params.Interval, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "interval"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "interval", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "before" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "before", r.URL.Query(), &params.Before, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "before"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "before", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	headers := r.Header

	// ------------- Optional header parameter "X-Request-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Request-ID")]; found {
		var XRequestID RequestID
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Request-ID", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Request-ID", valueList[0], &XRequestID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Request-ID", Err: err})
			return
		}

		params.XRequestID = &XRequestID

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListInstrumentCandles(w, r, symbol, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetInstrumentChart operation middleware
func (siw *ServerInterfaceWrapper) GetInstrumentChart(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "symbol" -------------
	var symbol Symbol

	err = runtime.BindStyledParameterWithOptions("simple", "symbol", r.PathValue("symbol"), &symbol, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "symbol", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetInstrumentChartParams

	// ------------- Required query parameter "interval" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "interval", r.URL.Query(), &params.Interval, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "interval"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "interval", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "before" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "before", r.URL.Query(), &params.Before, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "before"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "before", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	headers := r.Header

	// ------------- Optional header parameter "X-Request-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Request-ID")]; found {
		var XRequestID RequestID
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Request-ID", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Request-ID", valueList[0], &XRequestID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Request-ID", Err: err})
			return
		}

		params.XRequestID = &XRequestID

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetInstrumentChart(w, r, symbol, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetLiveness operation middleware
func (siw *ServerInterfaceWrapper) GetLiveness(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetLivenessParams

	headers := r.Header

	// ------------- Optional header parameter "X-Request-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Request-ID")]; found {
		var XRequestID RequestID
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Request-ID", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Request-ID", valueList[0], &XRequestID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Request-ID", Err: err})
			return
		}

		params.XRequestID = &XRequestID

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetLiveness(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetReadiness operation middleware
func (siw *ServerInterfaceWrapper) GetReadiness(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetReadinessParams

	headers := r.Header

	// ------------- Optional header parameter "X-Request-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Request-ID")]; found {
		var XRequestID RequestID
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Request-ID", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Request-ID", valueList[0], &XRequestID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Request-ID", Err: err})
			return
		}

		params.XRequestID = &XRequestID

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetReadiness(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/health/live", wrapper.GetLiveness)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/health/ready", wrapper.GetReadiness)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/v1/analysis/instruments/{symbol}", wrapper.AnalyzeInstrument)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/v1/analysis/market", wrapper.AnalyzeMarket)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/instruments/{symbol}/candles", wrapper.ListInstrumentCandles)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/v1/instruments/{symbol}/chart", wrapper.GetInstrumentChart)

	return m
}

type AccessDeniedResponseHeaders struct {
	XRequestID string
}
type AccessDeniedJSONResponse struct {
	Body ErrorResponse

	Headers AccessDeniedResponseHeaders
}

type AnalysisUnavailableResponseHeaders struct {
	XRequestID string
}
type AnalysisUnavailableJSONResponse struct {
	Body ErrorResponse

	Headers AnalysisUnavailableResponseHeaders
}

type BadRequestResponseHeaders struct {
	XRequestID string
}
type BadRequestJSONResponse struct {
	Body ErrorResponse

	Headers BadRequestResponseHeaders
}

type InsufficientDataResponseHeaders struct {
	XRequestID string
}
type InsufficientDataJSONResponse struct {
	Body ErrorResponse

	Headers InsufficientDataResponseHeaders
}

type InternalErrorResponseHeaders struct {
	XRequestID string
}
type InternalErrorJSONResponse struct {
	Body ErrorResponse

	Headers InternalErrorResponseHeaders
}

type SymbolNotFoundResponseHeaders struct {
	XRequestID string
}
type SymbolNotFoundJSONResponse struct {
	Body ErrorResponse

	Headers SymbolNotFoundResponseHeaders
}

type UnauthenticatedResponseHeaders struct {
	XRequestID string
}
type UnauthenticatedJSONResponse struct {
	Body ErrorResponse

	Headers UnauthenticatedResponseHeaders
}

type UnprocessableAnalysisResponseHeaders struct {
	XRequestID string
}
type UnprocessableAnalysisJSONResponse struct {
	Body ErrorResponse

	Headers UnprocessableAnalysisResponseHeaders
}

type AnalyzeInstrumentRequestObject struct {
	Symbol Symbol `json:"symbol"`
	Params AnalyzeInstrumentParams
	Body   *AnalyzeInstrumentJSONRequestBody
}

type AnalyzeInstrumentResponseObject interface {
	VisitAnalyzeInstrumentResponse(w http.ResponseWriter) error
}

type AnalyzeInstrument200ResponseHeaders struct {
	XRequestID string
}

type AnalyzeInstrument200JSONResponse struct {
	Body    InstrumentAnalysisResponse
	Headers AnalyzeInstrument200ResponseHeaders
}

func (response AnalyzeInstrument200JSONResponse) VisitAnalyzeInstrumentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Request-ID", fmt.Sprint(response.Headers.XRequestID))
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type AnalyzeInstrument400JSONResponse struct{ BadRequestJSONResponse }

func (response AnalyzeInstrument400JSONResponse) VisitAnalyzeInstrumentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Request-ID", fmt.Sprint(response.Headers.XRequestID))
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type AnalyzeInstrument401JSONResponse struct{ UnauthenticatedJSONResponse }

func (response AnalyzeInstrument401JSONResponse) VisitAnalyzeInstrumentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Request-ID", fmt.Sprint(response.Headers.XRequestID))
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type AnalyzeInstrument403JSONResponse struct{ AccessDeniedJSONResponse }

func (response AnalyzeInstrument403JSONResponse) VisitAnalyzeInstrumentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Request-ID", fmt.Sprint(response.Headers.XRequestID))
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type AnalyzeInstrument404JSONResponse struct{ SymbolNotFoundJSONResponse }

func (response AnalyzeInstrument404JSONResponse) VisitAnalyzeInstrumentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Request-ID", fmt.Sprint(response.Headers.XRequestID))
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type AnalyzeInstrument409JSONResponse struct{ InsufficientDataJSONResponse }

func (response AnalyzeInstrument409JSONResponse) VisitAnalyzeInstrumentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Request-ID", fmt.Sprint(response.Headers.XRequestID))
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type AnalyzeInstrument422JSONResponse struct {
	UnprocessableAnalysisJSONResponse
}

func (response AnalyzeInstrument422JSONResponse) VisitAnalyzeInstrumentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Request-ID", fmt.Sprint(response.Headers.XRequestID))
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type AnalyzeInstrument500JSONResponse struct{ InternalErrorJSONResponse }

func (response AnalyzeInstrument500JSONResponse) VisitAnalyzeInstrumentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Request-ID", fmt.Sprint(response.Headers.XRequestID))
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type AnalyzeInstrument503JSONResponse struct {
	AnalysisUnavailableJSONResponse
}

func (response AnalyzeInstrument503JSONResponse) VisitAnalyzeInstrumentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Request-ID", fmt.Sprint(response.Headers.XRequestID))
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type AnalyzeMarketRequestObject struct {
	Params AnalyzeMarketParams
	Body   *AnalyzeMarketJSONRequestBody
}

type AnalyzeMarketResponseObject interface {
	VisitAnalyzeMarketResponse(w http.ResponseWriter) error
}

type AnalyzeMarket200ResponseHeaders struct {
	XRequestID string
}

type AnalyzeMarket200JSONResponse struct {
	Body    MarketAnalysisResponse
	Headers AnalyzeMarket200ResponseHeaders
}

func (response AnalyzeMarket200JSONResponse) VisitAnalyzeMarketResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Request-ID", fmt.Sprint(response.Headers.XRequestID))
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type AnalyzeMarket400JSONResponse struct{ BadRequestJSONResponse }

func (response AnalyzeMarket400JSONResponse) VisitAnalyzeMarketResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Request-ID", fmt.Sprint(response.Headers.XRequestID))
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type AnalyzeMarket401JSONResponse struct{ UnauthenticatedJSONResponse }

func (response AnalyzeMarket401JSONResponse) VisitAnalyzeMarketResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Request-ID", fmt.Sprint(response.Headers.XRequestID))
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type AnalyzeMarket403JSONResponse struct{ AccessDeniedJSONResponse }

func (response AnalyzeMarket403JSONResponse) VisitAnalyzeMarketResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Request-ID", fmt.Sprint(response.Headers.XRequestID))
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type AnalyzeMarket422JSONResponse struct {
	UnprocessableAnalysisJSONResponse
}

func (response AnalyzeMarket422JSONResponse) VisitAnalyzeMarketResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Request-ID", fmt.Sprint(response.Headers.XRequestID))
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type AnalyzeMarket500JSONResponse struct{ InternalErrorJSONResponse }

func (response AnalyzeMarket500JSONResponse) VisitAnalyzeMarketResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Request-ID", fmt.Sprint(response.Headers.XRequestID))
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type AnalyzeMarket503JSONResponse struct {
	AnalysisUnavailableJSONResponse
}

func (response AnalyzeMarket503JSONResponse) VisitAnalyzeMarketResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Request-ID", fmt.Sprint(response.Headers.XRequestID))
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type ListInstrumentCandlesRequestObject struct {
	Symbol Symbol `json:"symbol"`
	Params ListInstrumentCandlesParams
}

type ListInstrumentCandlesResponseObject interface {
	VisitListInstrumentCandlesResponse(w http.ResponseWriter) error
}

type ListInstrumentCandles200ResponseHeaders struct {
	XRequestID string
}

type ListInstrumentCandles200JSONResponse struct {
	Body    CandlePageResponse
	Headers ListInstrumentCandles200ResponseHeaders
}

func (response ListInstrumentCandles200JSONResponse) VisitListInstrumentCandlesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Request-ID", fmt.Sprint(response.Headers.XRequestID))
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListInstrumentCandles400JSONResponse struct{ BadRequestJSONResponse }

func (response ListInstrumentCandles400JSONResponse) VisitListInstrumentCandlesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Request-ID", fmt.Sprint(response.Headers.XRequestID))
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ListInstrumentCandles401JSONResponse struct{ UnauthenticatedJSONResponse }

func (response ListInstrumentCandles401JSONResponse) VisitListInstrumentCandlesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Request-ID", fmt.Sprint(response.Headers.XRequestID))
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListInstrumentCandles403JSONResponse struct{ AccessDeniedJSONResponse }

func (response ListInstrumentCandles403JSONResponse) VisitListInstrumentCandlesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Request-ID", fmt.Sprint(response.Headers.XRequestID))
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type ListInstrumentCandles404JSONResponse struct{ SymbolNotFoundJSONResponse }

func (response ListInstrumentCandles404JSONResponse) VisitListInstrumentCandlesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Request-ID", fmt.Sprint(response.Headers.XRequestID))
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type ListInstrumentCandles500JSONResponse struct{ InternalErrorJSONResponse }

func (response ListInstrumentCandles500JSONResponse) VisitListInstrumentCandlesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Request-ID", fmt.Sprint(response.Headers.XRequestID))
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetInstrumentChartRequestObject struct {
	Symbol Symbol `json:"symbol"`
	Params GetInstrumentChartParams
	Body   *GetInstrumentChartJSONRequestBody
}

type GetInstrumentChartResponseObject interface {
	VisitGetInstrumentChartResponse(w http.ResponseWriter) error
}

type GetInstrumentChart200ResponseHeaders struct {
	XRequestID string
}

type GetInstrumentChart200JSONResponse struct {
	Body    ChartPageResponse
	Headers GetInstrumentChart200ResponseHeaders
}

func (response GetInstrumentChart200JSONResponse) VisitGetInstrumentChartResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Request-ID", fmt.Sprint(response.Headers.XRequestID))
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetInstrumentChart400JSONResponse struct{ BadRequestJSONResponse }

func (response GetInstrumentChart400JSONResponse) VisitGetInstrumentChartResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Request-ID", fmt.Sprint(response.Headers.XRequestID))
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetInstrumentChart401JSONResponse struct{ UnauthenticatedJSONResponse }

func (response GetInstrumentChart401JSONResponse) VisitGetInstrumentChartResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Request-ID", fmt.Sprint(response.Headers.XRequestID))
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetInstrumentChart403JSONResponse struct{ AccessDeniedJSONResponse }

func (response GetInstrumentChart403JSONResponse) VisitGetInstrumentChartResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Request-ID", fmt.Sprint(response.Headers.XRequestID))
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type GetInstrumentChart404JSONResponse struct{ SymbolNotFoundJSONResponse }

func (response GetInstrumentChart404JSONResponse) VisitGetInstrumentChartResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Request-ID", fmt.Sprint(response.Headers.XRequestID))
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetInstrumentChart500JSONResponse struct{ InternalErrorJSONResponse }

func (response GetInstrumentChart500JSONResponse) VisitGetInstrumentChartResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Request-ID", fmt.Sprint(response.Headers.XRequestID))
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetLivenessRequestObject struct {
	Params GetLivenessParams
}

type GetLivenessResponseObject interface {
	VisitGetLivenessResponse(w http.ResponseWriter) error
}

type GetLiveness200ResponseHeaders struct {
	XRequestID string
}

type GetLiveness200JSONResponse struct {
	Body    LivenessResponse
	Headers GetLiveness200ResponseHeaders
}

func (response GetLiveness200JSONResponse) VisitGetLivenessResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Request-ID", fmt.Sprint(response.Headers.XRequestID))
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetReadinessRequestObject struct {
	Params GetReadinessParams
}

type GetReadinessResponseObject interface {
	VisitGetReadinessResponse(w http.ResponseWriter) error
}

type GetReadiness200ResponseHeaders struct {
	XRequestID string
}

type GetReadiness200JSONResponse struct {
	Body    ReadinessResponse
	Headers GetReadiness200ResponseHeaders
}

func (response GetReadiness200JSONResponse) VisitGetReadinessResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Request-ID", fmt.Sprint(response.Headers.XRequestID))
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetReadiness503ResponseHeaders struct {
	XRequestID string
}

type GetReadiness503JSONResponse struct {
	Body    ReadinessResponse
	Headers GetReadiness503ResponseHeaders
}

func (response GetReadiness503JSONResponse) VisitGetReadinessResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Request-ID", fmt.Sprint(response.Headers.XRequestID))
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// AnalyzeInstrument Analyze one active instrument
	// (POST /api/v1/analysis/instruments/{symbol})
	AnalyzeInstrument(ctx context.Context, request AnalyzeInstrumentRequestObject) (AnalyzeInstrumentResponseObject, error)
	// AnalyzeMarket Analyze active instruments in the market
	// (POST /api/v1/analysis/market)
	AnalyzeMarket(ctx context.Context, request AnalyzeMarketRequestObject) (AnalyzeMarketResponseObject, error)
	// ListInstrumentCandles List a chronological page of closed candles
	// (GET /api/v1/instruments/{symbol}/candles)
	ListInstrumentCandles(ctx context.Context, request ListInstrumentCandlesRequestObject) (ListInstrumentCandlesResponseObject, error)
	// GetInstrumentChart Get a chronological candle page with aligned technical indicators
	// (POST /api/v1/instruments/{symbol}/chart)
	GetInstrumentChart(ctx context.Context, request GetInstrumentChartRequestObject) (GetInstrumentChartResponseObject, error)
	// GetLiveness Check whether the process is alive
	// (GET /health/live)
	GetLiveness(ctx context.Context, request GetLivenessRequestObject) (GetLivenessResponseObject, error)
	// GetReadiness Check whether required service dependencies are ready
	// (GET /health/ready)
	GetReadiness(ctx context.Context, request GetReadinessRequestObject) (GetReadinessResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// AnalyzeInstrument operation middleware
func (sh *strictHandler) AnalyzeInstrument(w http.ResponseWriter, r *http.Request, symbol Symbol, params AnalyzeInstrumentParams) {
	var request AnalyzeInstrumentRequestObject

	request.Symbol = symbol
	request.Params = params

	var body AnalyzeInstrumentJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.AnalyzeInstrument(ctx, request.(AnalyzeInstrumentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AnalyzeInstrument")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(AnalyzeInstrumentResponseObject); ok {
		if err := validResponse.VisitAnalyzeInstrumentResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// AnalyzeMarket operation middleware
func (sh *strictHandler) AnalyzeMarket(w http.ResponseWriter, r *http.Request, params AnalyzeMarketParams) {
	var request AnalyzeMarketRequestObject

	request.Params = params

	var body AnalyzeMarketJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.AnalyzeMarket(ctx, request.(AnalyzeMarketRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AnalyzeMarket")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(AnalyzeMarketResponseObject); ok {
		if err := validResponse.VisitAnalyzeMarketResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListInstrumentCandles operation middleware
func (sh *strictHandler) ListInstrumentCandles(w http.ResponseWriter, r *http.Request, symbol Symbol, params ListInstrumentCandlesParams) {
	var request ListInstrumentCandlesRequestObject

	request.Symbol = symbol
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListInstrumentCandles(ctx, request.(ListInstrumentCandlesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListInstrumentCandles")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListInstrumentCandlesResponseObject); ok {
		if err := validResponse.VisitListInstrumentCandlesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetInstrumentChart operation middleware
func (sh *strictHandler) GetInstrumentChart(w http.ResponseWriter, r *http.Request, symbol Symbol, params GetInstrumentChartParams) {
	var request GetInstrumentChartRequestObject

	request.Symbol = symbol
	request.Params = params

	var body GetInstrumentChartJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetInstrumentChart(ctx, request.(GetInstrumentChartRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetInstrumentChart")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetInstrumentChartResponseObject); ok {
		if err := validResponse.VisitGetInstrumentChartResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetLiveness operation middleware
func (sh *strictHandler) GetLiveness(w http.ResponseWriter, r *http.Request, params GetLivenessParams) {
	var request GetLivenessRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetLiveness(ctx, request.(GetLivenessRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetLiveness")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetLivenessResponseObject); ok {
		if err := validResponse.VisitGetLivenessResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetReadiness operation middleware
func (sh *strictHandler) GetReadiness(w http.ResponseWriter, r *http.Request, params GetReadinessParams) {
	var request GetReadinessRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetReadiness(ctx, request.(GetReadinessRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetReadiness")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetReadinessResponseObject); ok {
		if err := validResponse.VisitGetReadinessResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7Fvdb9s4Ev9XCN49KnHc/cBt3tL0rg2uvQ2aFnu4IPAy1NjihiJVknLiLfy/H0jq06YsyXXcLnbfbEmj",
	"+eRvhsPRZ0xlmkkBwmh8/hknQGJQ7ud7+JSDNlev7J8YNFUsM0wKfI4vpVLAif2Hrl4hojVbCIiRkcgk",
	"gJSnPMURtj+ZghifG5VDhDVNICX2jWaVAT7H2igmFni9Xkc4I4qkYPr5/+x+EI4o4RzUSabkksUQI9oS",
	"7BR9FJrMAS0Jz0EjoqxsGScUYiscs+/yGuMIC5Jagf57UjA+uXqFdwkc4ZtVei/5tngX1LAloJSoBzBI",
	"u6cqfhkxSc3N39xpqJSJtyAWJsHn0yhkNgU6k0KDs9oFpaD1KxDMvsu6VxgQxv4kWcYZdcaZ/KatpJ8b",
	"bP6uYI7P8d8mdUBM/F09+adSUr0v2HimbY0/JIBIbhIQxnKAGH0ADgtFUpRrUIhpJKRBIMg997ZvBFrL",
	"4h2SFI9P6qBwUlwIwlea6Y+CLAnj9u3HU/p94bLS0TExBElV/D2hJGOGcPa7D0d3l2mU16Iezg4vSVxc",
	"Oa7Pi5Vu9UoJn0uVQmxNYCUgTGhEBMqFzrNMKhsVRC3yFIQ5nOZXQufzOaMMhHlFDPkq+lvNikhExULW",
	"KJUKECUi5oASpo1Uq0OqbUAJwp2Ux9P5wroTnjKgVmcNagkKgaVCktJcqUMubg+v/5HmXzIXRwYzj8t+",
	"vT4I+ShsVDNBHLIfTsWPooWaR9SxhOcGf4tSdiEzrZlYRIiJJeEsjqzq8JSxgzr3o8iUtKnKAmEJ40cN",
	"ZCa0UQ6NEJU5j12GurdrWku+hBjNpaqW9aEUX5eZ3Sfr66tqAZM4Zr6quVYyA2WYTehzwjVEOGtcsiaK",
	"XZoDkaf4/BYTl/NnsU/6ts6oMXFm84675gFj5laru+C8OyshGUc4JVnGxGJGpZhzRpuXhDSzuVuG9bWi",
	"6lKzRkpzt236m1GSzYpQal8MPm2l3Ljjl2CLc76xXO626iHrZ0MYt3ZaRzi1AbaAcPlWl1y33qT18/WL",
	"5f1vQI198aWD8rGu4lI7GpsbicHnOJa5169gIPL0HpRl4J6dGZZuEBADJ+5qQNuELZKBr+fyceCTMgMx",
	"4tGRIn/KpYEZ0RrMbCl5ng61j1EkhhmVuUeHioIJ8+P31nlMsNSuiLOK2Eb9wlOPYLURG7WOLR8Vdip8",
	"4O1bPIArdkF126p0x5pL8kvCm2t9allN7WKYWnbTd8FF4OmvyQIqEBwZt+4F7iczkOo+wC0Wx7qShShF",
	"Vi5CiZ7ZUqixBu+l5ECEvcsaKva/vzLIOsICnszsHubFq3fE3m1pmAiLnHN8ty7BpR8Xqv1ZJWhU2aah",
	"W9CHCVHmSsQWq1wyyrkZ6YX2hjhM6LeLW9w1KDbCf5WcN54u4Ej/v89g7m5rK1/J0mmkP0ScFvYZwSrk",
	"/wDjP/YSaBhmyHpo7FJHeHkP61eGv5RizhwopuTpypP+wyWL4s900yUb+jeYB9VSzIBiUuyn2gOsAi6I",
	"MCf3wIN3fOcocGNvtNhQ2IpUsCnlaL08ZIV2wT3OBFCWwLv8WZXKhbCgzYzF/dFblrsNmqD8S8Jz4jcH",
	"ewBQXZXsLkLmSqbDK6XxsZESQxOIwxiWglGM7giOYVXYpuk649HIoaoOCcBStVqPqG38wrqOb8jFm4hw",
	"tFRcJs7djdy+NLpTpWvJxFjkGVe1uxb6PtVz8UJPv1OJm6pkGaFFNxpak+yRL7wp1z1JoQjOgklYrbK9",
	"UHY39ksQ1OcXMrzu2ExI6zHZrmK3pVOEn04W8qQ4uOhWr0P3/VJDBcvDPdmA8kC1tRMhO0uiCD8SJZhY",
	"DBfjF0/QG0lVeVUDXFPrBudQlL1lSxCg97WvNsTkZdvNhiaWD73wXBCFxHnnujml023IfdsOzxSjMCu6",
	"8y2GXTB3W+Jco5KuC8vpjz+1Fpv9uynQ6Lq7KzDawve749vEnwhzljKzfYr6jjzZSqrRp9XISKSBAzWn",
	"6H+gJJIKSddklAKlQIRGQiL3vlNnuCdfi03PzvraQ1oq06eZN+eNfXJf2Ax7JOCqvZaz61b/DvHQcnSr",
	"UTyYsAyEQRERQIXuhTpUhFb0zx6ZiH1/c5cg15bmjSf5xVOsI5yLsuU/WKOPFUmd6kI6PVvWCGq/acNo",
	"MyC6PV66tGWNntzTWA7jwjRmCmi516oOMTTF/pQm2NGcM+Bx8/nmiYIOHQVsWMy/IGowD+kUiJBxuo3b",
	"4e29Rdq91XkPJGa2LLhMgD40rebS+8YJTHFIE7J69aJ923OW/9iS3oblPfG8dq2VDS3X1WGSXgm6BzFb",
	"qLryGEO74ZtK/tY729KFvFYXY6W3FJDYbYWlmfnfdwOLs6g0fYhREL2+7Ajy2Y4OQ1HZfaq3R3U14OSv",
	"BOX9TDRC/LGHkq7PT3PFzOrGxmaxsS/O9q8Eq0ZiOk7/3zHB0EWWISZYMcCUKZizJ4jRIzMJ+tWkBP3a",
	"OSx3kZtEqmLEqQYtkrF/w8qfuzMxl9sSvPnw4RpdXF+5Q3YNaskooAQIN0mEqFplRrpxEkFX5XhVeRQf",
	"ISLiwGCNYYZb5peOGt1QIgQoywRHeAlKe87T07PTs/LokmQMn+PvTqenZ67bYhJnwQnJ2GQ5nZQsJ40a",
	"dPLZh87adYWkr6et350NrmI3XOCybmNxtZuzt2F4qR9pzgxEvQ8XY4jru6rL+VLGq4PNUuzY6bcD1qgc",
	"NscRX5ydPasg3RMe9dPN2Syd8wMOn33vtQtRVFaYNGbzHMm0n2RzLMjRfddP1xr+dETf9xNtjFk5sp/6",
	"ybYG7yzhixdDlAtN/qwj/MMQa7YH3xzVEMME5kSb6OnW5DZu3t7ZRaXzNCVqVS9sJAUgPwrW2J1aCCK2",
	"1L+txlLxnWWyhSYe0Hrxw9fXX4Idz4QIHZvY46JBx4Y5gATv2vnjz4cCf5JVubUiNWLCfZCQlitp9wIN",
	"ZflJY8JgAYHF+pZpU+eay+pg/AgJP9qsqm6qQeuXTBBBAd1k0pS1Unl+X1Vzn3JQq7qYa5zvd3+NMGZC",
	"YVvA92ByJQqBNHpMpAZkCzFkd72IaeTHGZBJmEY0V1qqLnGLwYemcMM20l2NRt/YRXJeyWckUk7iLhl8",
	"67IpQgxz4gZ9XrieY9mB/KHVgZxuN7Q8Vj8TVgbGwQI46Z9CGVnAXyVST4m0DyqORzaLLYggmigpJJcL",
	"Rgl3/nFByqWGciOkG+BW5Dv3ygH4lhC1oxZ5DU10c88eC9u+LkYtmWb3HL46Vh0Ddg5fIraGvY5cGW7P",
	"FO4GO9dPINx/wlhNeyE/tfgXEn4TSPgatoGQNlzomlWlDw3QRLhHWtOJ3fjoG08TzpbQWee9BlMetn/x",
	"luyZAn9rGKDj46ai0rcQpnIhmFgc8vOWymeuO44eEzAJKFeHNxgTZ+zaKW+cC9r+8C3vHQ6pGvHfqke2",
	"z09C3yJxXn41GKMYMhAxCMqqD5ZJfMAPB4uN2fG0+1mA+yhWKtih5TN8FbsjFis5ys5z2OrB8PSz9csy",
	"znLF8TmeuDAqHi6H0koim8XLfnm9sa6uNeFofbf+fwAAAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
