// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: alerts.sql

package sqlc

import (
	"context"
)

const deletePriceAlert = `-- name: DeletePriceAlert :execrows
DELETE FROM app.price_alerts WHERE id = $1 AND user_id = $2
`

type DeletePriceAlertParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) DeletePriceAlert(ctx context.Context, arg DeletePriceAlertParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletePriceAlert, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const firePriceAlert = `-- name: FirePriceAlert :one
DELETE FROM app.price_alerts a
USING app.users u
WHERE a.id = $1 AND a.version = $2 AND a.user_id = u.id
RETURNING a.id, a.user_id, a.instrument_id, a.target::text AS target
`

type FirePriceAlertParams struct {
	ID      int64
	Version int64
}

type FirePriceAlertRow struct {
	ID           int64
	UserID       int64
	InstrumentID int64
	Target       string
}

func (q *Queries) FirePriceAlert(ctx context.Context, arg FirePriceAlertParams) (FirePriceAlertRow, error) {
	row := q.db.QueryRow(ctx, firePriceAlert, arg.ID, arg.Version)
	var i FirePriceAlertRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.InstrumentID,
		&i.Target,
	)
	return i, err
}

const insertPriceAlert = `-- name: InsertPriceAlert :one
INSERT INTO app.price_alerts (user_id, instrument_id, target)
VALUES ($1, $2, $3)
RETURNING id, user_id, instrument_id, target, version, created_at, updated_at
`

type InsertPriceAlertParams struct {
	UserID       int64
	InstrumentID int64
	Target       string
}

func (q *Queries) InsertPriceAlert(ctx context.Context, arg InsertPriceAlertParams) (AppPriceAlert, error) {
	row := q.db.QueryRow(ctx, insertPriceAlert, arg.UserID, arg.InstrumentID, arg.Target)
	var i AppPriceAlert
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.InstrumentID,
		&i.Target,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEnabledPriceAlerts = `-- name: ListEnabledPriceAlerts :many
SELECT a.id, a.user_id, a.instrument_id, a.target, a.version, a.created_at, a.updated_at, i.symbol, u.telegram_id
FROM app.price_alerts a
JOIN app.users u ON u.id = a.user_id
JOIN binance_spot.instruments i ON i.id = a.instrument_id AND i.is_active
ORDER BY i.symbol, a.target, a.id
`

type ListEnabledPriceAlertsRow struct {
	AppPriceAlert AppPriceAlert
	Symbol        string
	TelegramID    int64
}

func (q *Queries) ListEnabledPriceAlerts(ctx context.Context) ([]ListEnabledPriceAlertsRow, error) {
	rows, err := q.db.Query(ctx, listEnabledPriceAlerts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEnabledPriceAlertsRow
	for rows.Next() {
		var i ListEnabledPriceAlertsRow
		if err := rows.Scan(
			&i.AppPriceAlert.ID,
			&i.AppPriceAlert.UserID,
			&i.AppPriceAlert.InstrumentID,
			&i.AppPriceAlert.Target,
			&i.AppPriceAlert.Version,
			&i.AppPriceAlert.CreatedAt,
			&i.AppPriceAlert.UpdatedAt,
			&i.Symbol,
			&i.TelegramID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPriceAlerts = `-- name: ListPriceAlerts :many
SELECT a.id, a.user_id, a.instrument_id, a.target, a.version, a.created_at, a.updated_at, i.symbol, u.telegram_id
FROM app.price_alerts a
JOIN app.users u ON u.id = a.user_id
JOIN binance_spot.instruments i ON i.id = a.instrument_id
WHERE a.user_id = $1 AND i.symbol = $2
ORDER BY a.target, a.id
`

type ListPriceAlertsParams struct {
	UserID int64
	Symbol string
}

type ListPriceAlertsRow struct {
	AppPriceAlert AppPriceAlert
	Symbol        string
	TelegramID    int64
}

func (q *Queries) ListPriceAlerts(ctx context.Context, arg ListPriceAlertsParams) ([]ListPriceAlertsRow, error) {
	rows, err := q.db.Query(ctx, listPriceAlerts, arg.UserID, arg.Symbol)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPriceAlertsRow
	for rows.Next() {
		var i ListPriceAlertsRow
		if err := rows.Scan(
			&i.AppPriceAlert.ID,
			&i.AppPriceAlert.UserID,
			&i.AppPriceAlert.InstrumentID,
			&i.AppPriceAlert.Target,
			&i.AppPriceAlert.Version,
			&i.AppPriceAlert.CreatedAt,
			&i.AppPriceAlert.UpdatedAt,
			&i.Symbol,
			&i.TelegramID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockPriceAlertSymbol = `-- name: LockPriceAlertSymbol :one
SELECT i.symbol
FROM app.price_alerts a
JOIN binance_spot.instruments i ON i.id = a.instrument_id
WHERE a.id = $1 AND a.user_id = $2
FOR UPDATE OF a
`

type LockPriceAlertSymbolParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) LockPriceAlertSymbol(ctx context.Context, arg LockPriceAlertSymbolParams) (string, error) {
	row := q.db.QueryRow(ctx, lockPriceAlertSymbol, arg.ID, arg.UserID)
	var symbol string
	err := row.Scan(&symbol)
	return symbol, err
}

const updatePriceAlert = `-- name: UpdatePriceAlert :one
UPDATE app.price_alerts
SET target = $3, version = version + 1, updated_at = now()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, instrument_id, target, version, created_at, updated_at
`

type UpdatePriceAlertParams struct {
	ID     int64
	UserID int64
	Target string
}

func (q *Queries) UpdatePriceAlert(ctx context.Context, arg UpdatePriceAlertParams) (AppPriceAlert, error) {
	row := q.db.QueryRow(ctx, updatePriceAlert, arg.ID, arg.UserID, arg.Target)
	var i AppPriceAlert
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.InstrumentID,
		&i.Target,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
