// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: api_tokens.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAPIToken = `-- name: CreateAPIToken :one
INSERT INTO app.api_tokens (user_id, name, token_hash, created_at)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type CreateAPITokenParams struct {
	UserID    int64
	Name      string
	TokenHash []byte
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) CreateAPIToken(ctx context.Context, arg CreateAPITokenParams) (int64, error) {
	row := q.db.QueryRow(ctx, createAPIToken,
		arg.UserID,
		arg.Name,
		arg.TokenHash,
		arg.CreatedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteAPIToken = `-- name: DeleteAPIToken :execrows
DELETE FROM app.api_tokens
WHERE id = $1 AND user_id = $2
`

type DeleteAPITokenParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) DeleteAPIToken(ctx context.Context, arg DeleteAPITokenParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAPIToken, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findAPIToken = `-- name: FindAPIToken :one
SELECT u.id, u.telegram_id, u.username, u.display_name, u.created_at, u.updated_at, u.strategy_alerts, t.id, t.last_used_at
FROM app.api_tokens AS t
JOIN app.users AS u ON u.id = t.user_id
WHERE t.token_hash = $1
`

type FindAPITokenRow struct {
	AppUser    AppUser
	ID         int64
	LastUsedAt pgtype.Timestamptz
}

func (q *Queries) FindAPIToken(ctx context.Context, tokenHash []byte) (FindAPITokenRow, error) {
	row := q.db.QueryRow(ctx, findAPIToken, tokenHash)
	var i FindAPITokenRow
	err := row.Scan(
		&i.AppUser.ID,
		&i.AppUser.TelegramID,
		&i.AppUser.Username,
		&i.AppUser.DisplayName,
		&i.AppUser.CreatedAt,
		&i.AppUser.UpdatedAt,
		&i.AppUser.StrategyAlerts,
		&i.ID,
		&i.LastUsedAt,
	)
	return i, err
}

const listAPITokens = `-- name: ListAPITokens :many
SELECT id, name, created_at, last_used_at
FROM app.api_tokens
WHERE user_id = $1
ORDER BY created_at DESC, id DESC
`

type ListAPITokensRow struct {
	ID         int64
	Name       string
	CreatedAt  pgtype.Timestamptz
	LastUsedAt pgtype.Timestamptz
}

func (q *Queries) ListAPITokens(ctx context.Context, userID int64) ([]ListAPITokensRow, error) {
	rows, err := q.db.Query(ctx, listAPITokens, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAPITokensRow
	for rows.Next() {
		var i ListAPITokensRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchAPIToken = `-- name: TouchAPIToken :exec
UPDATE app.api_tokens
SET last_used_at = $1
WHERE id = $2 AND (last_used_at IS NULL OR last_used_at <= $3)
`

type TouchAPITokenParams struct {
	UsedAt      pgtype.Timestamptz
	ID          int64
	TouchBefore pgtype.Timestamptz
}

// The predicate keeps concurrent requests to one write per minimum interval
// and never moves the last use back.
func (q *Queries) TouchAPIToken(ctx context.Context, arg TouchAPITokenParams) error {
	_, err := q.db.Exec(ctx, touchAPIToken, arg.UsedAt, arg.ID, arg.TouchBefore)
	return err
}
