// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: batch.go

package sqlc

import (
	"context"
	"errors"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
)

var (
	ErrBatchAlreadyClosed = errors.New("batch already closed")
)

const upsertCandle = `-- name: UpsertCandle :batchone
INSERT INTO binance_spot.candles (
    instrument_id, interval, open_time, close_time, open, high, low, close,
    volume, quote_asset_volume, trade_count
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
ON CONFLICT (instrument_id, interval, open_time) DO UPDATE SET
    close_time = EXCLUDED.close_time,
    open = EXCLUDED.open,
    high = EXCLUDED.high,
    low = EXCLUDED.low,
    close = EXCLUDED.close,
    volume = EXCLUDED.volume,
    quote_asset_volume = EXCLUDED.quote_asset_volume,
    trade_count = EXCLUDED.trade_count
WHERE (binance_spot.candles.close_time, binance_spot.candles.open, binance_spot.candles.high,
       binance_spot.candles.low, binance_spot.candles.close, binance_spot.candles.volume,
       binance_spot.candles.quote_asset_volume, binance_spot.candles.trade_count)
  IS DISTINCT FROM (EXCLUDED.close_time, EXCLUDED.open, EXCLUDED.high, EXCLUDED.low,
                    EXCLUDED.close, EXCLUDED.volume, EXCLUDED.quote_asset_volume, EXCLUDED.trade_count)
RETURNING open_time
`

type UpsertCandleBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type UpsertCandleParams struct {
	InstrumentID     int64
	Interval         string
	OpenTime         pgtype.Timestamptz
	CloseTime        pgtype.Timestamptz
	Open             string
	High             string
	Low              string
	Close            string
	Volume           string
	QuoteAssetVolume string
	TradeCount       int64
}

func (q *Queries) UpsertCandle(ctx context.Context, arg []UpsertCandleParams) *UpsertCandleBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.InstrumentID,
			a.Interval,
			a.OpenTime,
			a.CloseTime,
			a.Open,
			a.High,
			a.Low,
			a.Close,
			a.Volume,
			a.QuoteAssetVolume,
			a.TradeCount,
		}
		batch.Queue(upsertCandle, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &UpsertCandleBatchResults{br, len(arg), false}
}

func (b *UpsertCandleBatchResults) QueryRow(f func(int, pgtype.Timestamptz, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		var open_time pgtype.Timestamptz
		if b.closed {
			if f != nil {
				f(t, open_time, ErrBatchAlreadyClosed)
			}
			continue
		}
		row := b.br.QueryRow()
		err := row.Scan(&open_time)
		if f != nil {
			f(t, open_time, err)
		}
	}
}

func (b *UpsertCandleBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}
