// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: batch.go

package sqlc

import (
	"context"
	"errors"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
)

var (
	ErrBatchAlreadyClosed = errors.New("batch already closed")
)

const upsertCandle = `-- name: UpsertCandle :batchone
INSERT INTO binance_spot.candles (
    instrument_id, interval, open_time, close_time, open, high, low, close,
    volume, quote_asset_volume, trade_count
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
ON CONFLICT (instrument_id, interval, open_time) DO UPDATE SET
    close_time = EXCLUDED.close_time,
    open = EXCLUDED.open,
    high = EXCLUDED.high,
    low = EXCLUDED.low,
    close = EXCLUDED.close,
    volume = EXCLUDED.volume,
    quote_asset_volume = EXCLUDED.quote_asset_volume,
    trade_count = EXCLUDED.trade_count
WHERE (binance_spot.candles.close_time, binance_spot.candles.open, binance_spot.candles.high,
       binance_spot.candles.low, binance_spot.candles.close, binance_spot.candles.volume,
       binance_spot.candles.quote_asset_volume, binance_spot.candles.trade_count)
  IS DISTINCT FROM (EXCLUDED.close_time, EXCLUDED.open, EXCLUDED.high, EXCLUDED.low,
                    EXCLUDED.close, EXCLUDED.volume, EXCLUDED.quote_asset_volume, EXCLUDED.trade_count)
RETURNING open_time
`

type UpsertCandleBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type UpsertCandleParams struct {
	InstrumentID     int64
	Interval         string
	OpenTime         pgtype.Timestamptz
	CloseTime        pgtype.Timestamptz
	Open             float64
	High             float64
	Low              float64
	Close            float64
	Volume           float64
	QuoteAssetVolume float64
	TradeCount       int64
}

func (q *Queries) UpsertCandle(ctx context.Context, arg []UpsertCandleParams) *UpsertCandleBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.InstrumentID,
			a.Interval,
			a.OpenTime,
			a.CloseTime,
			a.Open,
			a.High,
			a.Low,
			a.Close,
			a.Volume,
			a.QuoteAssetVolume,
			a.TradeCount,
		}
		batch.Queue(upsertCandle, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &UpsertCandleBatchResults{br, len(arg), false}
}

func (b *UpsertCandleBatchResults) QueryRow(f func(int, pgtype.Timestamptz, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		var open_time pgtype.Timestamptz
		if b.closed {
			if f != nil {
				f(t, open_time, ErrBatchAlreadyClosed)
			}
			continue
		}
		row := b.br.QueryRow()
		err := row.Scan(&open_time)
		if f != nil {
			f(t, open_time, err)
		}
	}
}

func (b *UpsertCandleBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const upsertCoinGeckoMapping = `-- name: UpsertCoinGeckoMapping :batchexec
INSERT INTO app.coingecko_asset_mappings (base_asset, coin_id, quote_asset, source_symbol, status, reason, observed_at, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (base_asset) DO UPDATE SET coin_id=EXCLUDED.coin_id, quote_asset=EXCLUDED.quote_asset, source_symbol=EXCLUDED.source_symbol, status=EXCLUDED.status, reason=EXCLUDED.reason, observed_at=EXCLUDED.observed_at, expires_at=EXCLUDED.expires_at
`

type UpsertCoinGeckoMappingBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type UpsertCoinGeckoMappingParams struct {
	BaseAsset    string
	CoinID       pgtype.Text
	QuoteAsset   string
	SourceSymbol string
	Status       string
	Reason       pgtype.Text
	ObservedAt   pgtype.Timestamptz
	ExpiresAt    pgtype.Timestamptz
}

func (q *Queries) UpsertCoinGeckoMapping(ctx context.Context, arg []UpsertCoinGeckoMappingParams) *UpsertCoinGeckoMappingBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.BaseAsset,
			a.CoinID,
			a.QuoteAsset,
			a.SourceSymbol,
			a.Status,
			a.Reason,
			a.ObservedAt,
			a.ExpiresAt,
		}
		batch.Queue(upsertCoinGeckoMapping, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &UpsertCoinGeckoMappingBatchResults{br, len(arg), false}
}

func (b *UpsertCoinGeckoMappingBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *UpsertCoinGeckoMappingBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const upsertCoinGeckoMarketCap = `-- name: UpsertCoinGeckoMarketCap :batchexec
INSERT INTO app.coingecko_market_caps (coin_id, market_cap_usd, fetched_at, observed_at) VALUES ($1, $2, $3, $4)
ON CONFLICT (coin_id) DO UPDATE SET market_cap_usd=EXCLUDED.market_cap_usd, fetched_at=EXCLUDED.fetched_at, observed_at=EXCLUDED.observed_at
`

type UpsertCoinGeckoMarketCapBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type UpsertCoinGeckoMarketCapParams struct {
	CoinID       string
	MarketCapUsd string
	FetchedAt    pgtype.Timestamptz
	ObservedAt   pgtype.Timestamptz
}

func (q *Queries) UpsertCoinGeckoMarketCap(ctx context.Context, arg []UpsertCoinGeckoMarketCapParams) *UpsertCoinGeckoMarketCapBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.CoinID,
			a.MarketCapUsd,
			a.FetchedAt,
			a.ObservedAt,
		}
		batch.Queue(upsertCoinGeckoMarketCap, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &UpsertCoinGeckoMarketCapBatchResults{br, len(arg), false}
}

func (b *UpsertCoinGeckoMarketCapBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *UpsertCoinGeckoMarketCapBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}
