// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: candles.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listLatestCandles = `-- name: ListLatestCandles :many
SELECT instrument_id, interval, open_time, close_time, open, high, low, close,
       volume, quote_asset_volume, trade_count
FROM binance_spot.candles
WHERE instrument_id = $1
ORDER BY open_time DESC
LIMIT $2
`

type ListLatestCandlesParams struct {
	InstrumentID int64
	Limit        int32
}

func (q *Queries) ListLatestCandles(ctx context.Context, arg ListLatestCandlesParams) ([]BinanceSpotCandle, error) {
	rows, err := q.db.Query(ctx, listLatestCandles, arg.InstrumentID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BinanceSpotCandle
	for rows.Next() {
		var i BinanceSpotCandle
		if err := rows.Scan(
			&i.InstrumentID,
			&i.Interval,
			&i.OpenTime,
			&i.CloseTime,
			&i.Open,
			&i.High,
			&i.Low,
			&i.Close,
			&i.Volume,
			&i.QuoteAssetVolume,
			&i.TradeCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCandle = `-- name: UpsertCandle :exec
INSERT INTO binance_spot.candles (
    instrument_id, interval, open_time, close_time, open, high, low, close,
    volume, quote_asset_volume, trade_count
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
ON CONFLICT (instrument_id, interval, open_time) DO UPDATE SET
    close_time = EXCLUDED.close_time,
    open = EXCLUDED.open,
    high = EXCLUDED.high,
    low = EXCLUDED.low,
    close = EXCLUDED.close,
    volume = EXCLUDED.volume,
    quote_asset_volume = EXCLUDED.quote_asset_volume,
    trade_count = EXCLUDED.trade_count
`

type UpsertCandleParams struct {
	InstrumentID     int64
	Interval         string
	OpenTime         pgtype.Timestamptz
	CloseTime        pgtype.Timestamptz
	Open             string
	High             string
	Low              string
	Close            string
	Volume           string
	QuoteAssetVolume string
	TradeCount       int64
}

func (q *Queries) UpsertCandle(ctx context.Context, arg UpsertCandleParams) error {
	_, err := q.db.Exec(ctx, upsertCandle,
		arg.InstrumentID,
		arg.Interval,
		arg.OpenTime,
		arg.CloseTime,
		arg.Open,
		arg.High,
		arg.Low,
		arg.Close,
		arg.Volume,
		arg.QuoteAssetVolume,
		arg.TradeCount,
	)
	return err
}
