// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: candles.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCandleHistoryCoverage = `-- name: GetCandleHistoryCoverage :one
SELECT instrument_id, interval, verified_oldest_open_time, target_depth,
       policy_version, retry_after
FROM binance_spot.candle_history_coverage
WHERE instrument_id = $1 AND interval = $2
`

type GetCandleHistoryCoverageParams struct {
	InstrumentID int64
	Interval     string
}

func (q *Queries) GetCandleHistoryCoverage(ctx context.Context, arg GetCandleHistoryCoverageParams) (BinanceSpotCandleHistoryCoverage, error) {
	row := q.db.QueryRow(ctx, getCandleHistoryCoverage, arg.InstrumentID, arg.Interval)
	var i BinanceSpotCandleHistoryCoverage
	err := row.Scan(
		&i.InstrumentID,
		&i.Interval,
		&i.VerifiedOldestOpenTime,
		&i.TargetDepth,
		&i.PolicyVersion,
		&i.RetryAfter,
	)
	return i, err
}

const listCandlePage = `-- name: ListCandlePage :many
SELECT instrument_id, interval, open_time, close_time, open, high, low, close,
       volume, quote_asset_volume, trade_count
FROM binance_spot.candles
WHERE instrument_id = $1
  AND interval = $2
  AND close_time < now()
  AND ($3::timestamptz IS NULL OR open_time < $3)
ORDER BY open_time DESC
LIMIT $4
`

type ListCandlePageParams struct {
	InstrumentID int64
	Interval     string
	BeforeTime   pgtype.Timestamptz
	RowLimit     int32
}

func (q *Queries) ListCandlePage(ctx context.Context, arg ListCandlePageParams) ([]BinanceSpotCandle, error) {
	rows, err := q.db.Query(ctx, listCandlePage,
		arg.InstrumentID,
		arg.Interval,
		arg.BeforeTime,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BinanceSpotCandle
	for rows.Next() {
		var i BinanceSpotCandle
		if err := rows.Scan(
			&i.InstrumentID,
			&i.Interval,
			&i.OpenTime,
			&i.CloseTime,
			&i.Open,
			&i.High,
			&i.Low,
			&i.Close,
			&i.Volume,
			&i.QuoteAssetVolume,
			&i.TradeCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHourlyPrices = `-- name: ListHourlyPrices :many
SELECT instrument_id, open_time, close
FROM binance_spot.candles
WHERE instrument_id = ANY($1::bigint[])
  AND interval = '1h'
  AND open_time >= $2
  AND open_time <= $3
  AND close_time < $3::timestamptz + INTERVAL '1 hour'
ORDER BY instrument_id, open_time
`

type ListHourlyPricesParams struct {
	InstrumentIds []int64
	FromTime      pgtype.Timestamptz
	ToTime        pgtype.Timestamptz
}

type ListHourlyPricesRow struct {
	InstrumentID int64
	OpenTime     pgtype.Timestamptz
	Close        string
}

func (q *Queries) ListHourlyPrices(ctx context.Context, arg ListHourlyPricesParams) ([]ListHourlyPricesRow, error) {
	rows, err := q.db.Query(ctx, listHourlyPrices, arg.InstrumentIds, arg.FromTime, arg.ToTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListHourlyPricesRow
	for rows.Next() {
		var i ListHourlyPricesRow
		if err := rows.Scan(&i.InstrumentID, &i.OpenTime, &i.Close); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLatestCandles = `-- name: ListLatestCandles :many
SELECT instrument_id, interval, open_time, close_time, open, high, low, close,
       volume, quote_asset_volume, trade_count
FROM binance_spot.candles
WHERE instrument_id = $1
  AND interval = $2
ORDER BY open_time DESC
LIMIT $3
`

type ListLatestCandlesParams struct {
	InstrumentID int64
	Interval     string
	Limit        int32
}

func (q *Queries) ListLatestCandles(ctx context.Context, arg ListLatestCandlesParams) ([]BinanceSpotCandle, error) {
	rows, err := q.db.Query(ctx, listLatestCandles, arg.InstrumentID, arg.Interval, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BinanceSpotCandle
	for rows.Next() {
		var i BinanceSpotCandle
		if err := rows.Scan(
			&i.InstrumentID,
			&i.Interval,
			&i.OpenTime,
			&i.CloseTime,
			&i.Open,
			&i.High,
			&i.Low,
			&i.Close,
			&i.Volume,
			&i.QuoteAssetVolume,
			&i.TradeCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLatestCandlesBatch = `-- name: ListLatestCandlesBatch :many
SELECT candle.instrument_id, candle.interval, candle.open_time, candle.close_time,
       candle.open, candle.high, candle.low, candle.close,
       candle.volume, candle.quote_asset_volume, candle.trade_count
FROM unnest($1::bigint[]) AS selected(instrument_id)
CROSS JOIN LATERAL (
    SELECT instrument_id, interval, open_time, close_time, open, high, low, close,
           volume, quote_asset_volume, trade_count
    FROM binance_spot.candles
    WHERE instrument_id = selected.instrument_id
      AND interval = $2
    ORDER BY open_time DESC
    LIMIT $3
) AS candle
ORDER BY candle.instrument_id, candle.open_time DESC
`

type ListLatestCandlesBatchParams struct {
	InstrumentIds []int64
	Interval      string
	RowLimit      int32
}

func (q *Queries) ListLatestCandlesBatch(ctx context.Context, arg ListLatestCandlesBatchParams) ([]BinanceSpotCandle, error) {
	rows, err := q.db.Query(ctx, listLatestCandlesBatch, arg.InstrumentIds, arg.Interval, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BinanceSpotCandle
	for rows.Next() {
		var i BinanceSpotCandle
		if err := rows.Scan(
			&i.InstrumentID,
			&i.Interval,
			&i.OpenTime,
			&i.CloseTime,
			&i.Open,
			&i.High,
			&i.Low,
			&i.Close,
			&i.Volume,
			&i.QuoteAssetVolume,
			&i.TradeCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveCandleHistoryCoverage = `-- name: SaveCandleHistoryCoverage :exec
INSERT INTO binance_spot.candle_history_coverage (
    instrument_id, interval, verified_oldest_open_time, target_depth,
    policy_version, retry_after
) VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (instrument_id, interval) DO UPDATE SET
    verified_oldest_open_time = EXCLUDED.verified_oldest_open_time,
    target_depth = EXCLUDED.target_depth,
    policy_version = EXCLUDED.policy_version,
    retry_after = EXCLUDED.retry_after
`

type SaveCandleHistoryCoverageParams struct {
	InstrumentID           int64
	Interval               string
	VerifiedOldestOpenTime pgtype.Timestamptz
	TargetDepth            int32
	PolicyVersion          int32
	RetryAfter             pgtype.Timestamptz
}

func (q *Queries) SaveCandleHistoryCoverage(ctx context.Context, arg SaveCandleHistoryCoverageParams) error {
	_, err := q.db.Exec(ctx, saveCandleHistoryCoverage,
		arg.InstrumentID,
		arg.Interval,
		arg.VerifiedOldestOpenTime,
		arg.TargetDepth,
		arg.PolicyVersion,
		arg.RetryAfter,
	)
	return err
}

const upsertCandle = `-- name: UpsertCandle :one
INSERT INTO binance_spot.candles (
    instrument_id, interval, open_time, close_time, open, high, low, close,
    volume, quote_asset_volume, trade_count
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
ON CONFLICT (instrument_id, interval, open_time) DO UPDATE SET
    close_time = EXCLUDED.close_time,
    open = EXCLUDED.open,
    high = EXCLUDED.high,
    low = EXCLUDED.low,
    close = EXCLUDED.close,
    volume = EXCLUDED.volume,
    quote_asset_volume = EXCLUDED.quote_asset_volume,
    trade_count = EXCLUDED.trade_count
WHERE (binance_spot.candles.close_time, binance_spot.candles.open, binance_spot.candles.high,
       binance_spot.candles.low, binance_spot.candles.close, binance_spot.candles.volume,
       binance_spot.candles.quote_asset_volume, binance_spot.candles.trade_count)
  IS DISTINCT FROM (EXCLUDED.close_time, EXCLUDED.open, EXCLUDED.high, EXCLUDED.low,
                    EXCLUDED.close, EXCLUDED.volume, EXCLUDED.quote_asset_volume, EXCLUDED.trade_count)
RETURNING open_time
`

type UpsertCandleParams struct {
	InstrumentID     int64
	Interval         string
	OpenTime         pgtype.Timestamptz
	CloseTime        pgtype.Timestamptz
	Open             string
	High             string
	Low              string
	Close            string
	Volume           string
	QuoteAssetVolume string
	TradeCount       int64
}

func (q *Queries) UpsertCandle(ctx context.Context, arg UpsertCandleParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, upsertCandle,
		arg.InstrumentID,
		arg.Interval,
		arg.OpenTime,
		arg.CloseTime,
		arg.Open,
		arg.High,
		arg.Low,
		arg.Close,
		arg.Volume,
		arg.QuoteAssetVolume,
		arg.TradeCount,
	)
	var open_time pgtype.Timestamptz
	err := row.Scan(&open_time)
	return open_time, err
}
