// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: candles.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listCandleHistoryCoverage = `-- name: ListCandleHistoryCoverage :many
SELECT instrument_id, interval, verified_oldest_open_time, target_depth,
       policy_version, retry_after
FROM binance_spot.candle_history_coverage
WHERE instrument_id = ANY($1::bigint[])
  AND interval = $2
`

type ListCandleHistoryCoverageParams struct {
	InstrumentIds []int64
	Interval      string
}

func (q *Queries) ListCandleHistoryCoverage(ctx context.Context, arg ListCandleHistoryCoverageParams) ([]BinanceSpotCandleHistoryCoverage, error) {
	rows, err := q.db.Query(ctx, listCandleHistoryCoverage, arg.InstrumentIds, arg.Interval)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BinanceSpotCandleHistoryCoverage
	for rows.Next() {
		var i BinanceSpotCandleHistoryCoverage
		if err := rows.Scan(
			&i.InstrumentID,
			&i.Interval,
			&i.VerifiedOldestOpenTime,
			&i.TargetDepth,
			&i.PolicyVersion,
			&i.RetryAfter,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCandlePage = `-- name: ListCandlePage :many
SELECT instrument_id, interval, open_time, close_time, open, high, low, close,
       volume, quote_asset_volume, trade_count
FROM binance_spot.candles
WHERE instrument_id = $1
  AND interval = $2
  AND close_time < now()
  AND ($3::timestamptz IS NULL OR open_time < $3)
ORDER BY open_time DESC
LIMIT $4
`

type ListCandlePageParams struct {
	InstrumentID int64
	Interval     string
	BeforeTime   pgtype.Timestamptz
	RowLimit     int32
}

func (q *Queries) ListCandlePage(ctx context.Context, arg ListCandlePageParams) ([]BinanceSpotCandle, error) {
	rows, err := q.db.Query(ctx, listCandlePage,
		arg.InstrumentID,
		arg.Interval,
		arg.BeforeTime,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BinanceSpotCandle
	for rows.Next() {
		var i BinanceSpotCandle
		if err := rows.Scan(
			&i.InstrumentID,
			&i.Interval,
			&i.OpenTime,
			&i.CloseTime,
			&i.Open,
			&i.High,
			&i.Low,
			&i.Close,
			&i.Volume,
			&i.QuoteAssetVolume,
			&i.TradeCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHourlyPrices = `-- name: ListHourlyPrices :many
SELECT instrument_id, open_time, close
FROM binance_spot.candles
WHERE instrument_id = ANY($1::bigint[])
  AND interval = '1h'
  AND open_time >= $2
  AND open_time <= $3
  AND close_time < $3::timestamptz + INTERVAL '1 hour'
ORDER BY instrument_id, open_time
`

type ListHourlyPricesParams struct {
	InstrumentIds []int64
	FromTime      pgtype.Timestamptz
	ToTime        pgtype.Timestamptz
}

type ListHourlyPricesRow struct {
	InstrumentID int64
	OpenTime     pgtype.Timestamptz
	Close        float64
}

func (q *Queries) ListHourlyPrices(ctx context.Context, arg ListHourlyPricesParams) ([]ListHourlyPricesRow, error) {
	rows, err := q.db.Query(ctx, listHourlyPrices, arg.InstrumentIds, arg.FromTime, arg.ToTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListHourlyPricesRow
	for rows.Next() {
		var i ListHourlyPricesRow
		if err := rows.Scan(&i.InstrumentID, &i.OpenTime, &i.Close); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLatestCandles = `-- name: ListLatestCandles :many
SELECT candle.instrument_id, candle.interval, candle.open_time, candle.close_time,
       candle.open, candle.high, candle.low, candle.close,
       candle.volume, candle.quote_asset_volume, candle.trade_count
FROM unnest($1::bigint[]) AS selected(instrument_id)
CROSS JOIN LATERAL (
    SELECT instrument_id, interval, open_time, close_time, open, high, low, close,
           volume, quote_asset_volume, trade_count
    FROM binance_spot.candles
    WHERE instrument_id = selected.instrument_id
      AND interval = $2
    ORDER BY open_time DESC
    LIMIT $3
) AS candle
`

type ListLatestCandlesParams struct {
	InstrumentIds []int64
	Interval      string
	RowLimit      int32
}

// Returns up to row_limit latest candles per instrument, grouped by
// instrument. Rows are not sorted globally; callers order each instrument's
// candles, which avoids sorting every returned row.
func (q *Queries) ListLatestCandles(ctx context.Context, arg ListLatestCandlesParams) ([]BinanceSpotCandle, error) {
	rows, err := q.db.Query(ctx, listLatestCandles, arg.InstrumentIds, arg.Interval, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BinanceSpotCandle
	for rows.Next() {
		var i BinanceSpotCandle
		if err := rows.Scan(
			&i.InstrumentID,
			&i.Interval,
			&i.OpenTime,
			&i.CloseTime,
			&i.Open,
			&i.High,
			&i.Low,
			&i.Close,
			&i.Volume,
			&i.QuoteAssetVolume,
			&i.TradeCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneCandles = `-- name: PruneCandles :execrows
DELETE FROM binance_spot.candles AS candle
USING (
    SELECT instrument.id AS instrument_id, cutoff.open_time
    FROM binance_spot.instruments AS instrument
    CROSS JOIN LATERAL (
        SELECT recent.open_time
        FROM binance_spot.candles AS recent
        WHERE recent.instrument_id = instrument.id AND recent.interval = $1
        ORDER BY recent.open_time DESC
        OFFSET $2::int
        LIMIT 1
    ) AS cutoff
) AS bound
WHERE candle.instrument_id = bound.instrument_id
  AND candle.interval = $1
  AND candle.open_time <= bound.open_time
`

type PruneCandlesParams struct {
	Interval  string
	KeepCount int32
}

// Keeps the newest keep_count candles of the interval per instrument.
func (q *Queries) PruneCandles(ctx context.Context, arg PruneCandlesParams) (int64, error) {
	result, err := q.db.Exec(ctx, pruneCandles, arg.Interval, arg.KeepCount)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const saveCandleHistoryCoverage = `-- name: SaveCandleHistoryCoverage :exec
INSERT INTO binance_spot.candle_history_coverage (
    instrument_id, interval, verified_oldest_open_time, target_depth,
    policy_version, retry_after
) VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (instrument_id, interval) DO UPDATE SET
    verified_oldest_open_time = EXCLUDED.verified_oldest_open_time,
    target_depth = EXCLUDED.target_depth,
    policy_version = EXCLUDED.policy_version,
    retry_after = EXCLUDED.retry_after
`

type SaveCandleHistoryCoverageParams struct {
	InstrumentID           int64
	Interval               string
	VerifiedOldestOpenTime pgtype.Timestamptz
	TargetDepth            int32
	PolicyVersion          int32
	RetryAfter             pgtype.Timestamptz
}

func (q *Queries) SaveCandleHistoryCoverage(ctx context.Context, arg SaveCandleHistoryCoverageParams) error {
	_, err := q.db.Exec(ctx, saveCandleHistoryCoverage,
		arg.InstrumentID,
		arg.Interval,
		arg.VerifiedOldestOpenTime,
		arg.TargetDepth,
		arg.PolicyVersion,
		arg.RetryAfter,
	)
	return err
}

const saveEmptyCandleGap = `-- name: SaveEmptyCandleGap :exec
INSERT INTO binance_spot.empty_candle_gaps (instrument_id, interval, gap_from, gap_to, retry_after)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (instrument_id, interval, gap_from) DO UPDATE SET
    gap_to = EXCLUDED.gap_to,
    retry_after = EXCLUDED.retry_after
`

type SaveEmptyCandleGapParams struct {
	InstrumentID int64
	Interval     string
	GapFrom      pgtype.Timestamptz
	GapTo        pgtype.Timestamptz
	RetryAfter   pgtype.Timestamptz
}

func (q *Queries) SaveEmptyCandleGap(ctx context.Context, arg SaveEmptyCandleGapParams) error {
	_, err := q.db.Exec(ctx, saveEmptyCandleGap,
		arg.InstrumentID,
		arg.Interval,
		arg.GapFrom,
		arg.GapTo,
		arg.RetryAfter,
	)
	return err
}

const summarizeCandleHistory = `-- name: SummarizeCandleHistory :many
SELECT selected.instrument_id::bigint AS instrument_id,
       history.candle_count::int AS candle_count,
       history.oldest_open_time::timestamptz AS oldest_open_time,
       history.latest_open_time::timestamptz AS latest_open_time,
       history.gap_from::timestamptz AS gap_from,
       history.open_time::timestamptz AS gap_to,
       empty_gap.retry_after::timestamptz AS gap_retry_after
FROM unnest($1::bigint[]) AS selected(instrument_id)
CROSS JOIN LATERAL (
    SELECT bounded.open_time, bounded.previous_open_time, bounded.candle_count,
           bounded.oldest_open_time, bounded.latest_open_time,
           ((bounded.previous_open_time AT TIME ZONE 'UTC') + $2::interval) AT TIME ZONE 'UTC' AS gap_from
    FROM (
        SELECT recent.open_time,
               lag(recent.open_time) OVER (ORDER BY recent.open_time) AS previous_open_time,
               count(*) OVER () AS candle_count,
               min(recent.open_time) OVER () AS oldest_open_time,
               max(recent.open_time) OVER () AS latest_open_time
        FROM (
            SELECT candle.open_time
            FROM binance_spot.candles AS candle
            WHERE candle.instrument_id = selected.instrument_id
              AND candle.interval = $3
            ORDER BY candle.open_time DESC
            LIMIT $4
        ) AS recent
    ) AS bounded
) AS history
LEFT JOIN binance_spot.empty_candle_gaps AS empty_gap
    ON empty_gap.instrument_id = selected.instrument_id
   AND empty_gap.interval = $3
   AND empty_gap.gap_from = history.gap_from
   AND empty_gap.gap_to = history.open_time
WHERE history.previous_open_time IS NULL
   OR history.open_time > history.gap_from
ORDER BY 1, history.open_time
`

type SummarizeCandleHistoryParams struct {
	InstrumentIds []int64
	Step          pgtype.Interval
	Interval      string
	RowLimit      int32
}

type SummarizeCandleHistoryRow struct {
	InstrumentID   int64
	CandleCount    int32
	OldestOpenTime pgtype.Timestamptz
	LatestOpenTime pgtype.Timestamptz
	GapFrom        pgtype.Timestamptz
	GapTo          pgtype.Timestamptz
	GapRetryAfter  pgtype.Timestamptz
}

// Walks the latest row_limit candles per instrument once, on the primary key
// index. Every returned row carries the count and time bounds of those
// candles; the oldest one has no gap, and every other returned row is a
// candle that follows a gap of more than one interval step (calendar-aware in
// UTC), with the retry time of a gap verified empty. Instruments without
// candles are omitted.
func (q *Queries) SummarizeCandleHistory(ctx context.Context, arg SummarizeCandleHistoryParams) ([]SummarizeCandleHistoryRow, error) {
	rows, err := q.db.Query(ctx, summarizeCandleHistory,
		arg.InstrumentIds,
		arg.Step,
		arg.Interval,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SummarizeCandleHistoryRow
	for rows.Next() {
		var i SummarizeCandleHistoryRow
		if err := rows.Scan(
			&i.InstrumentID,
			&i.CandleCount,
			&i.OldestOpenTime,
			&i.LatestOpenTime,
			&i.GapFrom,
			&i.GapTo,
			&i.GapRetryAfter,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
