// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: favorites.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addFavorite = `-- name: AddFavorite :exec
INSERT INTO app.favorites (user_id, instrument_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddFavoriteParams struct {
	UserID       int64
	InstrumentID int64
}

func (q *Queries) AddFavorite(ctx context.Context, arg AddFavoriteParams) error {
	_, err := q.db.Exec(ctx, addFavorite, arg.UserID, arg.InstrumentID)
	return err
}

const countFavoriteAlerts = `-- name: CountFavoriteAlerts :one
SELECT count(*) FROM app.price_alerts WHERE user_id = $1 AND instrument_id = $2
`

type CountFavoriteAlertsParams struct {
	UserID       int64
	InstrumentID int64
}

func (q *Queries) CountFavoriteAlerts(ctx context.Context, arg CountFavoriteAlertsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countFavoriteAlerts, arg.UserID, arg.InstrumentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteFavorite = `-- name: DeleteFavorite :execrows
DELETE FROM app.favorites WHERE user_id = $1 AND instrument_id = $2
`

type DeleteFavoriteParams struct {
	UserID       int64
	InstrumentID int64
}

func (q *Queries) DeleteFavorite(ctx context.Context, arg DeleteFavoriteParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteFavorite, arg.UserID, arg.InstrumentID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getFavorite = `-- name: GetFavorite :one
SELECT i.id AS instrument_id, i.symbol, i.base_asset, i.quote_asset,
       i.is_active, f.created_at,
       count(a.id)::int AS alert_count
FROM app.favorites f
JOIN binance_spot.instruments i ON i.id = f.instrument_id
LEFT JOIN app.price_alerts a ON a.user_id = f.user_id AND a.instrument_id = f.instrument_id
WHERE f.user_id = $1 AND i.symbol = $2
GROUP BY i.id, i.symbol, i.base_asset, i.quote_asset, i.exchange_status, i.is_active, f.created_at
`

type GetFavoriteParams struct {
	UserID int64
	Symbol string
}

type GetFavoriteRow struct {
	InstrumentID int64
	Symbol       string
	BaseAsset    string
	QuoteAsset   string
	IsActive     bool
	CreatedAt    pgtype.Timestamptz
	AlertCount   int32
}

func (q *Queries) GetFavorite(ctx context.Context, arg GetFavoriteParams) (GetFavoriteRow, error) {
	row := q.db.QueryRow(ctx, getFavorite, arg.UserID, arg.Symbol)
	var i GetFavoriteRow
	err := row.Scan(
		&i.InstrumentID,
		&i.Symbol,
		&i.BaseAsset,
		&i.QuoteAsset,
		&i.IsActive,
		&i.CreatedAt,
		&i.AlertCount,
	)
	return i, err
}

const listFavoriteSymbols = `-- name: ListFavoriteSymbols :many
SELECT i.symbol
FROM app.favorites f
JOIN binance_spot.instruments i ON i.id = f.instrument_id
WHERE f.user_id = $1 AND i.is_active
ORDER BY i.symbol
`

func (q *Queries) ListFavoriteSymbols(ctx context.Context, userID int64) ([]string, error) {
	rows, err := q.db.Query(ctx, listFavoriteSymbols, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var symbol string
		if err := rows.Scan(&symbol); err != nil {
			return nil, err
		}
		items = append(items, symbol)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFavorites = `-- name: ListFavorites :many
SELECT i.id AS instrument_id, i.symbol, i.base_asset, i.quote_asset,
       i.is_active, f.created_at,
       count(a.id)::int AS alert_count
FROM app.favorites f
JOIN binance_spot.instruments i ON i.id = f.instrument_id
LEFT JOIN app.price_alerts a ON a.user_id = f.user_id AND a.instrument_id = f.instrument_id
WHERE f.user_id = $1
GROUP BY i.id, i.symbol, i.base_asset, i.quote_asset, i.exchange_status, i.is_active, f.created_at
ORDER BY f.created_at DESC, i.symbol
`

type ListFavoritesRow struct {
	InstrumentID int64
	Symbol       string
	BaseAsset    string
	QuoteAsset   string
	IsActive     bool
	CreatedAt    pgtype.Timestamptz
	AlertCount   int32
}

func (q *Queries) ListFavorites(ctx context.Context, userID int64) ([]ListFavoritesRow, error) {
	rows, err := q.db.Query(ctx, listFavorites, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFavoritesRow
	for rows.Next() {
		var i ListFavoritesRow
		if err := rows.Scan(
			&i.InstrumentID,
			&i.Symbol,
			&i.BaseAsset,
			&i.QuoteAsset,
			&i.IsActive,
			&i.CreatedAt,
			&i.AlertCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMonitoredSymbols = `-- name: ListMonitoredSymbols :many
SELECT DISTINCT i.symbol
FROM app.favorites f
JOIN app.users u ON u.id = f.user_id AND u.is_enabled
JOIN binance_spot.instruments i ON i.id = f.instrument_id AND i.is_active
ORDER BY i.symbol
`

func (q *Queries) ListMonitoredSymbols(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listMonitoredSymbols)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var symbol string
		if err := rows.Scan(&symbol); err != nil {
			return nil, err
		}
		items = append(items, symbol)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
