// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: instruments.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deactivateInstrumentsExcept = `-- name: DeactivateInstrumentsExcept :exec
UPDATE binance_spot.instruments SET is_active = FALSE, deactivated_at = now()
WHERE is_active AND symbol <> ALL($1::text[])
`

func (q *Queries) DeactivateInstrumentsExcept(ctx context.Context, symbols []string) error {
	_, err := q.db.Exec(ctx, deactivateInstrumentsExcept, symbols)
	return err
}

const deleteDelistedInstrumentCandles = `-- name: DeleteDelistedInstrumentCandles :execrows
DELETE FROM binance_spot.candles
WHERE instrument_id = ANY($1::bigint[])
`

func (q *Queries) DeleteDelistedInstrumentCandles(ctx context.Context, instrumentIds []int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDelistedInstrumentCandles, instrumentIds)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteDelistedInstruments = `-- name: DeleteDelistedInstruments :many
DELETE FROM binance_spot.instruments AS instrument
WHERE instrument.id = ANY($1::bigint[])
RETURNING instrument.symbol
`

// Their candles must already be deleted; history coverage cascades.
func (q *Queries) DeleteDelistedInstruments(ctx context.Context, instrumentIds []int64) ([]string, error) {
	rows, err := q.db.Query(ctx, deleteDelistedInstruments, instrumentIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var symbol string
		if err := rows.Scan(&symbol); err != nil {
			return nil, err
		}
		items = append(items, symbol)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getActiveInstrumentBySymbol = `-- name: GetActiveInstrumentBySymbol :one
SELECT instrument.id, instrument.symbol, instrument.base_asset, instrument.quote_asset, instrument.exchange_status, instrument.is_active, instrument.deactivated_at
FROM binance_spot.instruments AS instrument
WHERE instrument.symbol = $1 AND instrument.is_active = TRUE
`

type GetActiveInstrumentBySymbolRow struct {
	BinanceSpotInstrument BinanceSpotInstrument
}

func (q *Queries) GetActiveInstrumentBySymbol(ctx context.Context, symbol string) (GetActiveInstrumentBySymbolRow, error) {
	row := q.db.QueryRow(ctx, getActiveInstrumentBySymbol, symbol)
	var i GetActiveInstrumentBySymbolRow
	err := row.Scan(
		&i.BinanceSpotInstrument.ID,
		&i.BinanceSpotInstrument.Symbol,
		&i.BinanceSpotInstrument.BaseAsset,
		&i.BinanceSpotInstrument.QuoteAsset,
		&i.BinanceSpotInstrument.ExchangeStatus,
		&i.BinanceSpotInstrument.IsActive,
		&i.BinanceSpotInstrument.DeactivatedAt,
	)
	return i, err
}

const listActiveInstruments = `-- name: ListActiveInstruments :many
SELECT instrument.id, instrument.symbol, instrument.base_asset, instrument.quote_asset, instrument.exchange_status, instrument.is_active, instrument.deactivated_at
FROM binance_spot.instruments AS instrument
WHERE instrument.is_active = TRUE
`

type ListActiveInstrumentsRow struct {
	BinanceSpotInstrument BinanceSpotInstrument
}

func (q *Queries) ListActiveInstruments(ctx context.Context) ([]ListActiveInstrumentsRow, error) {
	rows, err := q.db.Query(ctx, listActiveInstruments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveInstrumentsRow
	for rows.Next() {
		var i ListActiveInstrumentsRow
		if err := rows.Scan(
			&i.BinanceSpotInstrument.ID,
			&i.BinanceSpotInstrument.Symbol,
			&i.BinanceSpotInstrument.BaseAsset,
			&i.BinanceSpotInstrument.QuoteAsset,
			&i.BinanceSpotInstrument.ExchangeStatus,
			&i.BinanceSpotInstrument.IsActive,
			&i.BinanceSpotInstrument.DeactivatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDelistedInstrumentIDs = `-- name: ListDelistedInstrumentIDs :many
SELECT instrument.id
FROM binance_spot.instruments AS instrument
WHERE NOT instrument.is_active
  AND instrument.deactivated_at < $1
  AND NOT EXISTS (SELECT 1 FROM app.favorites AS favorite WHERE favorite.instrument_id = instrument.id)
FOR UPDATE
`

// Locks instruments inactive since before inactive_before that nobody has
// favorited, so a concurrent snapshot cannot reactivate them mid-deletion.
func (q *Queries) ListDelistedInstrumentIDs(ctx context.Context, inactiveBefore pgtype.Timestamptz) ([]int64, error) {
	rows, err := q.db.Query(ctx, listDelistedInstrumentIDs, inactiveBefore)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectActiveInstruments = `-- name: SelectActiveInstruments :many
SELECT instrument.id, instrument.symbol, instrument.base_asset, instrument.quote_asset, instrument.exchange_status, instrument.is_active, instrument.deactivated_at,
       (market_cap.coin_id IS NOT NULL)::boolean AS market_cap_available,
       COALESCE(market_cap.market_cap_usd::text, ''::text)::text AS market_cap_usd
FROM binance_spot.instruments AS instrument
LEFT JOIN app.coingecko_asset_mappings AS mapping
  ON mapping.base_asset = instrument.base_asset
 AND mapping.status = 'resolved'
LEFT JOIN app.coingecko_market_caps AS market_cap
  ON market_cap.coin_id = mapping.coin_id
WHERE instrument.is_active = TRUE
  AND ($1::text = '' OR instrument.symbol = $1::text)
  AND (COALESCE(cardinality($2::text[]), 0) = 0 OR instrument.symbol = ANY($2::text[]))
  AND (NOT $3::boolean OR COALESCE(mapping.is_stablecoin, FALSE) = FALSE)
  AND ($4::numeric IS NULL OR market_cap.market_cap_usd >= $4::numeric)
ORDER BY
  CASE WHEN $5::text = 'asc' THEN market_cap.market_cap_usd END ASC NULLS LAST,
  CASE WHEN $5::text = 'desc' THEN market_cap.market_cap_usd END DESC NULLS LAST,
  CASE WHEN $5::text <> '' THEN instrument.symbol END ASC
LIMIT NULLIF($6::int, 0)
`

type SelectActiveInstrumentsParams struct {
	Symbol              string
	Symbols             []string
	ExcludeStablecoins  bool
	MinimumMarketCapUsd pgtype.Numeric
	MarketCapSort       string
	ResultLimit         int32
}

type SelectActiveInstrumentsRow struct {
	BinanceSpotInstrument BinanceSpotInstrument
	MarketCapAvailable    bool
	MarketCapUsd          string
}

func (q *Queries) SelectActiveInstruments(ctx context.Context, arg SelectActiveInstrumentsParams) ([]SelectActiveInstrumentsRow, error) {
	rows, err := q.db.Query(ctx, selectActiveInstruments,
		arg.Symbol,
		arg.Symbols,
		arg.ExcludeStablecoins,
		arg.MinimumMarketCapUsd,
		arg.MarketCapSort,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SelectActiveInstrumentsRow
	for rows.Next() {
		var i SelectActiveInstrumentsRow
		if err := rows.Scan(
			&i.BinanceSpotInstrument.ID,
			&i.BinanceSpotInstrument.Symbol,
			&i.BinanceSpotInstrument.BaseAsset,
			&i.BinanceSpotInstrument.QuoteAsset,
			&i.BinanceSpotInstrument.ExchangeStatus,
			&i.BinanceSpotInstrument.IsActive,
			&i.BinanceSpotInstrument.DeactivatedAt,
			&i.MarketCapAvailable,
			&i.MarketCapUsd,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertInstruments = `-- name: UpsertInstruments :exec
INSERT INTO binance_spot.instruments (
    symbol, base_asset, quote_asset, exchange_status, is_active, deactivated_at
)
SELECT snapshot.symbol, snapshot.base_asset, snapshot.quote_asset, snapshot.exchange_status, snapshot.is_active,
       CASE WHEN snapshot.is_active THEN NULL ELSE now() END
FROM (
    SELECT unnest($1::text[]) AS symbol, unnest($2::text[]) AS base_asset,
           unnest($3::text[]) AS quote_asset, unnest($4::text[]) AS exchange_status,
           unnest($5::boolean[]) AS is_active
) AS snapshot
ON CONFLICT (symbol) DO UPDATE SET
    base_asset = EXCLUDED.base_asset,
    quote_asset = EXCLUDED.quote_asset,
    exchange_status = EXCLUDED.exchange_status,
    is_active = EXCLUDED.is_active,
    -- Keep the first deactivation time while an instrument stays inactive.
    deactivated_at = CASE
        WHEN EXCLUDED.is_active THEN NULL
        ELSE COALESCE(binance_spot.instruments.deactivated_at, now())
    END
WHERE (binance_spot.instruments.base_asset, binance_spot.instruments.quote_asset,
       binance_spot.instruments.exchange_status, binance_spot.instruments.is_active)
  IS DISTINCT FROM (EXCLUDED.base_asset, EXCLUDED.quote_asset, EXCLUDED.exchange_status, EXCLUDED.is_active)
`

type UpsertInstrumentsParams struct {
	Symbols     []string
	BaseAssets  []string
	QuoteAssets []string
	Statuses    []string
	Actives     []bool
}

// Rows whose values are unchanged are not rewritten.
func (q *Queries) UpsertInstruments(ctx context.Context, arg UpsertInstrumentsParams) error {
	_, err := q.db.Exec(ctx, upsertInstruments,
		arg.Symbols,
		arg.BaseAssets,
		arg.QuoteAssets,
		arg.Statuses,
		arg.Actives,
	)
	return err
}
