// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: instruments.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deactivateAllInstruments = `-- name: DeactivateAllInstruments :exec
UPDATE binance_spot.instruments SET is_active = FALSE
`

func (q *Queries) DeactivateAllInstruments(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deactivateAllInstruments)
	return err
}

const getActiveInstrumentBySymbol = `-- name: GetActiveInstrumentBySymbol :one
SELECT id, symbol, base_asset, quote_asset, exchange_status, is_active
FROM binance_spot.instruments
WHERE symbol = $1 AND is_active = TRUE
`

func (q *Queries) GetActiveInstrumentBySymbol(ctx context.Context, symbol string) (BinanceSpotInstrument, error) {
	row := q.db.QueryRow(ctx, getActiveInstrumentBySymbol, symbol)
	var i BinanceSpotInstrument
	err := row.Scan(
		&i.ID,
		&i.Symbol,
		&i.BaseAsset,
		&i.QuoteAsset,
		&i.ExchangeStatus,
		&i.IsActive,
	)
	return i, err
}

const listActiveInstruments = `-- name: ListActiveInstruments :many
SELECT id, symbol, base_asset, quote_asset, exchange_status, is_active
FROM binance_spot.instruments
WHERE is_active = TRUE
`

func (q *Queries) ListActiveInstruments(ctx context.Context) ([]BinanceSpotInstrument, error) {
	rows, err := q.db.Query(ctx, listActiveInstruments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BinanceSpotInstrument
	for rows.Next() {
		var i BinanceSpotInstrument
		if err := rows.Scan(
			&i.ID,
			&i.Symbol,
			&i.BaseAsset,
			&i.QuoteAsset,
			&i.ExchangeStatus,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectActiveInstruments = `-- name: SelectActiveInstruments :many
SELECT instrument.id, instrument.symbol, instrument.base_asset, instrument.quote_asset,
       instrument.exchange_status, instrument.is_active,
       market_cap.coin_id IS NOT NULL AS market_cap_available,
       COALESCE(market_cap.market_cap_usd::text, ''::text) AS market_cap_usd
FROM binance_spot.instruments AS instrument
LEFT JOIN app.coingecko_asset_mappings AS mapping
  ON mapping.base_asset = instrument.base_asset
 AND mapping.status = 'resolved'
LEFT JOIN app.coingecko_market_caps AS market_cap
  ON market_cap.coin_id = mapping.coin_id
WHERE instrument.is_active = TRUE
  AND ($1::text = '' OR instrument.symbol = $1::text)
  AND (NOT $2::boolean OR COALESCE(mapping.is_stablecoin, FALSE) = FALSE)
  AND ($3::numeric IS NULL OR market_cap.market_cap_usd >= $3::numeric)
ORDER BY
  CASE WHEN $4::text = 'asc' THEN market_cap.market_cap_usd END ASC NULLS LAST,
  CASE WHEN $4::text = 'desc' THEN market_cap.market_cap_usd END DESC NULLS LAST,
  CASE WHEN $4::text <> '' THEN instrument.symbol END ASC
LIMIT NULLIF($5::int, 0)
`

type SelectActiveInstrumentsParams struct {
	Symbol              string
	ExcludeStablecoins  bool
	MinimumMarketCapUsd pgtype.Numeric
	MarketCapSort       string
	ResultLimit         int32
}

type SelectActiveInstrumentsRow struct {
	ID                 int64
	Symbol             string
	BaseAsset          string
	QuoteAsset         string
	ExchangeStatus     string
	IsActive           bool
	MarketCapAvailable interface{}
	MarketCapUsd       interface{}
}

func (q *Queries) SelectActiveInstruments(ctx context.Context, arg SelectActiveInstrumentsParams) ([]SelectActiveInstrumentsRow, error) {
	rows, err := q.db.Query(ctx, selectActiveInstruments,
		arg.Symbol,
		arg.ExcludeStablecoins,
		arg.MinimumMarketCapUsd,
		arg.MarketCapSort,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SelectActiveInstrumentsRow
	for rows.Next() {
		var i SelectActiveInstrumentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Symbol,
			&i.BaseAsset,
			&i.QuoteAsset,
			&i.ExchangeStatus,
			&i.IsActive,
			&i.MarketCapAvailable,
			&i.MarketCapUsd,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertInstrument = `-- name: UpsertInstrument :one
INSERT INTO binance_spot.instruments (
    symbol, base_asset, quote_asset, exchange_status, is_active
) VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (symbol) DO UPDATE SET
    base_asset = EXCLUDED.base_asset,
    quote_asset = EXCLUDED.quote_asset,
    exchange_status = EXCLUDED.exchange_status,
    is_active = EXCLUDED.is_active
RETURNING id, symbol, base_asset, quote_asset, exchange_status, is_active
`

type UpsertInstrumentParams struct {
	Symbol         string
	BaseAsset      string
	QuoteAsset     string
	ExchangeStatus string
	IsActive       bool
}

func (q *Queries) UpsertInstrument(ctx context.Context, arg UpsertInstrumentParams) (BinanceSpotInstrument, error) {
	row := q.db.QueryRow(ctx, upsertInstrument,
		arg.Symbol,
		arg.BaseAsset,
		arg.QuoteAsset,
		arg.ExchangeStatus,
		arg.IsActive,
	)
	var i BinanceSpotInstrument
	err := row.Scan(
		&i.ID,
		&i.Symbol,
		&i.BaseAsset,
		&i.QuoteAsset,
		&i.ExchangeStatus,
		&i.IsActive,
	)
	return i, err
}
