// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: instruments.sql

package sqlc

import (
	"context"
)

const deactivateAllInstruments = `-- name: DeactivateAllInstruments :exec
UPDATE binance_spot.instruments SET is_active = FALSE
`

func (q *Queries) DeactivateAllInstruments(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deactivateAllInstruments)
	return err
}

const listActiveInstruments = `-- name: ListActiveInstruments :many
SELECT id, symbol, base_asset, quote_asset, exchange_status, is_active
FROM binance_spot.instruments
WHERE is_active = TRUE
`

func (q *Queries) ListActiveInstruments(ctx context.Context) ([]BinanceSpotInstrument, error) {
	rows, err := q.db.Query(ctx, listActiveInstruments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BinanceSpotInstrument
	for rows.Next() {
		var i BinanceSpotInstrument
		if err := rows.Scan(
			&i.ID,
			&i.Symbol,
			&i.BaseAsset,
			&i.QuoteAsset,
			&i.ExchangeStatus,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveInstrumentsLimited = `-- name: ListActiveInstrumentsLimited :many
SELECT id, symbol, base_asset, quote_asset, exchange_status, is_active
FROM binance_spot.instruments
WHERE is_active = TRUE
LIMIT NULLIF($1::int, 0)
`

func (q *Queries) ListActiveInstrumentsLimited(ctx context.Context, resultLimit int32) ([]BinanceSpotInstrument, error) {
	rows, err := q.db.Query(ctx, listActiveInstrumentsLimited, resultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BinanceSpotInstrument
	for rows.Next() {
		var i BinanceSpotInstrument
		if err := rows.Scan(
			&i.ID,
			&i.Symbol,
			&i.BaseAsset,
			&i.QuoteAsset,
			&i.ExchangeStatus,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveInstrumentsSortedByMarketCap = `-- name: ListActiveInstrumentsSortedByMarketCap :many
SELECT instrument.id, instrument.symbol, instrument.base_asset, instrument.quote_asset,
       instrument.exchange_status, instrument.is_active
FROM binance_spot.instruments AS instrument
JOIN app.coingecko_asset_mappings AS mapping
  ON mapping.base_asset = instrument.base_asset
 AND mapping.status = 'resolved'
JOIN app.coingecko_market_caps AS market_cap
  ON market_cap.coin_id = mapping.coin_id
WHERE instrument.is_active = TRUE
ORDER BY
  CASE WHEN $1::text = 'asc' THEN market_cap.market_cap_usd END ASC,
  CASE WHEN $1::text = 'desc' THEN market_cap.market_cap_usd END DESC,
  instrument.symbol ASC
LIMIT NULLIF($2::int, 0)
`

type ListActiveInstrumentsSortedByMarketCapParams struct {
	SortDirection string
	ResultLimit   int32
}

func (q *Queries) ListActiveInstrumentsSortedByMarketCap(ctx context.Context, arg ListActiveInstrumentsSortedByMarketCapParams) ([]BinanceSpotInstrument, error) {
	rows, err := q.db.Query(ctx, listActiveInstrumentsSortedByMarketCap, arg.SortDirection, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BinanceSpotInstrument
	for rows.Next() {
		var i BinanceSpotInstrument
		if err := rows.Scan(
			&i.ID,
			&i.Symbol,
			&i.BaseAsset,
			&i.QuoteAsset,
			&i.ExchangeStatus,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertInstrument = `-- name: UpsertInstrument :one
INSERT INTO binance_spot.instruments (
    symbol, base_asset, quote_asset, exchange_status, is_active
) VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (symbol) DO UPDATE SET
    base_asset = EXCLUDED.base_asset,
    quote_asset = EXCLUDED.quote_asset,
    exchange_status = EXCLUDED.exchange_status,
    is_active = EXCLUDED.is_active
RETURNING id, symbol, base_asset, quote_asset, exchange_status, is_active
`

type UpsertInstrumentParams struct {
	Symbol         string
	BaseAsset      string
	QuoteAsset     string
	ExchangeStatus string
	IsActive       bool
}

func (q *Queries) UpsertInstrument(ctx context.Context, arg UpsertInstrumentParams) (BinanceSpotInstrument, error) {
	row := q.db.QueryRow(ctx, upsertInstrument,
		arg.Symbol,
		arg.BaseAsset,
		arg.QuoteAsset,
		arg.ExchangeStatus,
		arg.IsActive,
	)
	var i BinanceSpotInstrument
	err := row.Scan(
		&i.ID,
		&i.Symbol,
		&i.BaseAsset,
		&i.QuoteAsset,
		&i.ExchangeStatus,
		&i.IsActive,
	)
	return i, err
}
