// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: market_cap.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearMappings = `-- name: ClearMappings :exec
DELETE FROM app.coingecko_asset_mappings
`

func (q *Queries) ClearMappings(ctx context.Context) error {
	_, err := q.db.Exec(ctx, clearMappings)
	return err
}

const getCoinGeckoMapping = `-- name: GetCoinGeckoMapping :one
SELECT base_asset, coin_id, quote_asset, source_symbol, status, reason, observed_at, expires_at FROM app.coingecko_asset_mappings WHERE base_asset = $1
`

func (q *Queries) GetCoinGeckoMapping(ctx context.Context, baseAsset string) (AppCoingeckoAssetMapping, error) {
	row := q.db.QueryRow(ctx, getCoinGeckoMapping, baseAsset)
	var i AppCoingeckoAssetMapping
	err := row.Scan(
		&i.BaseAsset,
		&i.CoinID,
		&i.QuoteAsset,
		&i.SourceSymbol,
		&i.Status,
		&i.Reason,
		&i.ObservedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getCoinGeckoMarketCap = `-- name: GetCoinGeckoMarketCap :one
SELECT coin_id, market_cap_usd, fetched_at, observed_at FROM app.coingecko_market_caps WHERE coin_id = $1
`

func (q *Queries) GetCoinGeckoMarketCap(ctx context.Context, coinID string) (AppCoingeckoMarketCap, error) {
	row := q.db.QueryRow(ctx, getCoinGeckoMarketCap, coinID)
	var i AppCoingeckoMarketCap
	err := row.Scan(
		&i.CoinID,
		&i.MarketCapUsd,
		&i.FetchedAt,
		&i.ObservedAt,
	)
	return i, err
}

const mappingBootstrapCompleted = `-- name: MappingBootstrapCompleted :one
SELECT completed_at IS NOT NULL FROM app.coingecko_mapping_bootstrap WHERE id = TRUE
`

func (q *Queries) MappingBootstrapCompleted(ctx context.Context) (interface{}, error) {
	row := q.db.QueryRow(ctx, mappingBootstrapCompleted)
	var column_1 interface{}
	err := row.Scan(&column_1)
	return column_1, err
}

const replaceMappingsAndCompleteBootstrap = `-- name: ReplaceMappingsAndCompleteBootstrap :exec
UPDATE app.coingecko_mapping_bootstrap SET completed_at = now() WHERE id = TRUE
`

func (q *Queries) ReplaceMappingsAndCompleteBootstrap(ctx context.Context) error {
	_, err := q.db.Exec(ctx, replaceMappingsAndCompleteBootstrap)
	return err
}

const upsertCoinGeckoMapping = `-- name: UpsertCoinGeckoMapping :exec
INSERT INTO app.coingecko_asset_mappings (base_asset, coin_id, quote_asset, source_symbol, status, reason, observed_at, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (base_asset) DO UPDATE SET coin_id=EXCLUDED.coin_id, quote_asset=EXCLUDED.quote_asset, source_symbol=EXCLUDED.source_symbol, status=EXCLUDED.status, reason=EXCLUDED.reason, observed_at=EXCLUDED.observed_at, expires_at=EXCLUDED.expires_at
`

type UpsertCoinGeckoMappingParams struct {
	BaseAsset    string
	CoinID       pgtype.Text
	QuoteAsset   string
	SourceSymbol string
	Status       string
	Reason       pgtype.Text
	ObservedAt   pgtype.Timestamptz
	ExpiresAt    pgtype.Timestamptz
}

func (q *Queries) UpsertCoinGeckoMapping(ctx context.Context, arg UpsertCoinGeckoMappingParams) error {
	_, err := q.db.Exec(ctx, upsertCoinGeckoMapping,
		arg.BaseAsset,
		arg.CoinID,
		arg.QuoteAsset,
		arg.SourceSymbol,
		arg.Status,
		arg.Reason,
		arg.ObservedAt,
		arg.ExpiresAt,
	)
	return err
}

const upsertCoinGeckoMarketCap = `-- name: UpsertCoinGeckoMarketCap :exec
INSERT INTO app.coingecko_market_caps (coin_id, market_cap_usd, fetched_at, observed_at) VALUES ($1, $2, $3, $4)
ON CONFLICT (coin_id) DO UPDATE SET market_cap_usd=EXCLUDED.market_cap_usd, fetched_at=EXCLUDED.fetched_at, observed_at=EXCLUDED.observed_at
`

type UpsertCoinGeckoMarketCapParams struct {
	CoinID       string
	MarketCapUsd string
	FetchedAt    pgtype.Timestamptz
	ObservedAt   pgtype.Timestamptz
}

func (q *Queries) UpsertCoinGeckoMarketCap(ctx context.Context, arg UpsertCoinGeckoMarketCapParams) error {
	_, err := q.db.Exec(ctx, upsertCoinGeckoMarketCap,
		arg.CoinID,
		arg.MarketCapUsd,
		arg.FetchedAt,
		arg.ObservedAt,
	)
	return err
}
