// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AppCoingeckoAssetMapping struct {
	BaseAsset    string
	CoinID       pgtype.Text
	QuoteAsset   string
	SourceSymbol string
	Status       string
	Reason       pgtype.Text
	ObservedAt   pgtype.Timestamptz
	ExpiresAt    pgtype.Timestamptz
	IsStablecoin pgtype.Bool
}

type AppCoingeckoMappingBootstrap struct {
	ID          bool
	CompletedAt pgtype.Timestamptz
}

type AppCoingeckoMarketCap struct {
	CoinID       string
	MarketCapUsd string
	FetchedAt    pgtype.Timestamptz
	ObservedAt   pgtype.Timestamptz
}

type AppFavorite struct {
	UserID       int64
	InstrumentID int64
	CreatedAt    pgtype.Timestamptz
}

type AppPriceAlert struct {
	ID           int64
	UserID       int64
	InstrumentID int64
	Target       string
	Version      int64
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type AppScannerIndicator struct {
	ID            int64
	Interval      string
	IndicatorType string
	Parameters    []byte
	ShowInTable   bool
	ScaleMin      pgtype.Float8
	ScaleMax      pgtype.Float8
	ScaleLevels   []float64
	CreatedAt     pgtype.Timestamptz
	Position      int32
}

type AppSchemaMigration struct {
	Version                  int64
	AppliedAt                pgtype.Timestamptz
	AppSchemaCreated         bool
	BinanceSpotSchemaCreated bool
}

type AppUser struct {
	ID          int64
	TelegramID  int64
	Username    pgtype.Text
	DisplayName pgtype.Text
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type BinanceSpotCandle struct {
	InstrumentID     int64
	Interval         string
	OpenTime         pgtype.Timestamptz
	CloseTime        pgtype.Timestamptz
	Open             float64
	High             float64
	Low              float64
	Close            float64
	Volume           float64
	QuoteAssetVolume float64
	TradeCount       int64
}

type BinanceSpotCandleHistoryCoverage struct {
	InstrumentID           int64
	Interval               string
	VerifiedOldestOpenTime pgtype.Timestamptz
	TargetDepth            int32
	PolicyVersion          int32
	RetryAfter             pgtype.Timestamptz
}

type BinanceSpotInstrument struct {
	ID             int64
	Symbol         string
	BaseAsset      string
	QuoteAsset     string
	ExchangeStatus string
	IsActive       bool
	DeactivatedAt  pgtype.Timestamptz
}

type BinanceSpotSyncState struct {
	ProfileKey         string
	LastStartedAt      pgtype.Timestamptz
	LastSucceededAt    pgtype.Timestamptz
	LastClosedOpenTime pgtype.Timestamptz
	Status             string
	ErrorMessage       pgtype.Text
}

type MigrationV1SchemaOwnership struct {
	AppSchemaCreated         interface{}
	BinanceSpotSchemaCreated interface{}
}
