// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scanner_indicators.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteScannerIndicator = `-- name: DeleteScannerIndicator :execrows
DELETE FROM app.scanner_indicators WHERE id = $1
`

func (q *Queries) DeleteScannerIndicator(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteScannerIndicator, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteUnusedScannerIndicators = `-- name: DeleteUnusedScannerIndicators :many
DELETE FROM app.scanner_indicators AS indicators
WHERE NOT EXISTS (
        SELECT 1 FROM app.strategy_indicators AS used
        WHERE used.indicator_id = indicators.id
    )
RETURNING indicators.id
`

func (q *Queries) DeleteUnusedScannerIndicators(ctx context.Context) ([]int64, error) {
	rows, err := q.db.Query(ctx, deleteUnusedScannerIndicators)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertScannerIndicator = `-- name: InsertScannerIndicator :one
INSERT INTO app.scanner_indicators (interval, indicator_type, parameters, show_in_table, scale_min, scale_max, scale_levels, position)
SELECT $1, $2, $3, $4, $5, $6, $7, COALESCE(MAX(position) + 1, 0)::INTEGER
FROM app.scanner_indicators
RETURNING id
`

type InsertScannerIndicatorParams struct {
	Interval      string
	IndicatorType string
	Parameters    []byte
	ShowInTable   bool
	ScaleMin      pgtype.Float8
	ScaleMax      pgtype.Float8
	ScaleLevels   []float64
}

func (q *Queries) InsertScannerIndicator(ctx context.Context, arg InsertScannerIndicatorParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertScannerIndicator,
		arg.Interval,
		arg.IndicatorType,
		arg.Parameters,
		arg.ShowInTable,
		arg.ScaleMin,
		arg.ScaleMax,
		arg.ScaleLevels,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listScannerIndicators = `-- name: ListScannerIndicators :many
SELECT id, interval, indicator_type, parameters, show_in_table, scale_min, scale_max, scale_levels
FROM app.scanner_indicators
ORDER BY position, id
`

type ListScannerIndicatorsRow struct {
	ID            int64
	Interval      string
	IndicatorType string
	Parameters    []byte
	ShowInTable   bool
	ScaleMin      pgtype.Float8
	ScaleMax      pgtype.Float8
	ScaleLevels   []float64
}

func (q *Queries) ListScannerIndicators(ctx context.Context) ([]ListScannerIndicatorsRow, error) {
	rows, err := q.db.Query(ctx, listScannerIndicators)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListScannerIndicatorsRow
	for rows.Next() {
		var i ListScannerIndicatorsRow
		if err := rows.Scan(
			&i.ID,
			&i.Interval,
			&i.IndicatorType,
			&i.Parameters,
			&i.ShowInTable,
			&i.ScaleMin,
			&i.ScaleMax,
			&i.ScaleLevels,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reorderScannerIndicators = `-- name: ReorderScannerIndicators :execrows
UPDATE app.scanner_indicators AS indicators
SET position = (ordered.position - 1)::INTEGER
FROM unnest($1::BIGINT[]) WITH ORDINALITY AS ordered(id, position)
WHERE indicators.id = ordered.id
`

func (q *Queries) ReorderScannerIndicators(ctx context.Context, ids []int64) (int64, error) {
	result, err := q.db.Exec(ctx, reorderScannerIndicators, ids)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateScannerIndicator = `-- name: UpdateScannerIndicator :execrows
UPDATE app.scanner_indicators
SET show_in_table = $2, scale_min = $3, scale_max = $4, scale_levels = $5
WHERE id = $1
`

type UpdateScannerIndicatorParams struct {
	ID          int64
	ShowInTable bool
	ScaleMin    pgtype.Float8
	ScaleMax    pgtype.Float8
	ScaleLevels []float64
}

func (q *Queries) UpdateScannerIndicator(ctx context.Context, arg UpdateScannerIndicatorParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateScannerIndicator,
		arg.ID,
		arg.ShowInTable,
		arg.ScaleMin,
		arg.ScaleMax,
		arg.ScaleLevels,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
