// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :exec
WITH inserted AS (
    INSERT INTO app.sessions (token_hash, user_id, created_at, idle_expires_at, absolute_expires_at)
    VALUES ($3, $1, $4, $5, $6)
)
DELETE FROM app.sessions AS s
WHERE s.user_id = $1
  AND s.token_hash IN (
      SELECT older.token_hash
      FROM app.sessions AS older
      WHERE older.user_id = $1
      ORDER BY older.created_at DESC
      OFFSET $2::int
  )
`

type CreateSessionParams struct {
	UserID            int64
	KeepExisting      int32
	TokenHash         []byte
	CreatedAt         pgtype.Timestamptz
	IdleExpiresAt     pgtype.Timestamptz
	AbsoluteExpiresAt pgtype.Timestamptz
}

// The deletion sees the snapshot before the insert, so it keeps the newest
// keep_existing earlier sessions of the user next to the new one.
func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession,
		arg.UserID,
		arg.KeepExisting,
		arg.TokenHash,
		arg.CreatedAt,
		arg.IdleExpiresAt,
		arg.AbsoluteExpiresAt,
	)
	return err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :execrows
DELETE FROM app.sessions
WHERE idle_expires_at <= $1
`

// The table checks idle_expires_at <= absolute_expires_at, so the idle expiry
// alone finds every expired session.
func (q *Queries) DeleteExpiredSessions(ctx context.Context, idleExpiresAt pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredSessions, idleExpiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM app.sessions
WHERE token_hash = $1
`

func (q *Queries) DeleteSession(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.Exec(ctx, deleteSession, tokenHash)
	return err
}

const extendSession = `-- name: ExtendSession :exec
UPDATE app.sessions
SET idle_expires_at = $1
WHERE token_hash = $2 AND idle_expires_at <= $3
`

type ExtendSessionParams struct {
	IdleExpiresAt pgtype.Timestamptz
	TokenHash     []byte
	ExtendBefore  pgtype.Timestamptz
}

// The predicate keeps concurrent requests to one write per minimum extension
// and never moves the expiry back.
func (q *Queries) ExtendSession(ctx context.Context, arg ExtendSessionParams) error {
	_, err := q.db.Exec(ctx, extendSession, arg.IdleExpiresAt, arg.TokenHash, arg.ExtendBefore)
	return err
}

const findSession = `-- name: FindSession :one
SELECT u.id, u.telegram_id, u.username, u.display_name, u.created_at, u.updated_at, u.strategy_alerts, s.idle_expires_at, s.absolute_expires_at
FROM app.sessions AS s
JOIN app.users AS u ON u.id = s.user_id
WHERE s.token_hash = $1
`

type FindSessionRow struct {
	AppUser           AppUser
	IdleExpiresAt     pgtype.Timestamptz
	AbsoluteExpiresAt pgtype.Timestamptz
}

func (q *Queries) FindSession(ctx context.Context, tokenHash []byte) (FindSessionRow, error) {
	row := q.db.QueryRow(ctx, findSession, tokenHash)
	var i FindSessionRow
	err := row.Scan(
		&i.AppUser.ID,
		&i.AppUser.TelegramID,
		&i.AppUser.Username,
		&i.AppUser.DisplayName,
		&i.AppUser.CreatedAt,
		&i.AppUser.UpdatedAt,
		&i.AppUser.StrategyAlerts,
		&i.IdleExpiresAt,
		&i.AbsoluteExpiresAt,
	)
	return i, err
}
