// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: strategies.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const completeStrategyBaseline = `-- name: CompleteStrategyBaseline :execrows
UPDATE app.strategies
SET baseline_pending = FALSE
WHERE id = $1 AND enabled AND baseline_pending AND revision = $2
`

type CompleteStrategyBaselineParams struct {
	ID       int64
	Revision int64
}

// Locks the strategy while its states are replaced; nothing changes unless
// the evaluated revision still awaits its baseline.
func (q *Queries) CompleteStrategyBaseline(ctx context.Context, arg CompleteStrategyBaselineParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeStrategyBaseline, arg.ID, arg.Revision)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteAllStrategyStates = `-- name: DeleteAllStrategyStates :exec
DELETE FROM app.strategy_states WHERE strategy_id = $1
`

func (q *Queries) DeleteAllStrategyStates(ctx context.Context, strategyID int64) error {
	_, err := q.db.Exec(ctx, deleteAllStrategyStates, strategyID)
	return err
}

const deleteStrategy = `-- name: DeleteStrategy :execrows
DELETE FROM app.strategies WHERE id = $1
`

func (q *Queries) DeleteStrategy(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteStrategy, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteStrategyIndicators = `-- name: DeleteStrategyIndicators :exec
DELETE FROM app.strategy_indicators WHERE strategy_id = $1
`

func (q *Queries) DeleteStrategyIndicators(ctx context.Context, strategyID int64) error {
	_, err := q.db.Exec(ctx, deleteStrategyIndicators, strategyID)
	return err
}

const deleteStrategyStates = `-- name: DeleteStrategyStates :exec
DELETE FROM app.strategy_states
WHERE strategy_id = $1::BIGINT AND instrument_id = ANY($2::BIGINT[])
`

type DeleteStrategyStatesParams struct {
	StrategyID    int64
	InstrumentIds []int64
}

func (q *Queries) DeleteStrategyStates(ctx context.Context, arg DeleteStrategyStatesParams) error {
	_, err := q.db.Exec(ctx, deleteStrategyStates, arg.StrategyID, arg.InstrumentIds)
	return err
}

const deleteStrategySymbols = `-- name: DeleteStrategySymbols :exec
DELETE FROM app.strategy_symbols WHERE strategy_id = $1
`

func (q *Queries) DeleteStrategySymbols(ctx context.Context, strategyID int64) error {
	_, err := q.db.Exec(ctx, deleteStrategySymbols, strategyID)
	return err
}

const insertStrategy = `-- name: InsertStrategy :one
INSERT INTO app.strategies (name, expression, exit_expression, take_profit_expression, stop_loss_expression,
                            min_market_cap_usd, max_market_cap_usd, message, enabled, baseline_pending)
VALUES ($1, $2, $3, $4, $5,
        $6, $7, $8, $9, $9)
RETURNING id
`

type InsertStrategyParams struct {
	Name                 string
	Expression           string
	ExitExpression       string
	TakeProfitExpression string
	StopLossExpression   string
	MinMarketCapUsd      pgtype.Float8
	MaxMarketCapUsd      pgtype.Float8
	Message              string
	Enabled              bool
}

func (q *Queries) InsertStrategy(ctx context.Context, arg InsertStrategyParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertStrategy,
		arg.Name,
		arg.Expression,
		arg.ExitExpression,
		arg.TakeProfitExpression,
		arg.StopLossExpression,
		arg.MinMarketCapUsd,
		arg.MaxMarketCapUsd,
		arg.Message,
		arg.Enabled,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertStrategyIndicators = `-- name: InsertStrategyIndicators :exec
INSERT INTO app.strategy_indicators (strategy_id, indicator_id)
SELECT $1::BIGINT, indicator_id
FROM unnest($2::BIGINT[]) AS ids(indicator_id)
`

type InsertStrategyIndicatorsParams struct {
	StrategyID   int64
	IndicatorIds []int64
}

func (q *Queries) InsertStrategyIndicators(ctx context.Context, arg InsertStrategyIndicatorsParams) error {
	_, err := q.db.Exec(ctx, insertStrategyIndicators, arg.StrategyID, arg.IndicatorIds)
	return err
}

const insertStrategyStates = `-- name: InsertStrategyStates :exec
INSERT INTO app.strategy_states (strategy_id, instrument_id, open_time, entry)
SELECT $1::BIGINT, v.instrument_id, v.open_time, v.entry
FROM (
    SELECT unnest($2::BIGINT[]) AS instrument_id, unnest($3::TIMESTAMPTZ[]) AS open_time,
           unnest($4::BOOLEAN[]) AS entry
) AS v
`

type InsertStrategyStatesParams struct {
	StrategyID    int64
	InstrumentIds []int64
	OpenTimes     []pgtype.Timestamptz
	Entries       []bool
}

// Inserts the states of a baseline: no trades, only the entry values.
func (q *Queries) InsertStrategyStates(ctx context.Context, arg InsertStrategyStatesParams) error {
	_, err := q.db.Exec(ctx, insertStrategyStates,
		arg.StrategyID,
		arg.InstrumentIds,
		arg.OpenTimes,
		arg.Entries,
	)
	return err
}

const insertStrategySymbols = `-- name: InsertStrategySymbols :exec
INSERT INTO app.strategy_symbols (strategy_id, instrument_id)
SELECT $1::BIGINT, instrument_id
FROM unnest($2::BIGINT[]) AS ids(instrument_id)
`

type InsertStrategySymbolsParams struct {
	StrategyID    int64
	InstrumentIds []int64
}

func (q *Queries) InsertStrategySymbols(ctx context.Context, arg InsertStrategySymbolsParams) error {
	_, err := q.db.Exec(ctx, insertStrategySymbols, arg.StrategyID, arg.InstrumentIds)
	return err
}

const listStrategies = `-- name: ListStrategies :many
SELECT id, name, expression, exit_expression, take_profit_expression, stop_loss_expression,
       min_market_cap_usd, max_market_cap_usd, message, enabled, baseline_pending, revision
FROM app.strategies
ORDER BY id
`

type ListStrategiesRow struct {
	ID                   int64
	Name                 string
	Expression           string
	ExitExpression       string
	TakeProfitExpression string
	StopLossExpression   string
	MinMarketCapUsd      pgtype.Float8
	MaxMarketCapUsd      pgtype.Float8
	Message              string
	Enabled              bool
	BaselinePending      bool
	Revision             int64
}

func (q *Queries) ListStrategies(ctx context.Context) ([]ListStrategiesRow, error) {
	rows, err := q.db.Query(ctx, listStrategies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStrategiesRow
	for rows.Next() {
		var i ListStrategiesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Expression,
			&i.ExitExpression,
			&i.TakeProfitExpression,
			&i.StopLossExpression,
			&i.MinMarketCapUsd,
			&i.MaxMarketCapUsd,
			&i.Message,
			&i.Enabled,
			&i.BaselinePending,
			&i.Revision,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStrategiesReading = `-- name: ListStrategiesReading :many
SELECT i.symbol, s.name
FROM app.strategy_symbols ss
JOIN app.strategies s ON s.id = ss.strategy_id
JOIN binance_spot.instruments i ON i.id = ss.instrument_id AND i.is_active
WHERE ss.instrument_id = $1
ORDER BY s.name
`

type ListStrategiesReadingRow struct {
	Symbol string
	Name   string
}

// The strategies that read the active instrument through of; a delisted one
// leaves them unknown anyway. Runs after LockInstrument.
func (q *Queries) ListStrategiesReading(ctx context.Context, instrumentID int64) ([]ListStrategiesReadingRow, error) {
	rows, err := q.db.Query(ctx, listStrategiesReading, instrumentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStrategiesReadingRow
	for rows.Next() {
		var i ListStrategiesReadingRow
		if err := rows.Scan(&i.Symbol, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStrategyInstruments = `-- name: ListStrategyInstruments :many
SELECT i.id, i.symbol, COALESCE(market_cap.market_cap_usd > 0, FALSE)::BOOLEAN AS market_cap_known,
       COALESCE(market_cap.market_cap_usd, 0)::DOUBLE PRECISION AS market_cap_usd
FROM app.favorites f
JOIN app.users u ON u.id = f.user_id AND u.telegram_id = $1::BIGINT
JOIN binance_spot.instruments i ON i.id = f.instrument_id AND i.is_active
LEFT JOIN app.coingecko_asset_mappings mapping ON mapping.base_asset = i.base_asset AND mapping.status = 'resolved'
LEFT JOIN app.coingecko_market_caps market_cap ON market_cap.coin_id = mapping.coin_id
ORDER BY i.id
`

type ListStrategyInstrumentsRow struct {
	ID             int64
	Symbol         string
	MarketCapKnown bool
	MarketCapUsd   float64
}

// Strategies evaluate the active favorites of the administrator, with their
// market caps when known; CoinGecko reports 0 for coins without supply data.
func (q *Queries) ListStrategyInstruments(ctx context.Context, administratorTelegramID int64) ([]ListStrategyInstrumentsRow, error) {
	rows, err := q.db.Query(ctx, listStrategyInstruments, administratorTelegramID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStrategyInstrumentsRow
	for rows.Next() {
		var i ListStrategyInstrumentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Symbol,
			&i.MarketCapKnown,
			&i.MarketCapUsd,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStrategyInstrumentsAmong = `-- name: ListStrategyInstrumentsAmong :many
SELECT i.id
FROM app.favorites f
JOIN app.users u ON u.id = f.user_id AND u.telegram_id = $1::BIGINT
JOIN binance_spot.instruments i ON i.id = f.instrument_id AND i.is_active
WHERE i.id = ANY($2::BIGINT[])
`

type ListStrategyInstrumentsAmongParams struct {
	AdministratorTelegramID int64
	InstrumentIds           []int64
}

// Runs after LockStrategySymbols, so it sees favorites removed meanwhile.
func (q *Queries) ListStrategyInstrumentsAmong(ctx context.Context, arg ListStrategyInstrumentsAmongParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, listStrategyInstrumentsAmong, arg.AdministratorTelegramID, arg.InstrumentIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStrategyRecipients = `-- name: ListStrategyRecipients :many
SELECT telegram_id
FROM app.users
WHERE strategy_alerts OR telegram_id = $1::BIGINT
ORDER BY telegram_id
`

func (q *Queries) ListStrategyRecipients(ctx context.Context, administratorTelegramID int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, listStrategyRecipients, administratorTelegramID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var telegram_id int64
		if err := rows.Scan(&telegram_id); err != nil {
			return nil, err
		}
		items = append(items, telegram_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStrategyStates = `-- name: ListStrategyStates :many
SELECT strategy_id, instrument_id, open_time, entry, buys, filled, quantity, opened_at, take_profit, stop_loss
FROM app.strategy_states
ORDER BY strategy_id, instrument_id
`

func (q *Queries) ListStrategyStates(ctx context.Context) ([]AppStrategyState, error) {
	rows, err := q.db.Query(ctx, listStrategyStates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AppStrategyState
	for rows.Next() {
		var i AppStrategyState
		if err := rows.Scan(
			&i.StrategyID,
			&i.InstrumentID,
			&i.OpenTime,
			&i.Entry,
			&i.Buys,
			&i.Filled,
			&i.Quantity,
			&i.OpenedAt,
			&i.TakeProfit,
			&i.StopLoss,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStrategySymbolIDs = `-- name: ListStrategySymbolIDs :many
SELECT instrument_id FROM app.strategy_symbols WHERE strategy_id = $1
`

func (q *Queries) ListStrategySymbolIDs(ctx context.Context, strategyID int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, listStrategySymbolIDs, strategyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var instrument_id int64
		if err := rows.Scan(&instrument_id); err != nil {
			return nil, err
		}
		items = append(items, instrument_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockInstrument = `-- name: LockInstrument :exec
SELECT id FROM binance_spot.instruments WHERE id = $1 FOR NO KEY UPDATE
`

// Orders a favorite removal with strategy writes, which lock the instruments
// they read FOR SHARE. NO KEY UPDATE conflicts with that but not with the
// KEY SHARE locks of foreign key inserts, such as candles and favorites.
func (q *Queries) LockInstrument(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, lockInstrument, id)
	return err
}

const lockStrategySymbols = `-- name: LockStrategySymbols :many
SELECT id, symbol
FROM binance_spot.instruments
WHERE symbol = ANY($1::TEXT[])
ORDER BY id
FOR SHARE
`

type LockStrategySymbolsRow struct {
	ID     int64
	Symbol string
}

// Locks the instruments an expression reads through of against their
// removal from the administrator's favorites, then lists them.
func (q *Queries) LockStrategySymbols(ctx context.Context, symbols []string) ([]LockStrategySymbolsRow, error) {
	rows, err := q.db.Query(ctx, lockStrategySymbols, symbols)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LockStrategySymbolsRow
	for rows.Next() {
		var i LockStrategySymbolsRow
		if err := rows.Scan(&i.ID, &i.Symbol); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveStrategyStates = `-- name: SaveStrategyStates :many
INSERT INTO app.strategy_states (strategy_id, instrument_id, open_time, entry, buys, filled, quantity, opened_at, take_profit, stop_loss)
SELECT s.id, v.instrument_id, v.open_time, v.entry, v.buys, v.filled, v.quantity, v.opened_at, v.take_profit, v.stop_loss
FROM app.strategies s
CROSS JOIN (
    SELECT unnest($1::BIGINT[]) AS instrument_id, unnest($2::TIMESTAMPTZ[]) AS open_time,
           unnest($3::BOOLEAN[]) AS entry, unnest($4::INTEGER[]) AS buys,
           unnest($5::INTEGER[]) AS filled, unnest($6::DOUBLE PRECISION[]) AS quantity,
           unnest($7::TIMESTAMPTZ[]) AS opened_at, unnest($8::DOUBLE PRECISION[]) AS take_profit,
           unnest($9::DOUBLE PRECISION[]) AS stop_loss
) AS v
WHERE s.id = $10 AND s.enabled AND NOT s.baseline_pending AND s.revision = $11
FOR SHARE OF s
ON CONFLICT (strategy_id, instrument_id) DO UPDATE
SET open_time = EXCLUDED.open_time, entry = EXCLUDED.entry, buys = EXCLUDED.buys,
    filled = EXCLUDED.filled, quantity = EXCLUDED.quantity, opened_at = EXCLUDED.opened_at,
    take_profit = EXCLUDED.take_profit, stop_loss = EXCLUDED.stop_loss
WHERE app.strategy_states.open_time < EXCLUDED.open_time
RETURNING instrument_id
`

type SaveStrategyStatesParams struct {
	InstrumentIds []int64
	OpenTimes     []pgtype.Timestamptz
	Entries       []bool
	Buys          []int32
	Filled        []int32
	Quantities    []float64
	OpenedAt      []pgtype.Timestamptz
	TakeProfits   []float64
	StopLosses    []float64
	StrategyID    int64
	Revision      int64
}

// Stores states of later candles only while the evaluated revision is
// current and announced, and returns the instruments stored. The row lock
// orders it with a concurrent change.
func (q *Queries) SaveStrategyStates(ctx context.Context, arg SaveStrategyStatesParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, saveStrategyStates,
		arg.InstrumentIds,
		arg.OpenTimes,
		arg.Entries,
		arg.Buys,
		arg.Filled,
		arg.Quantities,
		arg.OpenedAt,
		arg.TakeProfits,
		arg.StopLosses,
		arg.StrategyID,
		arg.Revision,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var instrument_id int64
		if err := rows.Scan(&instrument_id); err != nil {
			return nil, err
		}
		items = append(items, instrument_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setStrategyEnabled = `-- name: SetStrategyEnabled :one
UPDATE app.strategies
SET enabled = $2, baseline_pending = $2, revision = revision + 1, updated_at = now()
WHERE id = $1
RETURNING revision
`

type SetStrategyEnabledParams struct {
	ID      int64
	Enabled bool
}

func (q *Queries) SetStrategyEnabled(ctx context.Context, arg SetStrategyEnabledParams) (int64, error) {
	row := q.db.QueryRow(ctx, setStrategyEnabled, arg.ID, arg.Enabled)
	var revision int64
	err := row.Scan(&revision)
	return revision, err
}

const updateStrategy = `-- name: UpdateStrategy :one
UPDATE app.strategies
SET name = $1, expression = $2, exit_expression = $3,
    take_profit_expression = $4, stop_loss_expression = $5,
    min_market_cap_usd = $6, max_market_cap_usd = $7,
    message = $8, updated_at = now(),
    baseline_pending = baseline_pending OR $9::BOOLEAN,
    revision = revision + (expression IS DISTINCT FROM $2
        OR exit_expression IS DISTINCT FROM $3
        OR take_profit_expression IS DISTINCT FROM $4
        OR stop_loss_expression IS DISTINCT FROM $5)::INTEGER
WHERE id = $10
RETURNING revision
`

type UpdateStrategyParams struct {
	Name                 string
	Expression           string
	ExitExpression       string
	TakeProfitExpression string
	StopLossExpression   string
	MinMarketCapUsd      pgtype.Float8
	MaxMarketCapUsd      pgtype.Float8
	Message              string
	Baseline             bool
	ID                   int64
}

// A change of how the strategy trades starts a new revision; a market cap
// range change only limits later buys.
func (q *Queries) UpdateStrategy(ctx context.Context, arg UpdateStrategyParams) (int64, error) {
	row := q.db.QueryRow(ctx, updateStrategy,
		arg.Name,
		arg.Expression,
		arg.ExitExpression,
		arg.TakeProfitExpression,
		arg.StopLossExpression,
		arg.MinMarketCapUsd,
		arg.MaxMarketCapUsd,
		arg.Message,
		arg.Baseline,
		arg.ID,
	)
	var revision int64
	err := row.Scan(&revision)
	return revision, err
}
