// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: strategies.sql

package sqlc

import (
	"context"
)

const addStrategyMatches = `-- name: AddStrategyMatches :many
INSERT INTO app.strategy_matches (strategy_id, instrument_id)
SELECT s.id, ids.instrument_id
FROM app.strategies s
CROSS JOIN unnest($1::BIGINT[]) AS ids(instrument_id)
WHERE s.id = $2 AND s.enabled AND NOT s.baseline_pending AND s.revision = $3
FOR SHARE OF s
ON CONFLICT DO NOTHING
RETURNING instrument_id
`

type AddStrategyMatchesParams struct {
	InstrumentIds []int64
	StrategyID    int64
	Revision      int64
}

// Adds matches only while the evaluated revision is current and announced,
// and returns the instruments that were not matching yet. The row lock
// orders it with a concurrent change.
func (q *Queries) AddStrategyMatches(ctx context.Context, arg AddStrategyMatchesParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, addStrategyMatches, arg.InstrumentIds, arg.StrategyID, arg.Revision)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var instrument_id int64
		if err := rows.Scan(&instrument_id); err != nil {
			return nil, err
		}
		items = append(items, instrument_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const completeStrategyBaseline = `-- name: CompleteStrategyBaseline :execrows
UPDATE app.strategies
SET baseline_pending = FALSE
WHERE id = $1 AND enabled AND baseline_pending AND revision = $2
`

type CompleteStrategyBaselineParams struct {
	ID       int64
	Revision int64
}

// Locks the strategy while its matches are replaced; nothing changes unless
// the evaluated revision still awaits its baseline.
func (q *Queries) CompleteStrategyBaseline(ctx context.Context, arg CompleteStrategyBaselineParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeStrategyBaseline, arg.ID, arg.Revision)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteAllStrategyMatches = `-- name: DeleteAllStrategyMatches :exec
DELETE FROM app.strategy_matches WHERE strategy_id = $1
`

func (q *Queries) DeleteAllStrategyMatches(ctx context.Context, strategyID int64) error {
	_, err := q.db.Exec(ctx, deleteAllStrategyMatches, strategyID)
	return err
}

const deleteStrategy = `-- name: DeleteStrategy :execrows
DELETE FROM app.strategies WHERE id = $1
`

func (q *Queries) DeleteStrategy(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteStrategy, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteStrategyIndicators = `-- name: DeleteStrategyIndicators :exec
DELETE FROM app.strategy_indicators WHERE strategy_id = $1
`

func (q *Queries) DeleteStrategyIndicators(ctx context.Context, strategyID int64) error {
	_, err := q.db.Exec(ctx, deleteStrategyIndicators, strategyID)
	return err
}

const deleteStrategyMatches = `-- name: DeleteStrategyMatches :exec
DELETE FROM app.strategy_matches
WHERE strategy_id = $1::BIGINT AND instrument_id = ANY($2::BIGINT[])
`

type DeleteStrategyMatchesParams struct {
	StrategyID    int64
	InstrumentIds []int64
}

func (q *Queries) DeleteStrategyMatches(ctx context.Context, arg DeleteStrategyMatchesParams) error {
	_, err := q.db.Exec(ctx, deleteStrategyMatches, arg.StrategyID, arg.InstrumentIds)
	return err
}

const insertStrategy = `-- name: InsertStrategy :one
INSERT INTO app.strategies (name, expression, enabled, baseline_pending)
VALUES ($1, $2, $3, $3)
RETURNING id
`

type InsertStrategyParams struct {
	Name       string
	Expression string
	Enabled    bool
}

func (q *Queries) InsertStrategy(ctx context.Context, arg InsertStrategyParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertStrategy, arg.Name, arg.Expression, arg.Enabled)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertStrategyIndicators = `-- name: InsertStrategyIndicators :exec
INSERT INTO app.strategy_indicators (strategy_id, indicator_id)
SELECT $1::BIGINT, indicator_id
FROM unnest($2::BIGINT[]) AS ids(indicator_id)
`

type InsertStrategyIndicatorsParams struct {
	StrategyID   int64
	IndicatorIds []int64
}

func (q *Queries) InsertStrategyIndicators(ctx context.Context, arg InsertStrategyIndicatorsParams) error {
	_, err := q.db.Exec(ctx, insertStrategyIndicators, arg.StrategyID, arg.IndicatorIds)
	return err
}

const insertStrategyMatches = `-- name: InsertStrategyMatches :exec
INSERT INTO app.strategy_matches (strategy_id, instrument_id)
SELECT $1::BIGINT, instrument_id
FROM unnest($2::BIGINT[]) AS ids(instrument_id)
ON CONFLICT DO NOTHING
`

type InsertStrategyMatchesParams struct {
	StrategyID    int64
	InstrumentIds []int64
}

func (q *Queries) InsertStrategyMatches(ctx context.Context, arg InsertStrategyMatchesParams) error {
	_, err := q.db.Exec(ctx, insertStrategyMatches, arg.StrategyID, arg.InstrumentIds)
	return err
}

const listMonitoredInstruments = `-- name: ListMonitoredInstruments :many
SELECT DISTINCT i.id, i.symbol
FROM app.favorites f
JOIN app.users u ON u.id = f.user_id
JOIN binance_spot.instruments i ON i.id = f.instrument_id AND i.is_active
ORDER BY i.id
`

type ListMonitoredInstrumentsRow struct {
	ID     int64
	Symbol string
}

func (q *Queries) ListMonitoredInstruments(ctx context.Context) ([]ListMonitoredInstrumentsRow, error) {
	rows, err := q.db.Query(ctx, listMonitoredInstruments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMonitoredInstrumentsRow
	for rows.Next() {
		var i ListMonitoredInstrumentsRow
		if err := rows.Scan(&i.ID, &i.Symbol); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStrategies = `-- name: ListStrategies :many
SELECT id, name, expression, enabled, baseline_pending, revision
FROM app.strategies
ORDER BY id
`

type ListStrategiesRow struct {
	ID              int64
	Name            string
	Expression      string
	Enabled         bool
	BaselinePending bool
	Revision        int64
}

func (q *Queries) ListStrategies(ctx context.Context) ([]ListStrategiesRow, error) {
	rows, err := q.db.Query(ctx, listStrategies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStrategiesRow
	for rows.Next() {
		var i ListStrategiesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Expression,
			&i.Enabled,
			&i.BaselinePending,
			&i.Revision,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStrategyMatches = `-- name: ListStrategyMatches :many
SELECT strategy_id, instrument_id
FROM app.strategy_matches
ORDER BY strategy_id, instrument_id
`

type ListStrategyMatchesRow struct {
	StrategyID   int64
	InstrumentID int64
}

func (q *Queries) ListStrategyMatches(ctx context.Context) ([]ListStrategyMatchesRow, error) {
	rows, err := q.db.Query(ctx, listStrategyMatches)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStrategyMatchesRow
	for rows.Next() {
		var i ListStrategyMatchesRow
		if err := rows.Scan(&i.StrategyID, &i.InstrumentID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStrategyRecipients = `-- name: ListStrategyRecipients :many
SELECT telegram_id
FROM app.users
WHERE strategy_alerts OR telegram_id = $1::BIGINT
ORDER BY telegram_id
`

func (q *Queries) ListStrategyRecipients(ctx context.Context, administratorTelegramID int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, listStrategyRecipients, administratorTelegramID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var telegram_id int64
		if err := rows.Scan(&telegram_id); err != nil {
			return nil, err
		}
		items = append(items, telegram_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setStrategyEnabled = `-- name: SetStrategyEnabled :one
UPDATE app.strategies
SET enabled = $2, baseline_pending = $2, revision = revision + 1, updated_at = now()
WHERE id = $1
RETURNING revision
`

type SetStrategyEnabledParams struct {
	ID      int64
	Enabled bool
}

func (q *Queries) SetStrategyEnabled(ctx context.Context, arg SetStrategyEnabledParams) (int64, error) {
	row := q.db.QueryRow(ctx, setStrategyEnabled, arg.ID, arg.Enabled)
	var revision int64
	err := row.Scan(&revision)
	return revision, err
}

const updateStrategy = `-- name: UpdateStrategy :one
UPDATE app.strategies
SET name = $1, expression = $2, updated_at = now(),
    baseline_pending = baseline_pending OR $3::BOOLEAN,
    revision = revision + (expression IS DISTINCT FROM $2)::INTEGER
WHERE id = $4
RETURNING revision
`

type UpdateStrategyParams struct {
	Name       string
	Expression string
	Baseline   bool
	ID         int64
}

func (q *Queries) UpdateStrategy(ctx context.Context, arg UpdateStrategyParams) (int64, error) {
	row := q.db.QueryRow(ctx, updateStrategy,
		arg.Name,
		arg.Expression,
		arg.Baseline,
		arg.ID,
	)
	var revision int64
	err := row.Scan(&revision)
	return revision, err
}
