// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sync_state.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getSyncState = `-- name: GetSyncState :one
SELECT profile_key, last_started_at, last_succeeded_at, last_closed_open_time,
       status, error_message
FROM binance_spot.sync_state
WHERE profile_key = $1
`

func (q *Queries) GetSyncState(ctx context.Context, profileKey string) (BinanceSpotSyncState, error) {
	row := q.db.QueryRow(ctx, getSyncState, profileKey)
	var i BinanceSpotSyncState
	err := row.Scan(
		&i.ProfileKey,
		&i.LastStartedAt,
		&i.LastSucceededAt,
		&i.LastClosedOpenTime,
		&i.Status,
		&i.ErrorMessage,
	)
	return i, err
}

const saveSyncState = `-- name: SaveSyncState :exec
INSERT INTO binance_spot.sync_state (
    profile_key, last_started_at, last_succeeded_at, last_closed_open_time,
    status, error_message
) VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (profile_key) DO UPDATE SET
    last_started_at = EXCLUDED.last_started_at,
    last_succeeded_at = COALESCE(EXCLUDED.last_succeeded_at, sync_state.last_succeeded_at),
    last_closed_open_time = COALESCE(EXCLUDED.last_closed_open_time, sync_state.last_closed_open_time),
    status = EXCLUDED.status,
    error_message = EXCLUDED.error_message
`

type SaveSyncStateParams struct {
	ProfileKey         string
	LastStartedAt      pgtype.Timestamptz
	LastSucceededAt    pgtype.Timestamptz
	LastClosedOpenTime pgtype.Timestamptz
	Status             string
	ErrorMessage       pgtype.Text
}

func (q *Queries) SaveSyncState(ctx context.Context, arg SaveSyncStateParams) error {
	_, err := q.db.Exec(ctx, saveSyncState,
		arg.ProfileKey,
		arg.LastStartedAt,
		arg.LastSucceededAt,
		arg.LastClosedOpenTime,
		arg.Status,
		arg.ErrorMessage,
	)
	return err
}

const successfulMarketSyncExists = `-- name: SuccessfulMarketSyncExists :one
SELECT COUNT(DISTINCT profile_key) = 2
FROM binance_spot.sync_state
WHERE profile_key IN ('binance:spot:USDT:1d:UTC', 'binance:spot:USDT:1h:UTC')
  AND last_succeeded_at IS NOT NULL
`

func (q *Queries) SuccessfulMarketSyncExists(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, successfulMarketSyncExists)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}
