// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const bootstrapAdministrator = `-- name: BootstrapAdministrator :exec
INSERT INTO app.users (telegram_id)
VALUES ($1)
ON CONFLICT (telegram_id) DO NOTHING
`

func (q *Queries) BootstrapAdministrator(ctx context.Context, telegramID int64) error {
	_, err := q.db.Exec(ctx, bootstrapAdministrator, telegramID)
	return err
}

const deleteUserByTelegramID = `-- name: DeleteUserByTelegramID :one
DELETE FROM app.users
WHERE telegram_id = $1
RETURNING id
`

func (q *Queries) DeleteUserByTelegramID(ctx context.Context, telegramID int64) (int64, error) {
	row := q.db.QueryRow(ctx, deleteUserByTelegramID, telegramID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const findUserByTelegramID = `-- name: FindUserByTelegramID :one
SELECT id, telegram_id, username, display_name
FROM app.users
WHERE telegram_id = $1
`

type FindUserByTelegramIDRow struct {
	ID          int64
	TelegramID  int64
	Username    pgtype.Text
	DisplayName pgtype.Text
}

func (q *Queries) FindUserByTelegramID(ctx context.Context, telegramID int64) (FindUserByTelegramIDRow, error) {
	row := q.db.QueryRow(ctx, findUserByTelegramID, telegramID)
	var i FindUserByTelegramIDRow
	err := row.Scan(
		&i.ID,
		&i.TelegramID,
		&i.Username,
		&i.DisplayName,
	)
	return i, err
}

const grantUserAccess = `-- name: GrantUserAccess :one
INSERT INTO app.users (telegram_id, username, display_name)
VALUES ($1, $2, $3)
ON CONFLICT (telegram_id) DO NOTHING
RETURNING id, telegram_id, username, display_name
`

type GrantUserAccessParams struct {
	TelegramID  int64
	Username    pgtype.Text
	DisplayName pgtype.Text
}

type GrantUserAccessRow struct {
	ID          int64
	TelegramID  int64
	Username    pgtype.Text
	DisplayName pgtype.Text
}

func (q *Queries) GrantUserAccess(ctx context.Context, arg GrantUserAccessParams) (GrantUserAccessRow, error) {
	row := q.db.QueryRow(ctx, grantUserAccess, arg.TelegramID, arg.Username, arg.DisplayName)
	var i GrantUserAccessRow
	err := row.Scan(
		&i.ID,
		&i.TelegramID,
		&i.Username,
		&i.DisplayName,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, telegram_id, username, display_name
FROM app.users
ORDER BY telegram_id ASC
`

type ListUsersRow struct {
	ID          int64
	TelegramID  int64
	Username    pgtype.Text
	DisplayName pgtype.Text
}

func (q *Queries) ListUsers(ctx context.Context) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.TelegramID,
			&i.Username,
			&i.DisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
