// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const findEnabledUserByTelegramID = `-- name: FindEnabledUserByTelegramID :one
SELECT id, telegram_id, username, display_name, is_enabled
FROM app.users
WHERE telegram_id = $1 AND is_enabled = TRUE
`

type FindEnabledUserByTelegramIDRow struct {
	ID          int64
	TelegramID  int64
	Username    pgtype.Text
	DisplayName pgtype.Text
	IsEnabled   bool
}

func (q *Queries) FindEnabledUserByTelegramID(ctx context.Context, telegramID int64) (FindEnabledUserByTelegramIDRow, error) {
	row := q.db.QueryRow(ctx, findEnabledUserByTelegramID, telegramID)
	var i FindEnabledUserByTelegramIDRow
	err := row.Scan(
		&i.ID,
		&i.TelegramID,
		&i.Username,
		&i.DisplayName,
		&i.IsEnabled,
	)
	return i, err
}
