/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as TopCoinsRouteImport } from './routes/top-coins'
import { Route as InstrumentsSymbolRouteImport } from './routes/instruments.$symbol'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const TopCoinsRoute = TopCoinsRouteImport.update({
  id: '/top-coins',
  path: '/top-coins',
  getParentRoute: () => rootRouteImport,
} as any)
const InstrumentsSymbolRoute = InstrumentsSymbolRouteImport.update({
  id: '/instruments/$symbol',
  path: '/instruments/$symbol',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/favorites': typeof FavoritesRoute
  '/top-coins': typeof TopCoinsRoute
  '/instruments/$symbol': typeof InstrumentsSymbolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/favorites': typeof FavoritesRoute
  '/top-coins': typeof TopCoinsRoute
  '/instruments/$symbol': typeof InstrumentsSymbolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/favorites': typeof FavoritesRoute
  '/top-coins': typeof TopCoinsRoute
  '/instruments/$symbol': typeof InstrumentsSymbolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/favorites' | '/top-coins' | '/instruments/$symbol'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/favorites' | '/top-coins' | '/instruments/$symbol'
  id: '__root__' | '/' | '/favorites' | '/top-coins' | '/instruments/$symbol'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FavoritesRoute: typeof FavoritesRoute
  TopCoinsRoute: typeof TopCoinsRoute
  InstrumentsSymbolRoute: typeof InstrumentsSymbolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/top-coins': {
      id: '/top-coins'
      path: '/top-coins'
      fullPath: '/top-coins'
      preLoaderRoute: typeof TopCoinsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instruments/$symbol': {
      id: '/instruments/$symbol'
      path: '/instruments/$symbol'
      fullPath: '/instruments/$symbol'
      preLoaderRoute: typeof InstrumentsSymbolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FavoritesRoute: FavoritesRoute,
  TopCoinsRoute: TopCoinsRoute,
  InstrumentsSymbolRoute: InstrumentsSymbolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
