/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as TopCoinsRouteImport } from './routes/top-coins'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminCommandsRouteImport } from './routes/admin.commands'
import { Route as AdminStrategiesRouteImport } from './routes/admin.strategies'
import { Route as AdminTokensRouteImport } from './routes/admin.tokens'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as InstrumentsSymbolRouteImport } from './routes/instruments.$symbol'
import { Route as AdminBacktestIndexRouteImport } from './routes/admin.backtest.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const TopCoinsRoute = TopCoinsRouteImport.update({
  id: '/top-coins',
  path: '/top-coins',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCommandsRoute = AdminCommandsRouteImport.update({
  id: '/commands',
  path: '/commands',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStrategiesRoute = AdminStrategiesRouteImport.update({
  id: '/strategies',
  path: '/strategies',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTokensRoute = AdminTokensRouteImport.update({
  id: '/tokens',
  path: '/tokens',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const InstrumentsSymbolRoute = InstrumentsSymbolRouteImport.update({
  id: '/instruments/$symbol',
  path: '/instruments/$symbol',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBacktestIndexRoute = AdminBacktestIndexRouteImport.update({
  id: '/backtest/',
  path: '/backtest/',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/favorites': typeof FavoritesRoute
  '/top-coins': typeof TopCoinsRoute
  '/admin/commands': typeof AdminCommandsRoute
  '/admin/strategies': typeof AdminStrategiesRoute
  '/admin/tokens': typeof AdminTokensRoute
  '/admin/users': typeof AdminUsersRoute
  '/instruments/$symbol': typeof InstrumentsSymbolRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/backtest/': typeof AdminBacktestIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/favorites': typeof FavoritesRoute
  '/top-coins': typeof TopCoinsRoute
  '/admin/commands': typeof AdminCommandsRoute
  '/admin/strategies': typeof AdminStrategiesRoute
  '/admin/tokens': typeof AdminTokensRoute
  '/admin/users': typeof AdminUsersRoute
  '/instruments/$symbol': typeof InstrumentsSymbolRoute
  '/admin': typeof AdminIndexRoute
  '/admin/backtest': typeof AdminBacktestIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/favorites': typeof FavoritesRoute
  '/top-coins': typeof TopCoinsRoute
  '/admin/commands': typeof AdminCommandsRoute
  '/admin/strategies': typeof AdminStrategiesRoute
  '/admin/tokens': typeof AdminTokensRoute
  '/admin/users': typeof AdminUsersRoute
  '/instruments/$symbol': typeof InstrumentsSymbolRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/backtest/': typeof AdminBacktestIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/favorites'
    | '/top-coins'
    | '/admin/commands'
    | '/admin/strategies'
    | '/admin/tokens'
    | '/admin/users'
    | '/instruments/$symbol'
    | '/admin/'
    | '/admin/backtest/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/favorites'
    | '/top-coins'
    | '/admin/commands'
    | '/admin/strategies'
    | '/admin/tokens'
    | '/admin/users'
    | '/instruments/$symbol'
    | '/admin'
    | '/admin/backtest'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/favorites'
    | '/top-coins'
    | '/admin/commands'
    | '/admin/strategies'
    | '/admin/tokens'
    | '/admin/users'
    | '/instruments/$symbol'
    | '/admin/'
    | '/admin/backtest/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  FavoritesRoute: typeof FavoritesRoute
  TopCoinsRoute: typeof TopCoinsRoute
  InstrumentsSymbolRoute: typeof InstrumentsSymbolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/top-coins': {
      id: '/top-coins'
      path: '/top-coins'
      fullPath: '/top-coins'
      preLoaderRoute: typeof TopCoinsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/commands': {
      id: '/admin/commands'
      path: '/commands'
      fullPath: '/admin/commands'
      preLoaderRoute: typeof AdminCommandsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/strategies': {
      id: '/admin/strategies'
      path: '/strategies'
      fullPath: '/admin/strategies'
      preLoaderRoute: typeof AdminStrategiesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tokens': {
      id: '/admin/tokens'
      path: '/tokens'
      fullPath: '/admin/tokens'
      preLoaderRoute: typeof AdminTokensRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/instruments/$symbol': {
      id: '/instruments/$symbol'
      path: '/instruments/$symbol'
      fullPath: '/instruments/$symbol'
      preLoaderRoute: typeof InstrumentsSymbolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/backtest/': {
      id: '/admin/backtest/'
      path: '/backtest'
      fullPath: '/admin/backtest/'
      preLoaderRoute: typeof AdminBacktestIndexRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminCommandsRoute: typeof AdminCommandsRoute
  AdminStrategiesRoute: typeof AdminStrategiesRoute
  AdminTokensRoute: typeof AdminTokensRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminBacktestIndexRoute: typeof AdminBacktestIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCommandsRoute: AdminCommandsRoute,
  AdminStrategiesRoute: AdminStrategiesRoute,
  AdminTokensRoute: AdminTokensRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminBacktestIndexRoute: AdminBacktestIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  FavoritesRoute: FavoritesRoute,
  TopCoinsRoute: TopCoinsRoute,
  InstrumentsSymbolRoute: InstrumentsSymbolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
